// SPDX-License-Identifier: Apache-2.0

// Command docgen regenerates docs/FLAGS.md, docs/KEYBINDINGS.md and
// docs/ERRORS.md from the tree's own registered surfaces, so the three
// documents can never say something the code does not: the registered cobra
// flag set of cmd/lazyslice (grouped as --help groups it), internal/tui's
// Bindings() table, and internal/event's Catalogue().
//
// `make docs` runs it with the repository's docs/ directory as -out. CI's
// docs-drift job runs it a second way, into a temporary directory, diffs the
// two, and fails the build on any difference from what is committed
// (ADR-002's enforcement mechanism 2; docs/CLAUDE.md "generated files are
// never hand-edited").
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "docgen: %s\n", err)
		os.Exit(1)
	}
}

func run() error {
	out := flag.String("out", "docs", "directory to write FLAGS.md, KEYBINDINGS.md and ERRORS.md into")
	flag.Parse()

	root, err := repoRoot()
	if err != nil {
		return err
	}

	outDir := *out
	if !filepath.IsAbs(outDir) {
		outDir = filepath.Join(root, outDir)
	}
	if mkErr := os.MkdirAll(outDir, 0o755); mkErr != nil {
		return fmt.Errorf("creating %s: %w", outDir, mkErr)
	}

	flagsMD, err := generateFlags(root)
	if err != nil {
		return fmt.Errorf("FLAGS.md: %w", err)
	}
	if wrErr := writeFile(filepath.Join(outDir, "FLAGS.md"), flagsMD); wrErr != nil {
		return wrErr
	}

	keysMD, err := generateKeybindings()
	if err != nil {
		return fmt.Errorf("KEYBINDINGS.md: %w", err)
	}
	if wrErr := writeFile(filepath.Join(outDir, "KEYBINDINGS.md"), keysMD); wrErr != nil {
		return wrErr
	}

	errorsMD, err := generateErrors()
	if err != nil {
		return fmt.Errorf("ERRORS.md: %w", err)
	}
	if wrErr := writeFile(filepath.Join(outDir, "ERRORS.md"), errorsMD); wrErr != nil {
		return wrErr
	}

	fmt.Printf("docgen: wrote FLAGS.md, KEYBINDINGS.md, ERRORS.md into %s\n", outDir)
	return nil
}

// writeFile writes content to path, creating or truncating it. 0o600 rather
// than a more permissive mode: nothing docgen writes needs a second reader's
// write access, and a generated Markdown file is not an executable or a
// shared config other tooling expects at a looser mode.
func writeFile(path, content string) error {
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return nil
}

// repoRoot walks up from the working directory to the module root, so docgen
// behaves the same whether invoked as `go run ./tools/docgen` from the repo
// root (make docs) or from anywhere else a caller finds convenient.
func repoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("getwd: %w", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("no go.mod found above %s", dir)
		}
		dir = parent
	}
}

// generatedHeader is prepended to every file this program writes, so a reader
// — and the CLAUDE.md rule against hand-editing a generated file — knows
// where it came from and how to regenerate it.
func generatedHeader(title, source string) string {
	return fmt.Sprintf(
		"<!-- Generated by tools/docgen from %s. Do not edit by hand — run `make docs`. -->\n\n# %s\n\n",
		source, title)
}

// mdEscape keeps a table cell's own text from being read as a Markdown table
// separator, or a stray newline from breaking the row onto a second line.
// Nothing in the three sources has either as of this writing, but a row
// silently losing its own columns is a worse failure than an escaped
// character nobody notices, so the rewrite is unconditional.
func mdEscape(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\n", " ")
	return s
}
