// SPDX-License-Identifier: Apache-2.0

// Command docgen regenerates docs/FLAGS.md, docs/KEYBINDINGS.md,
// docs/ERRORS.md and the first-run flag table in README.md from the tree's
// own registered surfaces, so none of the four can say something the code
// does not: the registered cobra flag set of cmd/lazyslice (grouped as
// --help groups it), internal/tui's Bindings() table, and internal/event's
// Catalogue().
//
// `make docs` runs it with the repository's docs/ directory as -out, which
// rewrites README.md in place (readme.go reads and writes the same file: the
// tree's own README.md is both the template for everything outside the two
// markers and the target). CI's docs-check job runs it a second way, into a
// temporary directory with -readme pointed at a scratch copy, diffs both
// against what is committed, and fails the build on any difference
// (ADR-002's enforcement mechanism 2; docs/CLAUDE.md "generated files are
// never hand-edited").
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "docgen: %s\n", err)
		os.Exit(1)
	}
}

func run() error {
	out := flag.String("out", "docs", "directory to write FLAGS.md, KEYBINDINGS.md and ERRORS.md into")
	readmeOut := flag.String("readme", "", "path to write the regenerated README.md into "+
		"(default: README.md at the repository root, i.e. rewrite it in place, but only when -out "+
		"is also the repository root; if -out points elsewhere, the default follows it to "+
		"<out>/README.md so a redirected run can never touch the tree's own README.md by accident); "+
		"the template for everything outside the markers is always read from the repository root's own README.md")
	flag.Parse()

	root, err := repoRoot()
	if err != nil {
		return err
	}

	outDir := *out
	if !filepath.IsAbs(outDir) {
		outDir = filepath.Join(root, outDir)
	}
	if mkErr := os.MkdirAll(outDir, 0o755); mkErr != nil {
		return fmt.Errorf("creating %s: %w", outDir, mkErr)
	}

	readmePath := *readmeOut
	if readmePath == "" {
		// -out redirected elsewhere means "leave the working tree alone":
		// follow it rather than defaulting back to the repo root's README.md.
		if outDir == root {
			readmePath = filepath.Join(root, "README.md")
		} else {
			readmePath = filepath.Join(outDir, "README.md")
		}
	} else if !filepath.IsAbs(readmePath) {
		readmePath = filepath.Join(root, readmePath)
	}
	if mkErr := os.MkdirAll(filepath.Dir(readmePath), 0o755); mkErr != nil {
		return fmt.Errorf("creating %s: %w", filepath.Dir(readmePath), mkErr)
	}

	flagsMD, err := generateFlags(root)
	if err != nil {
		return fmt.Errorf("FLAGS.md: %w", err)
	}
	if wrErr := writeFile(filepath.Join(outDir, "FLAGS.md"), flagsMD); wrErr != nil {
		return wrErr
	}

	keysMD, err := generateKeybindings()
	if err != nil {
		return fmt.Errorf("KEYBINDINGS.md: %w", err)
	}
	if wrErr := writeFile(filepath.Join(outDir, "KEYBINDINGS.md"), keysMD); wrErr != nil {
		return wrErr
	}

	errorsMD, err := generateErrors()
	if err != nil {
		return fmt.Errorf("ERRORS.md: %w", err)
	}
	if wrErr := writeFile(filepath.Join(outDir, "ERRORS.md"), errorsMD); wrErr != nil {
		return wrErr
	}

	readmeMD, err := generateReadme(root)
	if err != nil {
		return fmt.Errorf("README.md: %w", err)
	}
	if wrErr := writeFile(readmePath, readmeMD); wrErr != nil {
		return wrErr
	}

	fmt.Printf("docgen: wrote FLAGS.md, KEYBINDINGS.md, ERRORS.md into %s, and the first-run flag table into %s\n",
		outDir, readmePath)
	return nil
}

// writeFile writes content to path, creating or truncating it. 0o600 rather
// than a more permissive mode: nothing docgen writes needs a second reader's
// write access, and a generated Markdown file is not an executable or a
// shared config other tooling expects at a looser mode.
func writeFile(path, content string) error {
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return nil
}

// repoRoot walks up from the working directory to the module root, so docgen
// behaves the same whether invoked as `go run ./tools/docgen` from the repo
// root (make docs) or from anywhere else a caller finds convenient.
func repoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("getwd: %w", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("no go.mod found above %s", dir)
		}
		dir = parent
	}
}

// generatedHeader is prepended to every file this program writes, so a reader
// — and the CLAUDE.md rule against hand-editing a generated file — knows
// where it came from and how to regenerate it.
func generatedHeader(title, source string) string {
	return fmt.Sprintf(
		"<!-- Generated by tools/docgen from %s. Do not edit by hand — run `make docs`. -->\n\n# %s\n\n",
		source, title)
}

// mdEscape keeps a table cell's own text from being read as a Markdown table
// separator, or a stray newline from breaking the row onto a second line.
// Nothing in the three sources has either as of this writing, but a row
// silently losing its own columns is a worse failure than an escaped
// character nobody notices, so the rewrite is unconditional.
func mdEscape(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\n", " ")
	return s
}

// mdEscapeText is mdEscape for a prose cell, one that is not wrapped in a code
// span. It also escapes angle brackets: a placeholder such as <source major>
// is a well-formed HTML tag name, and GitHub's Markdown pipeline drops it from
// the rendered table instead of printing it (T-0259 review). A code-span cell
// keeps mdEscape, because an entity inside backticks renders literally.
func mdEscapeText(s string) string {
	s = mdEscape(s)
	s = strings.ReplaceAll(s, "<", "&lt;")
	s = strings.ReplaceAll(s, ">", "&gt;")
	return s
}
