export const meta = {
  name: 'lazyslice-hardening',
  description: 'Phase 5: torture schemas, failure UX, performance, then a three-attacker red team with one fix round and re-attack',
  phases: [
    { title: 'Features', detail: 'section 14 phase-5 items: TUI screens, provisioning and rung 4, polymorphic inference, CI matrix and supply chain' },
    { title: 'Backlog', detail: 'review follow-ups carried into phase 5, in dependency order' },
    { title: 'Harden', detail: 'torture, the 2026-09-09 review findings, failure UX, performance, each through implement.js in sequence' },
    { title: 'Red team', detail: 'three attackers try to make the tool leak; fix; re-attack' },
    { title: 'Red team fixes', detail: 'the round-2 findings as tasks, then a replay of the leaking attempts' },
    { title: 'Gate', detail: 'what section 14 and the accepted ADRs promise for v1 and the 2026-09-17 audit found missing; no replay' },
  ],
}
const REPO = '/Users/gareth/personal_repos/lazyslice'
const IMPL = `${REPO}/.claude/workflows/implement.js`
// args: { step: 'features' | 'backlog' | 'harden' | 'redteam', from?: index }  one step per usage window; from skips merged tasks in features or backlog
const step = (args && args.step) || 'features'

const FEATURES = [
  { id: 'T-TUI', title: 'Bubble Tea reasons and plan screens', stage: 'tui', paths: ['docs/FLAGS.md', 'internal/tui/', 'cmd/lazyslice/'], integration: false,
    brief: `Implement internal/tui per docs/adr/002-tui.md and ARCHITECTURE.md §7 and §9: the reasons screen (classifier decisions with their reason strings, per-column opt-out that builds the same --unmask REASON flag) and the plan screen (tables, estimates, caps hit), both building a core.Request. The line printer stays the default; the TUI runs only on a TTY when the flag or the question ladder invokes it. Every action shows its keybinding; add the ADR-002 test that fails any keybinding lacking a CLI flag. Model tests with the framework's test utilities.` },
  { id: 'T-PROVISION', title: 'Provisioning --create-target and rung 4', stage: 'discover', paths: ['docs/FLAGS.md', 'internal/discover/', 'cmd/lazyslice/'], integration: true,
    brief: `Implement discover/provision per ARCHITECTURE.md §9 "Provisioning": --create-target creates and starts a Postgres container matching the source major, and rung 4 offers stopped containers. The T2 gate runs on the provisioned target exactly as on any other. Tracker T-0063 records the seam T-DISCOVER left: widen pipeline.Provisioner to carry the generated POSTGRES_PASSWORD, restore the prompter and controlling-terminal read that were removed as unreachable, and wire --create-target and the one blocking question Q1 per ADR-008 section 6. Integration test against Docker; skip cleanly when Docker is absent.` },
  { id: 'T-POLY', title: 'Polymorphic association inference', stage: 'plan', paths: ['internal/plan/', 'internal/introspect/'], integration: false,
    brief: `Implement ARCHITECTURE.md §3.2 polymorphic inference: detect _type/_id and content_type_id/object_id pairs, add parent-direction virtual edges, report them in the plan, and keep the caps bounding them. Until now the plan printed "polymorphic pair detected, not followed: no constraint"; keep that message for pairs that inference cannot resolve. Tests on nasty.sql's polymorphic pair.` },
  { id: 'T-CI5', title: 'Five-major CI matrix, SBOM, govulncheck, docgen and docs drift', stage: 'foundations', paths: ['.github/', 'Makefile', '.goreleaser.yaml', 'tools/docgen/', 'docs/FLAGS.md', 'docs/KEYBINDINGS.md', 'docs/ERRORS.md', 'internal/tui/'], integration: false,
    brief: `Per ADR-003 and THREAT_MODEL T10: the integration job runs against Postgres 14, 15, 16, 17, and 18 via testcontainers; add govulncheck to CI; add SBOM generation and checksum signing to the goreleaser release if not already present. Write tools/docgen, a small Go program that generates docs/FLAGS.md from the registered cobra flag set of cmd/lazyslice (name, type, default, help, grouped as --help groups them), docs/KEYBINDINGS.md from internal/tui's exported Bindings() table (key, action, the flag it is), and docs/ERRORS.md from internal/event's Catalogue() (code, stage, exit code, message template); add a make docs target that regenerates them and a CI job that fails when the committed files differ from regenerated output (ADR-002's enforcement mechanism). Add the unsafe-flag grep job from CONCEPT.md's enforcement list (fail on --no-mask, --disable-mask, --skip-mask, or any flag whose name contains unmask other than the per-column --unmask TABLE.COL=REASON). Check the workflow files parse and run the docs and grep jobs locally.` },
]

const from = (args && args.from) || 0
if (step === 'features') {
  phase('Features')
  const results = []
  for (const t of FEATURES.slice(from)) {
    const r = await workflow({ scriptPath: IMPL }, { ...t, model: t.model || 'sonnet', effort: t.effort || 'medium' })
    results.push(r)
    if (!r || r.status !== 'merged') { log(`Stopped at ${t.id}`); return { results, stopped_at: t.id } }
  }
  return { results }
}

const TASKS = [
  { id: 'T-0083', title: 'Target type registration for CopyFrom: enum, domain, composite and user-defined array types', stage: 'load', paths: ['internal/pg/', 'internal/load/', 'internal/introspect/', 'internal/pipeline/', 'testdata/', 'internal/testutil/'], integration: './internal/pg/... ./internal/load/...',
    brief: `Read tracker/tasks/T-0083-*.md. ARCHITECTURE.md section 11.1 and ADR-005 say load registers the source's user types on each target connection; nothing does, so an enum array or a composite column fails CopyFrom mid-table (SQLSTATE 54000 or 42804; THREAT_MODEL T8's empty-or-complete property then does the cleanup, but the run fails). Implement it in internal/pg: from the catalog internal/introspect already reads (enums, domains, composites, and array types over them), register the OIDs with pgx's type map on every target connection after the DDL has created them (an AfterConnect on the target pool is fine; the source pool stays untouched), and wire the schema through so pg has it. Tests: nasty.sql already has an enum, a composite key type and arrays; add a table with an enum[] column and one with a composite-typed column if absent, and prove a full load of nasty succeeds and I1 to I6 stay green. Run make lint && make test && make integration and paste the output.` },
  { id: 'T-TORTURE', title: 'Schema torture suite', stage: 'hardening', paths: ['docs/ERRORS.md', 'testdata/torture/', 'internal/', 'Makefile', 'docs/TORTURE.md'], integration: true,
    brief: `Collect ten real open-source PostgreSQL schemas of different shapes: Discourse, GitLab (a trimmed subset is acceptable, say why), Mastodon, Odoo (subset), Metabase, Supabase auth schema, Cal.com, Plausible, a Django default project with auth and admin, and a Rails default with ActiveStorage. Put each under testdata/torture/<name>/ with its source URL and commit pinned in a README. Add a make torture target that loads each into a container with a small amount of generated data (a generator script per schema, a few hundred rows in the most-connected tables) and runs a snapshot from its most-connected table into a second container, then the invariant checks. For every failure, write a minimal reproduction into testdata/regressions/ before fixing it in internal/. Write docs/TORTURE.md with a table: schema, tables, run time, failures found and fixed, and for three schemas a hand-labelled PII truth set with precision and recall. Do not stop until at least nine of ten snapshot cleanly and the tenth fails with a message that names the exact cause.` },
  { id: 'T-HARD-A', title: 'Unique credential masker; fingerprint after the plan picks a generator; not-recreatable refusal at plan', stage: 'plan', paths: ['docs/ERRORS.md', 'mask/', 'internal/plan/', 'internal/classify/', 'internal/core/', 'internal/load/', 'internal/transform/', 'internal/pipeline/', 'internal/event/catalogue.yml', 'testdata/'], integration: './internal/plan/... ./internal/load/... ./internal/core/...',
    brief: `Read tracker/tasks/T-0098-*.md, T-0101-*.md and T-0097-*.md. (1) T-0098: credential's only masker is a fixed literal with Domain 1, so a unique credential column (refresh_tokens.token, users.confirmation_token: twenty columns across the torture schemas) is refused at plan and the only escape is --unmask, which copies a credential verbatim. Add a credential_unique generator in mask/ that emits an unusable, clearly-fake token derived from h with a domain of at least 2^64 (for example lazyslice-invalid- followed by a hash-derived suffix, length-fitted to the column), registered so the plan's widest-generator pick finds it; the fixed literal stays the default for non-unique credential columns. Re-measure docs/TORTURE.md's counts and update the torture catalogue test that counts flags by kind. (2) T-0101: the plan writes the picked masker onto Decision.Masker after Classification.Fingerprint was computed, so an escalation to a unique generator changes masked values without changing the fingerprint. Decide: recompute the fingerprint in core after plan (fingerprint = classification plus picks) and record the decision in ARCHITECTURE.md's §5 determinism scope by reporting the exact sentence to change in your concerns; test that a column becoming unique between runs prints classification changed. (3) T-0097: move the not-recreatable check from load.Load to the plan stage in core so exit 13 is raised before extraction and before anything in the target is dropped; regression 002 and the two exit-13 catalogue rows already say stage plan. Run make lint && make test && make integration and paste the output.` },
  { id: 'T-0112', title: 'Re-measure the torture catalogue after credential_unique: strip the eighteen credential opt-outs, re-run make torture, re-count', model: 'sonnet', reviewers: 1, stage: 'hardening', paths: ['internal/invariants/', 'docs/TORTURE.md', 'ROADMAP.md', 'testdata/torture/'], integration: false,
    brief: `Read tracker/tasks/T-0112-*.md including its Log, which corrects the count: eighteen --unmask flags in internal/invariants's torture catalogue are tagged T-0098 (supabase-auth 6, calcom 1, mastodon 2, gitlab 8, discourse 1), forced only because a unique credential column could not be masked. T-HARD-A (commit ecc42ae) added the credential_unique masker. Remove those eighteen flags one schema at a time (a column may carry a second reason; keep any flag whose other reason still holds and say so), run make torture, and confirm every run still passes with the columns now masked rather than copied. Then re-measure and update, from the actual run: the flags-by-kind assertion in internal/invariants/torture_test.go, docs/TORTURE.md's counts and its Found-and-not-fixed row for T-0098 (now fixed), internal/invariants/CLAUDE.md's sentence, and ROADMAP.md's gate-5 torture line. Paste the make torture summary and the new counts. Run make lint && make test too.` },
  { id: 'T-HARD-B', title: 'Composite columns fail closed; arrays of extension types sampled element-wise; auth-schema name rules; URLs are not credentials', stage: 'classify', paths: ['docs/ERRORS.md', 'internal/classify/', 'internal/introspect/', 'internal/textsig/', 'internal/plan/', 'internal/transform/', 'internal/pipeline/', 'internal/event/catalogue.yml', 'testdata/'], integration: './internal/classify/... ./internal/introspect/... ./internal/plan/...',
    brief: `Read tracker/tasks/T-0094-*.md, T-0103-*.md, T-0104-*.md and T-0100-*.md. (1) T-0094, THREAT_MODEL T1: a composite column now loads and nothing masks or scans it, so personal data inside a composite field is copied silently. Decision: fail closed. Classify runs the value validators over the composite's text form; a hit at possible or above refuses at plan with exit 12 naming the column and offering --skip-table or a reasoned --unmask, never a silent copy; a composite with no hit is copied and the reason says so. (2) T-0103: an array of an extension type (citext[]) arrives from the source pool as one opaque string, so a list of email addresses is decided none. Add a Postgres array-literal splitter in classify's sample flattening for any array-typed column whose sample is a string, with quoting and escaping handled per the Postgres text format, and a test on a citext[] of addresses. (3) T-0104: extend the credential and online_id name rules in rules.yml with the spellings real auth schemas use (the task lists them from supabase, gitlab, mastodon); add each to the 50-name confusion-matrix fixture. (4) T-0100: textsig.LooksSecret must not classify a URL as a credential; a value that parses as a URL with a scheme and host is online_id or url, never credential, with a test. Run make lint && make test and the named integration packages, and paste the output.` },
  { id: 'T-HARD-C', title: 'RegisterTypes on pipeline.Writer; torture build tag linted; testdata docs current', model: 'sonnet', reviewers: 1, stage: 'foundations', paths: ['internal/pipeline/', 'internal/verify/', 'internal/load/', 'internal/pg/', 'internal/core/', '.golangci.yml', 'testdata/', 'internal/testutil/', 'internal/invariants/', 'mask/', 'internal/classify/', 'docs/TORTURE.md', 'ROADMAP.md'], integration: './internal/load/... ./internal/verify/...',
    brief: `Read tracker/tasks/T-0093-*.md, T-0105-*.md and T-0096-*.md. (1) T-0093: make RegisterTypes a method on pipeline.Writer so the load's type registration is compiler-checked; update the two test doubles in internal/verify (writeOnly, readableWriter) and core's readableWriter; remove load's by-name refusal once the compiler enforces it. (2) T-0105: .golangci.yml's build-tags list gains torture so the torture suite is linted; fix whatever it flags. (3) T-0096: testdata/CLAUDE.md and testdata/README.md still say two fixtures and nothing else; describe the torture directory, the regressions directory, and the build script. (4) T-0122: verify's second net lost URL coverage when textsig.LooksSecret stopped matching URLs; add the online_id entry (category pipeline.CatOnlineID, text, ok textsig.ValidURL) ahead of the credential entry in internal/verify/validators.go with a test. (5) T-0113: testdata/regressions 004 and 007 still assert an exit-12 refusal that credential_unique removed; re-cut their headers to the behaviour now expected (the column masks, exit 0, target holds lazyslice-invalid- prefixed unique tokens) and make sure make torture exits 0; then T-0115 and T-0116: re-measure docs/TORTURE.md's recall and flag counts from that run and update the flags-by-kind assertion; tick ROADMAP.md's torture gate item back on only if make torture exits 0, and paste that. (6) T-0114: mask/CLAUDE.md and mask/gen_credential.go still say the torture counts are un-re-measured; fix, and repoint the three internal/classify notes that say T-0099 carries the rule at ADR-011. (7) T-0121 decision: a public_key column is category credential (masked to the unusable literal, or credential_unique under a unique index); add the name rule. Run make lint && make test && make torture and the named integration packages, and paste the output.` },
  { id: 'T-0118', title: 'Transform masks an array that arrives as a text literal element-wise', stage: 'extract', paths: ['internal/transform/', 'internal/extract/', 'internal/pipeline/', 'mask/', 'testdata/'], integration: './internal/transform/... ./internal/extract/...',
    brief: `Read tracker/tasks/T-0118-*.md. T-0103 made classify split an array that arrives from the unregistered source pool as one text literal (citext[] and other extension-type arrays), so such a column is now decided email or another category. Transform must mask it the same way: parse the Postgres array-literal grammar (quoting, escaping, NULL elements, empty array, dimensions), mask each element through the column's masker with h computed per element, and re-emit a valid literal the load can write; a NULL column stays NULL. Add a regression in testdata/regressions with a citext[] of addresses that loads and whose target holds no source address, and unit tests for the grammar edge cases. Run make lint && make test and the named integration packages, and paste the output.` },
  { id: 'T-0129', title: 'Verify handles a masked array column whose target value does not decode to a slice', model: 'opus', reviewers: 1, stage: 'verify', paths: ['docs/ERRORS.md', 'internal/verify/', 'internal/pipeline/', 'internal/event/catalogue.yml', 'testdata/'], integration: './internal/verify/...',
    brief: `Read tracker/tasks/T-0129-*.md and T-0127-*.md. When the planner stops refusing arrays that arrive as text literals (T-0127), verify's residual scan and second net must not go blind on such a column: a masked array column whose target value does not decode to a slice is either split by the same array-literal grammar transform uses and scanned element-wise, or refused at exit 9 naming the column. Decide, implement, test with a citext[] fixture, and record the rule in internal/verify/CLAUDE.md. This lands before T-0127.` },
  { id: 'T-0127', title: 'Planner stops refusing arrays that arrive as text literals; regression 009 flips to ok', model: 'sonnet', reviewers: 1, stage: 'plan', paths: ['internal/plan/', 'testdata/', 'internal/invariants/', 'internal/transform/CLAUDE.md'], integration: './internal/plan/... ./internal/transform/...',
    brief: `Read tracker/tasks/T-0127-*.md. T-0129 has landed. Drop arrayArrivesAsLiteral from internal/plan's write-back check so an array column that arrives as a text literal is planned and masked element-wise by transform; flip testdata/regressions/009's header to ok and confirm its leak assertion runs and passes under make torture; update internal/transform/CLAUDE.md's owed list. Paste make torture's summary.` },
  { id: 'T-0130', title: 'Target ownership: run lease and lock-and-recheck before every destructive DDL', model: 'opus', reviewers: 1, stage: 'load', paths: ['docs/ERRORS.md', 'internal/pg/', 'internal/load/', 'internal/core/', 'internal/pipeline/', 'internal/event/catalogue.yml', 'internal/testutil/', 'testdata/', 'THREAT_MODEL.md', 'ARCHITECTURE.md'], integration: './internal/pg/... ./internal/load/... ./internal/core/...',
    brief: `Read tracker/tasks/T-0130-*.md, then docs/reviews/2026-09-09/REVIEW.md finding 1 and its evidence (docs/reviews/2026-09-09/evidence/target_race.py, race.log). Implement both controls the task names: the run lease (pg_try_advisory_lock on a dedicated target connection held until the marker is finished; a second run exits 4 naming the holder) and the per-table lock-and-recheck (LOCK TABLE IN ACCESS EXCLUSIVE MODE NOWAIT, then re-verify what the gate approved, refuse at exit 4 on a change, roll back, mark failed). Turn target_race.py into an integration test. Write the dated amendments to THREAT_MODEL.md T2 and ARCHITECTURE.md section 11.2 yourself, in place, stating the controls and the residual. Add catalogue rows for the new exit-4 reasons. Run make lint && make test and the named integration packages, and paste the output.` },
  { id: 'T-0133', title: 'Core owns the run lifecycle; complete only after verify; a residual failure empties the target', model: 'sonnet', reviewers: 1, stage: 'core', paths: ['docs/ERRORS.md', 'internal/core/', 'internal/load/', 'internal/pg/', 'internal/pipeline/', 'internal/event/catalogue.yml', 'internal/testutil/', 'testdata/', 'THREAT_MODEL.md'], integration: './internal/load/... ./internal/core/... ./internal/pg/...',
    brief: `Read tracker/tasks/T-0133-*.md, then docs/reviews/2026-09-09/REVIEW.md finding 4 and evidence/verify_failure.log. Load stops writing complete; core writes complete after verify passes and failed after any verify failure; on an exit-9 class failure core drops every table it loaded before marking failed (the target holds personal data by definition), on exit 8 the data stays. Say in internal/pg/marker.go whether you kept running or added loaded, and why. Write the dated amendment to THREAT_MODEL.md T8 yourself. Tests: the two-row column reproduces exit 9 with an empty target and a marker at failed; TestKillNineLeavesRunningMarker still passes. Run make lint && make test and the named integration packages, and paste the output.` },
  { id: 'T-0131', title: 'Events carry no source value; polymorphic reports by count and digest; output-sink canary test', model: 'sonnet', reviewers: 1, stage: 'plan', paths: ['docs/FLAGS.md', 'docs/ERRORS.md', 'internal/plan/', 'internal/classify/', 'internal/core/', 'internal/event/', 'cmd/lazyslice/', 'internal/testutil/', 'testdata/'], integration: './internal/plan/... ./cmd/lazyslice/...',
    brief: `Read tracker/tasks/T-0131-*.md, then docs/reviews/2026-09-09/REVIEW.md finding 2 and evidence/polymorphic_log.log. Apply the rule the task states (identifiers, counts and keyed digests only; never a value read from a source row) to polymorphic.go and to every other path in internal/plan and internal/classify that quotes a sample into an explanation; extend the value-free serialisation test in internal/event to reason arguments; add the canary test in cmd/lazyslice (unique canary per text column, run with --json and at the highest verbosity, assert no canary in stdout, stderr, lazyslice.yml or any written file). Run make lint && make test and the named integration packages, and paste the output.` },
  { id: 'T-0132', title: 'The masker is chosen per FK-connected equality group', model: 'opus', reviewers: 1, stage: 'plan', paths: ['docs/ERRORS.md', 'internal/plan/', 'internal/classify/', 'internal/transform/', 'internal/pipeline/', 'internal/event/catalogue.yml', 'testdata/', 'internal/invariants/', 'ARCHITECTURE.md'], integration: './internal/plan/... ./internal/transform/... ./internal/load/...',
    brief: `Read tracker/tasks/T-0132-*.md, then docs/reviews/2026-09-09/REVIEW.md finding 3 and evidence/fk_masker.log. The plan computes equality groups (columns connected by any foreign key, transitively, plus what classify already unified) and picks one masker per group: the widest generator any member needs, checked to fit every member; no fit for every member is exit 12 naming the group. Add the regression under testdata/regressions (two tables from the review, expected ok, FK valid, both columns hold the same masked token) and confirm it under make torture. Write the dated amendment to ARCHITECTURE.md section 5 yourself and record the rule in internal/plan/CLAUDE.md. Run make lint && make test && make torture and the named integration packages, and paste the output.` },
  { id: 'T-0134', title: 'Recreated DDL carries no sensitive literal; verify scans the target catalog', model: 'opus', reviewers: 1, stage: 'load', paths: ['docs/ERRORS.md', 'internal/load/', 'internal/plan/', 'internal/verify/', 'internal/classify/', 'internal/introspect/', 'internal/pipeline/', 'internal/event/catalogue.yml', 'testdata/', 'internal/invariants/', 'ARCHITECTURE.md', 'THREAT_MODEL.md'], integration: './internal/load/... ./internal/verify/... ./internal/plan/...',
    brief: `Read tracker/tasks/T-0134-*.md, then docs/reviews/2026-09-09/REVIEW.md finding 5 and evidence/ddl_default.log. Implement the rule the task states: literals in a default, CHECK or generated expression are inside the data boundary; a masked column has the literals in its default masked through its own masker; a CHECK or generated expression on a masked column that cannot be rewritten is exit 13 naming the object; a strong-validator hit in any such literal on an unmasked column is exit 12 at plan naming the object with the --unmask escape; verify adds a catalog pass over pg_attrdef and pg_constraint in the target that fails exit 9 on a strong hit. Regression under testdata/regressions: the review schema, expected ok, target default holds a masked address; confirm under make torture. Write the dated amendments to ARCHITECTURE.md section 11.1 and THREAT_MODEL.md T1 yourself. Run make lint && make test && make torture and the named integration packages, and paste the output.` },
  { id: 'T-0161', title: 'Core fills PlanRequest.Key before the plan stage so a masked default is masked, not refused; regression 011 flips to ok', model: 'sonnet', reviewers: 1, stage: 'core', paths: ['internal/core/', 'internal/pipeline/', 'internal/plan/', 'internal/verify/', 'testdata/', 'internal/invariants/', 'docs/ERRORS.md', 'internal/event/catalogue.yml', 'ARCHITECTURE.md', 'THREAT_MODEL.md'], integration: './internal/core/... ./internal/plan/... ./internal/verify/...',
    brief: `Read tracker/tasks/T-0161-*.md and T-0134-*.md, then internal/plan/ddlliteral.go and internal/core/run.go (planStage at about line 1194, planRequest at 1272, resolveKey called first inside move at 1376). Move key resolution ahead of the plan stage for any run that will write, and fill pipeline.PlanRequest.Key from it, so ARCHITECTURE.md section 11.1 arm 1 (a masked column default masked through its own masker) runs from the CLI. For a plan-only run: resolve the key if one is already present (env or ./lazyslice.secret) and otherwise plan with a nil key and print one line saying which defaults will be masked once a key exists; do not create a secret for a plan-only run. Flip testdata/regressions/011-masked-column-default-holds-a-literal.sql to expect ok and assert under make torture that the target pg_attrdef holds a masked address and that verify's catalog pass exempts exactly that default (pipeline.Column.DefaultOriginal set); remove the exception note for 011 from testdata/regressions/README.md. Correct the notes T-0134 left in internal/plan/CLAUDE.md, ARCHITECTURE.md 11.1 and THREAT_MODEL.md T1 that say the arm is dormant (ARCHITECTURE.md and THREAT_MODEL.md are in your paths for those sentences only). Run make check && make torture and the named integration packages, and paste the output.` },
  { id: 'T-0136', title: 'Second net: one strong hit in an unmasked column is a finding; classify masks a mixed column', model: 'sonnet', reviewers: 1, stage: 'verify', paths: ['internal/verify/', 'internal/classify/', 'internal/textsig/', 'internal/pipeline/', 'testdata/', 'docs/TORTURE.md', 'internal/invariants/'], integration: './internal/verify/... ./internal/classify/...',
    brief: `Read tracker/tasks/T-0136-*.md, then docs/reviews/2026-09-09/REVIEW.md finding 7 and evidence/sparse_email.log. Verify: a strong validator hitting even one distinct value in an unmasked column is exit 9 naming the column and the count (never the value); the ratio rule stays for dictionary and heuristic validators. Classify: any strong hit among the samples with a ratio below the category threshold decides free_text, masked, with the explanation the task gives. Regression under testdata/regressions: one address among nineteen plain strings, expected ok, target holds no address. Run make torture; a torture schema that now needs a flag gets it recorded in docs/TORTURE.md with the reason, and the flags-by-kind assertion is re-measured from the run. Run make lint && make test && make torture and the named integration packages, and paste the output.` },
  { id: 'T-0137', title: 'JSON object keys that a strong validator hits are masked', model: 'sonnet', reviewers: 1, stage: 'transform', paths: ['internal/transform/', 'internal/verify/', 'mask/', 'testdata/', 'SECURITY.md'], integration: './internal/transform/... ./internal/verify/...',
    brief: `Read tracker/tasks/T-0137-*.md, then docs/reviews/2026-09-09/REVIEW.md finding 8 and evidence/json_keys.log. A key that parses as an email, phone or credit card is masked through that category masker; other keys stay; the JSON walk in verify scans keys as well as values. Regression under testdata/regressions: the review document, expected ok, target key masked. Narrow the SECURITY.md limitation to what remains. Run make lint && make test && make torture and the named integration packages, and paste the output.` },
  { id: 'T-0135', title: 'dsn.Ref keeps the non-secret transport parameters', model: 'sonnet', reviewers: 1, stage: 'discover', paths: ['internal/dsn/', 'internal/emit/', 'internal/discover/', 'internal/config/', 'internal/pipeline/', 'testdata/'], integration: './internal/discover/...',
    brief: `Read tracker/tasks/T-0135-*.md, then docs/reviews/2026-09-09/REVIEW.md finding 6. Add the allowlisted Params map to dsn.Ref (sslmode, sslrootcert, sslcert, sslkey, connect_timeout, application_name, options; never password or a whole DSN), carry it through the emitted endpoint block and the discover reconstruction, show it in Ref.String as a count only, warn by name on a dropped key. Tests in dsn, emit and discover round-trip sslmode=verify-full with sslrootcert. Run make lint && make test and the named integration package, and paste the output.` },
  { id: 'T-0138', title: 'mapping_file refused explicitly until implemented; ADR-012', model: 'sonnet', reviewers: 1, stage: 'peripheral', paths: ['docs/FLAGS.md', 'internal/pipeline/', 'internal/config/', 'internal/emit/', 'internal/plan/', 'internal/repo/', 'internal/core/', 'cmd/lazyslice/', 'internal/event/catalogue.yml', 'docs/adr/', 'docs/ERRORS.md', 'testdata/'], integration: false,
    brief: `Read tracker/tasks/T-0138-*.md, then docs/reviews/2026-09-09/REVIEW.md finding 10. A yml naming mapping_file exits 2 with the message the task gives; the unique-domain refusal drops that remedy; emit stops writing the field; repo keeps protecting a named path. Write docs/adr/012-mapping-file-deferred.md (status proposed) superseding the mapping_file paragraph of ADR-006 for v1 and naming T-0142 as the implementing task. Regenerate docs/ERRORS.md with make docs if the catalogue changed. Run make lint && make test and paste the output.` },
  { id: 'T-0139', title: 'Torture suite fingerprints the source before the run, with a negative control', model: 'sonnet', effort: 'low', reviewers: 1, stage: 'hardening', paths: ['internal/invariants/'], integration: false,
    brief: `Read tracker/tasks/T-0139-*.md, then docs/reviews/2026-09-09/REVIEW.md finding 11. Move beforeRows and beforeCatalog ahead of runTool in internal/invariants/torture_test.go and add the negative control (one UPDATE on the source between baseline and comparison must make compareFingerprints fail). Run make lint && make test && make torture and paste the summary.` },
  { id: 'T-0119', title: 'A table-scoped name rule for refresh_tokens.parent and its kind', model: 'sonnet', reviewers: 1, stage: 'classify', paths: ['internal/classify/', 'testdata/', 'docs/TORTURE.md', 'internal/invariants/'], integration: './internal/classify/...',
    brief: `Read tracker/tasks/T-0119-*.md. Decision: the rule pack gains a table-scoped pattern (table regexp plus column regexp, one category, same priority field as a name rule), used first for refresh_tokens.parent as credential; document the field in rules.yml and internal/classify/CLAUDE.md. Flip internal/classify/supabase_misses_test.go from pinning the miss to asserting the mask, re-measure the confusion-matrix fixture and the supabase-auth truth set in docs/TORTURE.md from an actual make torture run. Run make lint && make test && make torture and the named integration package, and paste the output.` },
  { id: 'T-0140', title: 'CI runs the torture suite on main; release requires a green CI run for the tagged commit', model: 'sonnet', reviewers: 1, stage: 'foundations', paths: ['.github/', 'docs/RUNBOOK.md', 'Makefile'], integration: false,
    brief: `Read tracker/tasks/T-0140-*.md. Add a torture job to .github/workflows/ci.yml on pushes to main only; make .github/workflows/release.yml refuse unless the ci workflow succeeded on the same sha (a first step querying the checks API). Do not widen the matrix. Note the gate in docs/RUNBOOK.md. Validate both workflow files with actionlint if installed, otherwise with a YAML parse. Run make lint && make test and paste the output.` },
  { id: 'T-FAILUX', title: 'Failure UX and error catalogue', stage: 'hardening', paths: ['internal/', 'cmd/', 'docs/ERRORS.md'], integration: true,
    brief: `Audit every error path. Each user-facing error must say what went wrong, which table or column, and the exact flag or action that fixes it. No stack trace reaches the user without --debug. Partial failures must leave the target either empty or complete; verify the drop-on-failure path with a test that kills the load mid-way. Define an error type per failure class in one package and write docs/ERRORS.md as the catalogue; add a test that every error type in the code appears in the catalogue and vice versa. Every fix is a targeted edit; do not restructure packages.` },
  { id: 'T-PERF', title: 'Performance baseline', stage: 'hardening', paths: ['internal/extract/', 'internal/load/', 'internal/transform/', 'docs/PERF.md', 'Makefile', '.github/'], integration: true,
    brief: `Profile a snapshot of 5,000 root rows from a source whose child table has 2,000,000 rows (extend the nasty.sql generator with a size parameter; the 20,000,000-row run is a 0.2 item, T-0157, and this task does not attempt it). Report where time goes per stage with pprof. Target: under 60 seconds on this machine against local containers. Optimise only the top two hotspots. Also make extract batch by bytes as well as rows (a byte cap per batch, default a few MiB, so 2,000 one-MiB values no longer form one batch; docs/reviews/2026-09-09/REVIEW.md finding 9), and record peak RSS for a wide-row run next to the narrow-row numbers. Write the before and after numbers, the commands, and the flame summary into docs/PERF.md. Add a make bench target and a CI job that fails if extract throughput drops more than 20% from the recorded baseline stored in testdata/bench/baseline.json.` },
]

const BACKLOG = [
  { id: 'T-0075', title: 'CI red from provisioning: Windows file mode, container readiness deadline on runners', model: 'opus', reviewers: 1, stage: 'discover', paths: ['internal/discover/', 'internal/testutil/', '.github/workflows/ci.yml'], integration: './internal/discover/...',
    brief: `Read tracker/tasks/T-0075-*.md. Two CI defects from the provisioning work, both reproduced in GitHub run 34207236918. (1) Windows: TestProvisionCreatesTheContainerSection9Describes asserts the generated password file is 0o600 and Windows reports -rw-rw-rw- because os.Chmod does not carry POSIX modes there. Keep the 0600 guarantee on unix, and on windows skip the mode assertion with a comment naming the limitation (an ACL-based restriction is a later task; note it in internal/discover/provision/CLAUDE.md). (2) Linux runners: every provisioning integration test fails with 'did not accept a connection within 1m0s' while passing locally. The runners have no cached postgres image, so the pull almost certainly runs inside the readiness deadline; verify by removing the image locally (docker rmi postgres:18) and running TestProvisionCreatesAndReusesARealContainer, which should reproduce. Fix: pull or confirm the image before the readiness clock starts (log the pull as its own progress line), start the deadline from container start, wait on the container's 'database system is ready to accept connections' second occurrence before dialling, and make the deadline configurable with a sane default (90 s) that CI can raise through an environment variable read by the provisioner. Also check that the provisioner dials the published host port on the loopback address the daemon actually bound (IPv4 0.0.0.0 publishes are not reachable on ::1 on some hosts) and prefer 127.0.0.1 over localhost. Run make lint && make test && go test -tags integration -count=1 ./internal/discover/... locally with the image removed first, and paste the output including the pull line.` },
  { id: 'T-0052', title: 'testutil retries the mapped port instead of failing on the first miss', model: 'sonnet', reviewers: 1, stage: 'foundations', paths: ['internal/testutil/'], integration: './internal/testutil/... ./internal/load/...',
    brief: `Read tracker/tasks/T-0052-*.md including its Log. internal/testutil.Postgres turns a transient PortEndpoint failure (mapped port 5432/tcp not found, seen in TestKillNineLeavesEveryTableEmptyOrComplete and TestI6RootHoldsTakeRows) into an immediate t.Fatalf. Retry PortEndpoint with a bounded backoff (about ten attempts over five seconds), then fail with a message that names the race. Also handle a stale testcontainers reaper: if container creation fails with a ryuk No such container error, retry once. Add a unit test with a fake that fails the first two calls.` },
  { id: 'T-0073', title: 'Fixture email values out of the masker output space', model: 'sonnet', reviewers: 1, stage: 'foundations', paths: ['testdata/', 'internal/classify/', 'internal/testutil/', 'internal/verify/', 'internal/invariants/CLAUDE.md'], integration: './internal/invariants/...',
    brief: `ARCHITECTURE.md section 5 records that the email masker emits addresses under example.com, example.net and example.org, so a source value in those domains can equal a masked value and I2's assertMaskedValuesAreNew fails intermittently (seen on public.people.alt_emails against uploaded_by, owned_by, ref, and tenant_users.email). Change every source email address in testdata/ (nasty.sql and any generated data) to a domain the masker never emits, such as fixture.test or corp.invalid, keeping row counts and NULL patterns and keeping the values valid for net/mail.ParseAddress. Update testdata/README.md, and any classify, verify, or testutil test that asserts the literal old addresses. Add one sentence to internal/invariants/CLAUDE.md pointing at the section 5 note. Run the invariants package three times (go test -tags integration -count=3 ./internal/invariants/...) and paste the result.` },
  { id: 'T-0046', title: 'Fixture: deferrable unique on a partitioned root, leaf-local key, edge referencing the leaf', model: 'sonnet', reviewers: 1, stage: 'foundations', paths: ['testdata/', 'internal/testutil/', 'internal/introspect/', 'internal/plan/'], integration: './internal/introspect/... ./internal/plan/...',
    brief: `Read tracker/tasks/T-0046-*.md. Add to testdata/nasty.sql a partitioned root carrying a DEFERRABLE unique constraint, a leaf partition carrying its own non-deferrable unique key the root cannot hold, and a child table whose foreign key references the leaf's key. Document the trap in testdata/README.md. Add integration assertions: introspect leaves that edge un-re-pointed with ForeignKey.NotRecreatable set, and the planner refuses at plan time with exit 13 and target.schema.not_recreatable naming the edge, before anything in a target is touched. Update any fixture count assertion.` },
  { id: 'T-0049', title: 'Mask module low findings and a registry test for rules.yml masker ids', model: 'sonnet', reviewers: 1, stage: 'mask', paths: ['mask/', 'internal/classify/', 'internal/transform/'], integration: false,
    brief: `Read tracker/tasks/T-0049-*.md and the Log section of tracker/tasks/T-0040-*.md. Fix each recorded low finding in mask/ with a targeted edit and a test: the unique branch must refuse when no generator fits regardless of an unknown row count; freeTextExact clamps to MaxLen; satAdd saturates; checkValues treats NOT IN and NOT (= ANY) as forbidden sets, not allowed sets; the network_id range test generates honest inputs including documentation-range values and counts distinct outputs. Move internal/transform/writeback_test.go's two RFC 5737 probe values to RFC 1918. Add a test in internal/classify that every masker id named in rules.yml resolves in the mask registry. Do not change generator behaviour beyond what a finding names.` },
  { id: 'T-0053', title: 'pg gate follow-ups: transaction pin, rollback discipline, schema-only introspection', model: 'opus', reviewers: 3, stage: 'pg', paths: ['internal/pg/', 'internal/introspect/', 'internal/pipeline/', 'internal/load/'], integration: './internal/pg/... ./internal/load/... ./internal/introspect/...',
    brief: `Read tracker/tasks/T-0053-*.md. (1) In internal/pg's own integration suite add a case whose injected fingerprinter issues SAVEPOINT through the reader it is handed and fails on 25P01, so the BEGIN around the fingerprinter is pinned where it lives. (2) Route a failed ROLLBACK in catalogFingerprint through the same discipline as source.go's endTx (close the connection) and correct the doc comment that claims the gate has rules left to run. (3) Add a schema-only introspection path (an option on the Introspector or a second method, whichever ARCHITECTURE.md section 2 tolerates with the smallest change; report the deviation) so the gate's fingerprint over the target does not sample rows or hold a REPEATABLE READ transaction longer than the catalog read; use it from load.GateFingerprint. Fix the stale comments T-FPR's reviewer listed.` },
  { id: 'T-0050', title: 'Extract and transform hand-offs: shape-template escaping, KeySet chunk iterator, pooler test, text-keyed big fixture', model: 'opus', reviewers: 3, stage: 'extract', paths: ['internal/extract/', 'internal/pg/', 'internal/pipeline/', 'internal/plan/', 'internal/verify/', 'internal/testutil/', 'testdata/'], integration: './internal/extract/... ./internal/plan/... ./internal/verify/... ./internal/pg/...',
    brief: `Read tracker/tasks/T-0050-*.md including its Log. (1) lookupShapeFor interpolates a quoted table name into a shape template, so a table named with a {token} widens or breaks the allowlist; give the tracer a way to register a shape with a pre-quoted literal segment, or escape placeholder-shaped text in identifiers, with a test using a table named with braces. (2) Add FirstChunk(n int) Chunk to pipeline.KeySet and both internal/plan implementations, and a chunk-at-a-time iterator so extract's peak memory is one chunk, not a full copy of the key set; make internal/verify/sample.go use FirstChunk and drop its fallback; record the section 2 change in the package CLAUDE.md files. (3) Add a pgbouncer testcontainer helper to internal/testutil and one integration test proving the pooler-safe startup parameter list and the pooled single-connection fallback. (4) Add a text-keyed or uuid-keyed large table to the nasty generator and a memory-bound extract test over it.` },
  { id: 'T-PIN', title: 'The run that writes the target is pinned to the snapshot and endpoints the operator reviewed', model: 'opus', reviewers: 3, stage: 'core', paths: ['docs/FLAGS.md', 'docs/ERRORS.md', 'internal/core/', 'internal/pipeline/', 'internal/event/catalogue.yml', 'cmd/lazyslice/', 'internal/tui/'], integration: true,
    brief: `From T-TUI's review. With --tui, cmd/lazyslice runs a preview core.Run (plan only) to fill the reasons and plan screens, then a second core.Run with the built request; nothing ties the two together, so the operator's review is of a different snapshot and a different discovery walk than the run that writes the target. Add to core.Request an optional Reviewed struct carrying the preview's pipeline.Schema.Fingerprint (ADR-009 definition) and the chosen source and target endpoints; when set, core compares after introspection and discovery and refuses with a new event code (core.refused.reviewed_changed, exit 12, naming what changed) before any write. cmd/lazyslice fills it from the preview; the plan lines printed by the preview are then not reprinted by the run. Tests in internal/core: identical snapshot passes; a schema change between passes refuses; a different resolved target refuses. Update the runTUI doc comment that records the limit. Also apply the lows recorded in the Log of tracker/tasks/T-0071-*.md (options-literal test asserts values, openTarget empty-target test, ArgReason redaction test against a PgError with Detail, the three dangling comment back-references).` },
  { id: 'T-0076', title: 'Source read-only setting scoped per transaction; no session GUC leaks through a transaction-pooling PgBouncer', model: 'opus', reviewers: 3, stage: 'pg', paths: ['internal/pg/', 'internal/testutil/', 'THREAT_MODEL.md'], integration: './internal/pg/...',
    brief: `Read tracker/tasks/T-0076-*.md and internal/pg/CLAUDE.md's paragraph on the measured leak. internal/pg's AfterConnect runs SET default_transaction_read_only = on on every source connection; through a transaction-pooling PgBouncer that session GUC stays on the shared server connection after lazyslice exits, so other applications on the pooler become read-only for up to server_lifetime. Every source transaction is already BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY, so the session default is defence in depth that harms neighbours. Drop the AfterConnect exec and the source.read_only statement shape; wrap the one statement issued outside a transaction (Source.SystemID) in a read-only transaction; keep the tracer allowlist as the enforcement. Add an integration test using the pgbouncer testcontainer from T-0050 proving that after a lazyslice source session ends, a second client on the same pooler can CREATE TABLE. THREAT_MODEL.md is in your paths for exactly one edit: reword T9's read-only bullet (added 2026-09-06) to say the setting is per transaction, never a session default, and why. Record the decision in internal/pg/CLAUDE.md.` },
  { id: 'T-0077', title: 'stream_docs lifted above the nasty.sql big gate; introspect table list updated', model: 'sonnet', reviewers: 1, stage: 'foundations', paths: ['testdata/', 'internal/introspect/', 'internal/testutil/', 'internal/extract/'], integration: './internal/introspect/... ./internal/extract/...',
    brief: `Read tracker/tasks/T-0077-*.md. testdata/nasty.sql defines public.stream_docs and public.fill_stream_docs inside the \\if :{?big} gate, so the fixture's schema differs by load flag (25 tables by default, 26 with big). Move the CREATE TABLE and CREATE FUNCTION above the gate so the schema is constant and only the fill stays gated; add public.stream_docs to the table list internal/introspect/introspect_integration_test.go asserts; remove the nastyTables hole and the assertNastyGateOff special case in internal/extract that worked around it; update testdata/README.md. Run the named integration packages with and without the big flag.` },
  { id: 'T-0081', title: 'Discover probe reads inside a read-only transaction; a check that no source statement runs outside one; stale read-only prose', model: 'opus', reviewers: 3, stage: 'pg', paths: ['internal/discover/', 'internal/pg/', 'internal/load/', 'internal/testutil/'], integration: './internal/discover/... ./internal/pg/...',
    brief: `Read tracker/tasks/T-0081-*.md, T-0082-*.md and T-0078-*.md (all filed by developers; T-0081 and T-0082 were re-homed to phase 5 because T-0076 removed a pool-wide rail in this phase). (1) internal/discover/probe.go issues sqlVersion, sqlTables and sqlMarker on a source-mode pool with no BEGIN; wrap them in the same BEGIN ... READ ONLY / ROLLBACK pair internal/pg uses, registering source.begin and source.rollback from pg.SourceShapes() beside dialShapes so the literals are not written twice. (2) T-0082: add the structural check that no statement reaches a source-mode pool outside a transaction: the cheapest honest form is a tracer-level assertion in internal/pg (a source connection whose TxStatus is idle when a non-BEGIN statement starts is a violation that fails the run), with a unit test and a test in internal/discover proving probe now passes it. (3) Rewrite the three stale comments that still describe default_transaction_read_only as present (probe.go, internal/discover/CLAUDE.md, internal/load/CLAUDE.md) and drop the dangling back-reference in internal/load/ddl/recreatable.go (T-0078). Run make lint && make test && go test -tags integration -count=1 ./internal/discover/... ./internal/pg/... and paste the output.` },
  { id: 'T-0055', title: 'Shared validators package with the name dictionary; person_name and free_text in the second net', model: 'opus', reviewers: 3, stage: 'verify', paths: ['internal/classify/', 'internal/verify/', 'internal/pipeline/', 'internal/textsig/'], integration: './internal/classify/... ./internal/verify/...',
    brief: `Read tracker/tasks/T-0055-*.md. Create a leaf package internal/textsig holding the value-only halves of the classifier's validators and the embedded name dictionary, imported by both internal/classify and internal/verify (check internal/CLAUDE.md's import-graph rule: a leaf under internal/ that imports only ref and pipeline is allowed; say so in its CLAUDE.md). Register person_name and free_text in verify's second net. Decide the verify-side false-positive threshold: a single dictionary word (black, brown, hill, green, wood) in a column must not fail a target; require the classifier's own multi-token name shape or a dictionary hit rate over the strong threshold across at least minValues distinct values, and name the rule in internal/verify/CLAUDE.md. Update THREAT_MODEL.md T1's gap list only by reporting it; the orchestrator edits that file.` },
]

if (step === 'backlog') {
  phase('Backlog')
  const results = []
  for (const t of BACKLOG.slice(from)) {
    const r = await workflow({ scriptPath: IMPL }, { ...t, effort: t.model === 'opus' ? 'high' : 'medium' })
    results.push(r)
    if (!r || r.status !== 'merged') { log(`Stopped at ${t.id}`); return { results, stopped_at: t.id } }
  }
  return { results }
}

if (step === 'harden') {
  phase('Harden')
  const results = []
  for (const t of TASKS.slice(from)) {
    const r = await workflow({ scriptPath: IMPL }, { ...t, model: t.model || 'sonnet', effort: t.effort || (t.model === 'opus' ? 'high' : 'medium') })
    results.push(r)
    if (!r || r.status !== 'merged') { log(`Stopped at ${t.id}`); return { results, stopped_at: t.id } }
  }
  return { results }
}

phase('Red team')
const ATTACK = { type: 'object', required: ['attempts'], properties: { attempts: { type: 'array', items: { type: 'object', required: ['attack', 'reproduction', 'leaked', 'fix'], properties: { attack: { type: 'string' }, reproduction: { type: 'string' }, leaked: { type: 'boolean' }, documented_residual: { type: 'boolean', description: 'true when the leak reproduces a residual THREAT_MODEL.md names as accepted' }, fix: { type: 'string' } } } } } }
const attackers = [
  'PII that dodges the classifier: column names in other languages or abbreviations, values that miss every regex (obfuscated emails, phone numbers with spaces and words, names in a column called label), personal data inside arrays and JSON three levels deep, and inside a column the classifier marked as safe. Build a schema for each, run the tool, and check the target.',
  'Wrong target: make the tool write to production by aliasing the host, using a different port on the same database, a read replica, a connection string with the same database name on a different host, or a target URL taken from a compose file that points at prod. Also try to get it to hold write privileges on the source, and try to defeat the run lease and the per-table lock-and-recheck (T-0130) with a second run or a concurrent writer.',
  'Secrets and residue: get a password, secret, or unmasked row into lazyslice.yml, logs at any verbosity, --json, the emitted error messages, a crash dump, a temp file, the target catalog (defaults, CHECK constraints, comments, index predicates), or a snapshot written into a git-tracked or cloud-synced folder. Also try a custom masker that throws halfway and one that returns its input.',
  'The 2026-09-09 review, replayed: run docs/reviews/2026-09-09/evidence/probes.py and target_race.py (read them first; they build the binary with go build and use a disposable postgres container) against the current tree, one case at a time, and report each of the seven cases as an attempt: whether the fixed behaviour matches what tracker tasks T-0130 to T-0137 claim (target race refused at exit 4; no source value in any output; FK pair masked alike; a verify failure leaves an empty target and a failed marker; a masked default is masked in pg_attrdef; sslmode round-trips; one sparse email is caught; an email-shaped JSON key is masked). Then vary each probe once (a different type, a second column, a second row) and report that too.',
]
const REPLAY = (file, variants) => `This is a replay round. Read docs/reviews/2026-09-15-redteam/${file} first: it holds the attempts that still leaked after the previous fix round, each with its reproduction. Re-run every attempt on that list that belongs to your surface against the current tree (rebuild the binary first), report each as an attempt with leaked true or false, ${variants ? 'and for each one that now holds, try exactly one new variant of it and report that too.' : 'Do not try new variants: this round confirms fixes, so replay each listed attempt exactly as recorded and nothing else.'} Do not repeat attempts that already held. If an attempt still leaks but reproduces a residual THREAT_MODEL.md names as accepted (say which sentence), set documented_residual true on it; a leak the threat model does not name is documented_residual false.`
const attack = (round, replayFile, only, variants = true) => parallel(attackers.map((a, i) => () => (only && !only.includes(i)) ? null : agent(`You are a red-team engineer trying to make lazyslice leak production data. Repo: ${REPO}. Read THREAT_MODEL.md, ARCHITECTURE.md, and the code. Build the binary. Use the testutil containers. Your attack surface: ${a} ${replayFile ? REPLAY(replayFile, variants) : ''} For each attempt give the exact reproduction commands, whether anything leaked or the tool misbehaved, and the fix. Do not change any repo file; put scratch schemas under /private/tmp/claude-501/lazyslice-scratch/redteam-${i}/ and remove every container you started before you return (docker rm -f). Report every attempt, including the ones that failed to leak.`,
  { label: `attack:${i + 1}:r${round}`, phase: 'Red team', model: i === 3 ? 'sonnet' : 'opus', effort: 'medium', schema: ATTACK })))

const REDFIX = [
  { id: 'T-0187', title: 'National-identifier validators with checksums; strong in classify and the second net; digits-family SSN under the ratio rule', model: 'sonnet', effort: 'high', reviewers: 1, stage: 'classify', paths: ['internal/textsig/', 'internal/classify/', 'internal/verify/', 'internal/pipeline/', 'testdata/', 'internal/invariants/', 'docs/TORTURE.md', 'docs/ERRORS.md', 'internal/event/catalogue.yml'], integration: './internal/classify/... ./internal/verify/...',
    brief: `Read tracker/tasks/T-0187-*.md and the four attempts it names in docs/reviews/2026-09-15-redteam/round2-still-leaking.json (R2-01 to R2-04, the A2, A6, A7 and A9b entries). Implement every validator the task lists with its real check rule and positive and negative vectors (never real people's numbers: construct them); wire national_id as a strong text validator in classify and the second net and as a digits validator under the ratio rule on numeric families; add the three regression fixtures; run make torture and record any schema that now needs a flag in docs/TORTURE.md with the reason and the re-measured flags-by-kind. Run make check && make torture and the named integration packages, and paste the output.` },
  { id: 'T-0188', title: 'Multilingual given-name and surname lists in textsig under CC0', model: 'sonnet', reviewers: 1, stage: 'classify', paths: ['internal/textsig/', 'internal/classify/', 'testdata/', 'internal/invariants/', 'docs/TORTURE.md', 'THIRD_PARTY_NOTICES.md'], integration: './internal/classify/...',
    brief: `Read tracker/tasks/T-0188-*.md and R2-05 in docs/reviews/2026-09-15-redteam/round2-still-leaking.json. Source the lists from CC0 or public-domain material only (Wikidata SPARQL over given-name and family-name items with a language or country qualifier is CC0; a national statistics office open list is acceptable if its licence is stated), a few thousand per language, and record every source, query or URL and licence in THIRD_PARTY_NOTICES.md. Do not add a Go module. Keep the file format textsig already reads, or extend it minimally and say so. Measure the confusion-matrix fixture and the three torture truth sets before and after, record precision and recall changes in docs/TORTURE.md, and add a regression fixture with the round-2 names. Run make check && make torture and the named integration package, and paste the output.` },
  { id: 'T-0189', title: 'Catalog literals under every validator; pattern operands detected not rewritten; plan reads partial-index predicates', model: 'sonnet', effort: 'high', reviewers: 1, stage: 'plan', paths: ['internal/plan/', 'internal/verify/', 'internal/pipeline/', 'internal/load/', 'internal/introspect/', 'testdata/', 'internal/invariants/', 'docs/ERRORS.md', 'internal/event/catalogue.yml', 'ARCHITECTURE.md', 'THREAT_MODEL.md'], integration: './internal/plan/... ./internal/verify/... ./internal/load/...',
    brief: `Read tracker/tasks/T-0189-*.md, T-0163-*.md and R2-07 to R2-10 in docs/reviews/2026-09-15-redteam/round2-still-leaking.json. Implement the three rules the task states, with a regression fixture for each of the four attempts, and write the dated amendments to ARCHITECTURE.md 11.1 and THREAT_MODEL.md T1 yourself, replacing the sentence that limits the catalog passes to the five strong validators. Run make check && make torture and the named integration packages, and paste the output.` },
  { id: 'T-0190', title: 'Cluster identity does not depend on the transport', model: 'opus', effort: 'medium', reviewers: 1, stage: 'pg', paths: ['internal/pg/', 'internal/core/', 'internal/testutil/', 'testdata/', 'ARCHITECTURE.md', 'THREAT_MODEL.md'], integration: './internal/pg/... ./internal/core/...',
    brief: `Read tracker/tasks/T-0190-*.md and R2-06 in docs/reviews/2026-09-15-redteam/round2-still-leaking.json. Replace sqlClusterID's transport-dependent inputs as the task says, keep the read-only role in mind (no pg_control_system EXECUTE), write the dated amendments to ARCHITECTURE.md section 9 and THREAT_MODEL.md T2 yourself, and add the two-published-ports integration test (internal/testutil can publish a second port on the same container, or run a TCP proxy in the test). Run make check and the named integration packages, and paste the output.` },
  { id: 'T-0191', title: 'mask.Apply post-condition and recover; masker error messages never carry the value', model: 'opus', effort: 'medium', reviewers: 1, stage: 'mask', paths: ['mask/', 'internal/transform/', 'internal/core/', 'THREAT_MODEL.md', 'testdata/'], integration: './internal/transform/...',
    brief: `Read tracker/tasks/T-0191-*.md, T-0180-*.md, T-0181-*.md and R2-11 to R2-13 in docs/reviews/2026-09-15-redteam/round2-still-leaking.json, then mask/CLAUDE.md for the two paths allowed to return a member label. Implement the post-condition, the recover and the transform refusal change as the task states; mask/ is its own module so run its tests there too (make check covers both modules). Update THREAT_MODEL.md T7 and T12 from owed to landed. Run make check and the named integration package, and paste the output.` },
  { id: 'T-0192', title: 'Secret file protected on its resolved path; hard links refuse; password_command screened', model: 'sonnet', reviewers: 1, stage: 'core', paths: ['internal/core/', 'internal/repo/', 'internal/emit/', 'THREAT_MODEL.md', 'testdata/', 'docs/ERRORS.md', 'internal/event/catalogue.yml'], integration: './internal/core/...',
    brief: `Read tracker/tasks/T-0192-*.md and R2-14 to R2-16 in docs/reviews/2026-09-15-redteam/round2-still-leaking.json. Implement the three checks the task states with a unit test each (a symlinked parent directory, a hard link, an echo-style password_command), write the THREAT_MODEL.md T5 and T6 amendments yourself. Run make check and the named integration package, and paste the output.` },
  { id: 'T-0184', title: 'A headless run never auto-selects a target on the source cluster; ADR-013', model: 'sonnet', reviewers: 1, stage: 'discover', paths: ['internal/discover/', 'internal/core/', 'cmd/lazyslice/', 'docs/FLAGS.md', 'docs/ERRORS.md', 'internal/event/catalogue.yml', 'docs/adr/', 'ARCHITECTURE.md', 'testdata/'], integration: './internal/discover/... ./internal/core/...',
    brief: `Read tracker/tasks/T-0184-*.md. Decision (orchestrator, 2026-09-15): a run with --yes and no --target refuses, exit 4, when every reachable candidate is on the source's own cluster, naming --target as the escape; an interactive run asks as today; a target named explicitly on the source cluster stays eligible as ADR-008 section 5 says. Write docs/adr/013-headless-target-never-on-the-source-cluster.md (status proposed) recording this as a narrowing of ADR-008 for headless runs, not a reversal; amend ARCHITECTURE.md section 9 rule 1 in place; a catalogue row and an integration test that reproduces the red team's run (--source at a container, no --target, --yes) and is refused. Run make check and the named integration packages, and paste the output.` },
  { id: 'T-0178', title: 'The rung-4 test no longer binds a fixed host port', model: 'sonnet', effort: 'low', reviewers: 1, stage: 'discover', paths: ['internal/discover/', 'internal/testutil/'], integration: './internal/discover/...',
    brief: `Read tracker/tasks/T-0178-*.md. TestAStoppedContainerIsOfferedAndStarted binds 127.0.0.1:5433 and has failed twice in full make integration runs on this machine with port is already allocated. Pick a free loopback port per run (bind :0 and read it back, or a testcontainers-mapped port), keep the rung-4 semantics unchanged, and run the discover integration package three times in a row to show it is stable. Run make check and paste the output.` },
  { id: 'T-0186', title: '--allow-type-literal round-trips through lazyslice.yml as a reasoned opt-out', model: 'sonnet', reviewers: 1, stage: 'emit', paths: ['internal/emit/', 'internal/pipeline/', 'internal/core/', 'cmd/lazyslice/', 'docs/FLAGS.md', 'ARCHITECTURE.md', 'testdata/'], integration: './internal/emit/... ./internal/core/...',
    brief: `Read tracker/tasks/T-0186-*.md and T-0185-*.md. Decision: --allow-type-literal TYPE=REASON is recorded in the yml under a types: block exactly as --unmask is recorded for columns (reason required, expires when the type's labels or definition change), which is the same loosening ADR-004 already allows for --unmask; core reads it as a prior. Close T-0185 in the same change: ARCHITECTURE.md section 8's flag table and section 11.1's escape sentence name --allow-type-literal. Run make check and the named integration packages, and paste the output.` },
  { id: 'T-0213', title: '--password-command runs, and its output never reaches a sink', model: 'sonnet', reviewers: 1, stage: 'discover', paths: ['internal/discover/', 'internal/dsn/', 'internal/core/', 'cmd/lazyslice/', 'internal/event/catalogue.yml', 'docs/FLAGS.md', 'docs/ERRORS.md', 'THREAT_MODEL.md'], integration: './internal/discover/...',
    brief: `Read tracker/tasks/T-0213-*.md and R2-16 in docs/reviews/2026-09-15-redteam/round2-still-leaking.json. --password-command is accepted, printed in --help and the remedy text, and recorded in lazyslice.yml, but nothing ever runs it, so a run that relies on it fails authentication. Decision (orchestrator, 2026-09-16): implement it, do not refuse it. When the flag is set and no earlier password source resolved for an endpoint (keep the existing precedence: a password in the DSN, PGPASSWORD, ~/.pgpass, then the command), run the command through the shell (/bin/sh -c on unix, cmd /C on windows) with stdin closed and a 30 second timeout, pass its stderr through to the operator's stderr untouched, take its stdout with exactly one trailing newline trimmed as the password, and never let that stdout reach an event, a log line, a refusal message, lazyslice.yml or the trace. A non-zero exit, a timeout or empty stdout refuses with a catalogue row naming the exit status and nothing else (make docs regenerates docs/ERRORS.md). A unit test runs a script that prints a value and proves the endpoint authenticates with it; a second test proves the value appears in no sink cmd/lazyslice writes (the existing canary error-egress test shows the pattern). Update THREAT_MODEL.md T5's amendment that records the gap. Run make check and the named integration package and paste the output.` },
  { id: 'T-0221', title: 'Phone numbers in national format and spelled out in words are recognised; --phone-region', model: 'sonnet', effort: 'high', reviewers: 1, stage: 'classify', paths: ['internal/textsig/', 'internal/classify/', 'internal/verify/', 'internal/pipeline/', 'internal/core/', 'internal/emit/', 'cmd/lazyslice/', 'docs/FLAGS.md', 'docs/ERRORS.md', 'internal/event/catalogue.yml', 'testdata/', 'internal/invariants/', 'docs/TORTURE.md', 'THREAT_MODEL.md', 'ARCHITECTURE.md'], integration: './internal/classify/... ./internal/verify/...',
    brief: `Read tracker/tasks/T-0221-*.md, then the A2 attempts and the kontaktnr variant in docs/reviews/2026-09-15-redteam/round3-still-leaking.json. The decision in the task is final: --phone-region REGION and yml phone_region, shown in the reasons output; the row path parses under the configured region, and with none configured under a short built-in list only with corroboration (phone name rule, or a proven personal neighbour, the T-0187 pattern); verify's second net stays strong on +E.164 and the configured region only. spelledDigits output takes the same path. Three regressions: the plain national number in a column called kontaktnr, the dictated number, and a ten-digit account column that must load and verify. Run make torture and record any schema that changes in docs/TORTURE.md. Write the THREAT_MODEL.md T1 amendment yourself. Run make check && make torture and the named integration packages, and paste the output.` },
  { id: 'T-0222', title: 'Cluster identity degrades field by field; two unknown identities may be the same cluster', model: 'sonnet', effort: 'high', reviewers: 1, stage: 'pg', paths: ['internal/pg/', 'internal/core/', 'internal/discover/', 'ARCHITECTURE.md', 'THREAT_MODEL.md', 'testdata/'], integration: './internal/pg/... ./internal/core/...',
    brief: `Read tracker/tasks/T-0222-*.md and the R2-06 replay in docs/reviews/2026-09-15-redteam/round3-still-leaking.json. Guard every field of the identity statement with has_function_privilege so an unreadable field is empty and the rest still compare; when both identities are unknown the gate says the target may be on the source's own cluster, warns, and the headless refusal of ADR-013 treats it as same-cluster. Extend cluster_test.go's inputs, add an integration test with a source role that lacks EXECUTE on pg_postmaster_start_time, and write the ARCHITECTURE.md section 9 and THREAT_MODEL.md T2 amendments yourself. Run make check and the named integration packages, and paste the output.` },
  { id: 'T-0223', title: 'mask.Apply wraps a masker error without the value', model: 'sonnet', reviewers: 1, stage: 'mask', paths: ['mask/', 'internal/transform/'], integration: './internal/transform/...',
    brief: `Read tracker/tasks/T-0223-*.md and the R2-13 replay in docs/reviews/2026-09-15-redteam/round3-still-leaking.json. In maskCell, wrap a masker's returned error the way the panic is wrapped: a sentinel naming the masker id, the category and the error's type, the original not kept. A test registers a masker whose error quotes its input and asserts the returned error does not contain it; mask/ is its own module, run its tests there (make check covers both). Update mask/CLAUDE.md. Run make check and the named integration package, and paste the output.` },
  { id: 'T-0198', title: 'A masked column carries no non-rewritable literal in its own constraints; special_category validator', model: 'sonnet', effort: 'high', reviewers: 1, stage: 'plan', paths: ['internal/plan/', 'internal/verify/', 'internal/textsig/', 'internal/pipeline/', 'internal/load/', 'testdata/', 'internal/invariants/', 'docs/TORTURE.md', 'docs/ERRORS.md', 'internal/event/catalogue.yml', 'ARCHITECTURE.md', 'THREAT_MODEL.md'], integration: './internal/plan/... ./internal/verify/...',
    brief: `Read tracker/tasks/T-0198-*.md (its last log entry is the decision) and the two special-category replays in docs/reviews/2026-09-15-redteam/round3-still-leaking.json. Rule: a column the run masks may not carry a non-rewritable literal in its own CHECK, DEFAULT or index predicate, whatever it parses as, unless the existing named opt-out names the column; the refusal message says 'masked column, unrewritable literal in its own constraint' and, when a special_category validator (health, religion, sexuality, ethnicity, union, politics vocabulary; a small list, precision over recall) hits, names the category. Both catalog passes apply it. Measure make torture before and after and record every schema the rule newly refuses in docs/TORTURE.md with the flag it now needs; if more than two of the ten are newly refused, land the rule behind the existing opt-out and say so in your concerns instead of weakening it. Regressions for the CHECK on a masked column and for the sentence in a CHECK on an unmasked column. Write the ARCHITECTURE.md 11.1 and THREAT_MODEL.md T1 amendments yourself. Run make check && make torture and the named integration packages, and paste the output.` },
  { id: 'T-0212', title: 'renderSafe redacts by default; a transform refusal prints its reason only under the values flag', model: 'sonnet', reviewers: 1, stage: 'cli', paths: ['cmd/lazyslice/', 'internal/core/', 'internal/transform/', 'THREAT_MODEL.md', 'docs/FLAGS.md', 'docs/ERRORS.md', 'internal/event/catalogue.yml'], integration: './cmd/lazyslice/...',
    brief: `Read tracker/tasks/T-0212-*.md and the R2-13 replay in docs/reviews/2026-09-15-redteam/round3-still-leaking.json. Invert renderSafe: every error prints its type and a value-free summary by default, and only an allowlist of types known to carry no value prints its message; a transform refusal's reason prints under --show-row-values-in-errors and nowhere else. Extend the canary error-egress test so an unknown error type that quotes a canary never reaches any sink. Run make check and the named integration package, and paste the output.` },
  { id: 'T-0238', title: 'mask.Apply rebuilds a masker error with only its identity carried across', model: 'sonnet', reviewers: 1, stage: 'mask', paths: ['mask/', 'internal/transform/'], integration: './internal/transform/...',
    brief: `Read tracker/tasks/T-0238-*.md and the T-0223 variant in docs/reviews/2026-09-15-redteam/round4-still-leaking.json. Never return a foreign error object from maskCell: %w on the matched module sentinel (ErrMaskerFailed when none), category, masker id and the error's type, with a module-built NoRoomError or DomainError rebuilt from value-free fields, so errors.Is and errors.As still answer and no foreign text survives. Test with a masker that wraps ErrNoRoom around a canary. mask/ is its own module; run its tests there. Update mask/CLAUDE.md. Run make check and the named integration package, and paste the output.` },
  { id: 'T-0239', title: 'The certain-neighbour rail masks or refuses a short unrecognised column instead of skipping it', model: 'sonnet', effort: 'high', reviewers: 1, stage: 'classify', paths: ['internal/classify/', 'internal/pipeline/', 'testdata/', 'internal/invariants/', 'docs/TORTURE.md', 'docs/ERRORS.md', 'internal/event/catalogue.yml', 'THREAT_MODEL.md'], integration: './internal/classify/...',
    brief: `Read tracker/tasks/T-0239-*.md and the native-script varchar(12) variant in docs/reviews/2026-09-15-redteam/round4-still-leaking.json. Keep the two-letter-code exclusion; a column between that floor and sixteen characters beside a certain personal column is masked under a generator that fits its declared length or refused at exit 12 naming the column and --unmask; never copied. Regression fixture with a varchar(12) column beside a certain email column. Run make torture and record any schema that moves in docs/TORTURE.md. Write the THREAT_MODEL.md T1 A2b amendment yourself. Run make check && make torture and the named integration package, and paste the output.` },
  { id: 'T-0240', title: 'National-identifier corroboration counts a masked neighbour at any confidence and outranks the dense-sequence exemption', model: 'sonnet', effort: 'high', reviewers: 1, stage: 'verify', paths: ['internal/classify/', 'internal/verify/', 'internal/textsig/', 'internal/pipeline/', 'testdata/', 'internal/invariants/', 'docs/TORTURE.md', 'THREAT_MODEL.md'], integration: './internal/classify/... ./internal/verify/...',
    brief: `Read tracker/tasks/T-0240-*.md and the three A9b attempts in docs/reviews/2026-09-15-redteam/round4-still-leaking.json. A masked person-identifying neighbour at possible or above corroborates; the dense-sequence exemption applies only when nothing corroborates; the character family takes the same validator path as the digits family. Two regression fixtures as the task says; regression 026's account-number control must keep passing. Run make torture. Write the THREAT_MODEL.md T1 amendment to the T-0187 paragraph yourself. Run make check && make torture and the named integration packages, and paste the output.` },
  { id: 'T-0241', title: 'A standby source with the target on its primary is refused; a standby is announced; headless refuses on a standby', model: 'sonnet', effort: 'high', reviewers: 1, stage: 'pg', paths: ['internal/pg/', 'internal/core/', 'internal/discover/', 'internal/testutil/', 'testdata/', 'ARCHITECTURE.md', 'THREAT_MODEL.md', 'docs/adr/', 'docs/ERRORS.md', 'internal/event/catalogue.yml'], integration: './internal/pg/... ./internal/core/... ./internal/discover/...',
    brief: `Read tracker/tasks/T-0241-*.md and the two read-replica attempts in docs/reviews/2026-09-15-redteam/round4-still-leaking.json. Three changes as the task states: the start-time disagreement without system_identifier is unknown; pg_is_in_recovery() is read on the source, a standby is announced with its sender where readable, and a headless run with no --target refuses on a standby naming --target; the recommended-role snippet and the CodeRoleWritable message gain the pg_control_system grant. A primary-and-standby integration test if internal/testutil can stand a streaming standby up with pg_basebackup in a second container; if not, pin the verdict in cluster_test.go and record the gap in THREAT_MODEL.md T2. Write the ARCHITECTURE.md 9, THREAT_MODEL.md T2 and ADR-013 amendments yourself. Run make check and the named integration packages, and paste the output.` },
  { id: 'T-0242', title: 'The whole target is re-checked for emptiness under the lease before the first drop', model: 'sonnet', reviewers: 1, stage: 'load', paths: ['internal/load/', 'internal/pg/', 'internal/core/', 'testdata/', 'docs/ERRORS.md', 'internal/event/catalogue.yml', 'THREAT_MODEL.md'], integration: './internal/load/... ./internal/core/...',
    brief: `Read tracker/tasks/T-0242-*.md and the lock-and-recheck attempt in docs/reviews/2026-09-15-redteam/round4-still-leaking.json. Under the lease already held, before the first drop, re-run the gate's emptiness probe over the target's current user tables and refuse with load.refused.target_changed naming the tables that appeared; an integration test creates a table between gate and load. Correct THREAT_MODEL.md T2's residual bullet yourself. make docs regenerates docs/ERRORS.md. Run make check and the named integration packages, and paste the output.` },
  { id: 'T-0197', title: 'A sampled column with no hit reports absence of evidence, not a clean bill of health', model: 'sonnet', effort: 'low', reviewers: 1, stage: 'classify', paths: ['internal/classify/', 'internal/render/', 'internal/tui/', 'testdata/', 'docs/TORTURE.md'], integration: './internal/classify/...',
    brief: `Read tracker/tasks/T-0197-*.md; its last log entry narrows it to the reason string only. A sampled character column that matched nothing renders as nothing recognised in N samples, not proof the column is impersonal; no name or value signal stays for columns nothing could look inside. Update the fixtures that assert the old string. Run make check and the named integration package, and paste the output.` },
  { id: 'T-0251', title: 'The secret file is written only when git confirms it is ignored', model: 'sonnet', reviewers: 1, stage: 'core', paths: ['internal/repo/', 'internal/core/', 'THREAT_MODEL.md', 'docs/ERRORS.md', 'internal/event/catalogue.yml', 'testdata/'], integration: './internal/core/...',
    brief: `Read tracker/tasks/T-0251-*.md and the .gitignore negation attempt in docs/reviews/2026-09-15-redteam/round5-still-leaking.json. After appending the entry, ask git check-ignore -v --no-index as the task states; only exit 0 with a rule not beginning with ! sets the writable state; not ignored, no repository and no git on PATH all fall back to the ephemeral key and to exit 5 under --require-key. A repo test with the entry followed by its negation asserts MayWriteSecret is false; a test with git absent from PATH asserts the fallback. Write the THREAT_MODEL.md T6 amendment yourself. Run make check and the named integration package, and paste the output.` },
  { id: 'T-0252', title: 'The run lease is re-asserted before every drop; a lost lease refuses the load', model: 'sonnet', effort: 'high', reviewers: 1, stage: 'load', paths: ['internal/pg/', 'internal/load/', 'internal/core/', 'testdata/', 'docs/ERRORS.md', 'internal/event/catalogue.yml', 'THREAT_MODEL.md'], integration: './internal/pg/... ./internal/load/... ./internal/core/...',
    brief: `Read tracker/tasks/T-0252-*.md and the lease attempt in docs/reviews/2026-09-15-redteam/round5-still-leaking.json. Export Lease.Alive as the task states, call it in the loader before the whole-target recheck and before each dropOne, refuse with load.refused.lease_lost, and give the raw 23505 a code. An integration test terminates the lease backend with pg_terminate_backend between gate and load and asserts the refusal, and a second run started after the kill asserts the first run's refusal rather than two loaders. make docs regenerates docs/ERRORS.md. Write the THREAT_MODEL.md T2 amendment yourself. Run make check and the named integration packages, and paste the output.` },
  { id: 'T-0253', title: 'The certain-neighbour rail raises both ends of a validated foreign key, or refuses the pair', model: 'sonnet', effort: 'high', reviewers: 1, stage: 'classify', paths: ['internal/classify/', 'internal/pipeline/', 'testdata/', 'internal/invariants/', 'docs/TORTURE.md', 'docs/ERRORS.md', 'internal/event/catalogue.yml', 'THREAT_MODEL.md'], integration: './internal/classify/...',
    brief: `Read tracker/tasks/T-0253-*.md and the FK-child variant in docs/reviews/2026-09-15-redteam/round5-still-leaking.json. Raise both ends of a validated FK together under one category; refuse the pair at exit 12 with --unmask when the partner is excluded for another reason; never copy the pair. Regression fixture for the native-script FK child beside a certain email column with a parent that has none; regression 031 keeps pinning the safe direction. Run make torture and record any schema that moves in docs/TORTURE.md. Correct the exclusion's comment and THREAT_MODEL.md's 2026-09-17 amendment yourself. Run make check && make torture and the named integration package, and paste the output.` },
  { id: 'T-0254', title: 'Special-category terms match through underscores and camel case; a stripped LIKE metacharacter leaves a separator', model: 'sonnet', reviewers: 1, stage: 'plan', paths: ['internal/textsig/', 'internal/pipeline/', 'internal/plan/', 'internal/verify/', 'testdata/'], integration: './internal/plan/...',
    brief: `Read tracker/tasks/T-0254-*.md and the HIV_POSITIVE attempt in docs/reviews/2026-09-15-redteam/round5-still-leaking.json. Normalise the candidate before matching as the task states, and make StripPatternMeta leave a separator for a removed _ instead of gluing the tokens. Add the three canaries to the vocabulary test and a plan-level case asserting exit 13 for the CHECK. Run make check and the named integration package, and paste the output.` },
  { id: 'T-0255', title: 'A standby data directory is not evidence of a different cluster; the sender address is compared with the target', model: 'sonnet', reviewers: 1, stage: 'pg', paths: ['internal/pg/', 'internal/core/', 'ARCHITECTURE.md', 'THREAT_MODEL.md', 'testdata/'], integration: './internal/pg/... ./internal/core/...',
    brief: `Read tracker/tasks/T-0255-*.md and the standby data_directory variant in docs/reviews/2026-09-15-redteam/round5-still-leaking.json. When the source is a standby, data_directory joins the start time among the fields that cannot prove difference; when the WAL receiver's sender host and port resolve to the target's server, SameCluster is true outright. Extend cluster_test.go's standby case as the task states. Write the ARCHITECTURE.md 9 and THREAT_MODEL.md T2 amendments yourself. Run make check and the named integration packages, and paste the output.` },
  { id: 'T-0263', title: 'testutil outlasts the Docker port-table race', model: 'sonnet', effort: 'low', reviewers: 1, stage: 'foundations', paths: ['internal/testutil/', 'testdata/'], integration: './internal/testutil/...',
    brief: `Read tracker/tasks/T-0263-*.md and the helper in internal/testutil that resolves a container's mapped port (the message names T-0052). Wait with a bounded backoff for up to 120 seconds, then terminate and recreate the container once before failing; the message keeps naming T-0052 and says how long it waited and that it restarted. No product code. testdata/ is in your paths only so the verify step runs make torture; do not change anything under it. Run make check, the named integration package, and make torture three times in a row, and paste the five top-level PASS lines with their times from each run.` },
  { id: 'T-0258', title: 'The foreign-key pair refusal skips a pair a later pass already reconciled', model: 'sonnet', reviewers: 1, stage: 'plan', paths: ['internal/plan/', 'internal/classify/', 'internal/invariants/', 'testdata/', 'docs/TORTURE.md', 'THREAT_MODEL.md'], integration: './internal/plan/...',
    brief: `Read tracker/tasks/T-0258-*.md (its last log entry is the decision) and docs/TORTURE.md's T-0257 section. Narrow the plan-time pair refusal to skip a pair whose two ends are already masked under the same final category, keep it for a type conflict and a measured two-letter code lookup, drop Metabase's second --unmask so the torture count returns to 27 (internal/invariants counts and docs/TORTURE.md), and tell the orchestrator in concerns that ROADMAP.md's twenty-eight note must go back to twenty-seven. A plan-level test for the reconciled pair. Run make check && make torture and the named integration package, and paste the output.` },
  { id: 'T-0259', title: 'README flag table generated and checked; a tag refuses a README that does not name it', model: 'sonnet', reviewers: 1, stage: 'foundations', paths: ['tools/docgen/', 'Makefile', 'README.md', '.github/workflows/', 'CONTRIBUTING.md', 'docs/'], checks: 'check',
    brief: `Read tracker/tasks/T-0259-*.md. tools/docgen writes the first-run flag table between two HTML comment markers in README.md from the command tree, make docs regenerates it, make docs-check fails when it differs, and the release workflow refuses a tag whose README Status section does not name that version. Do not rewrite the rest of README.md: T-0260 does that next and writes around your markers. Run make check and paste the output, then show make docs-check failing on a hand-edited table and passing after make docs.` },
  { id: 'T-0260', title: 'README is true for v0.1.0; SECURITY.md reconciled with the threat model', model: 'sonnet', effort: 'high', reviewers: 1, stage: 'peripheral', paths: ['README.md', 'SECURITY.md', 'docs/'], checks: 'check',
    brief: `Read tracker/tasks/T-0260-*.md, then README.md, SECURITY.md, CONCEPT.md, THREAT_MODEL.md's residual sentences, docs/FLAGS.md, docs/ERRORS.md and docs/reviews/2026-09-15-redteam/round5.json's documented residuals. Build the binary and run the quickstart you write against a disposable postgres container pair with invented data (remove the containers after), and paste the trimmed transcript into the README: no command or flag appears that you did not run or check against --help. Keep T-0259's generated table markers intact. Plain words, short sentences, no marketing; say what it refuses to do as clearly as what it does. Reconcile SECURITY.md's stated false negatives with the residual list in the task. Run make check and paste the output.` },
]
// The last gate-5 item: what ARCHITECTURE.md section 14 and the accepted ADRs promise for v1 and the 2026-09-17 audit found missing. No replay follows; the red-team item is already ticked.
const GATE = [
  { id: 'T-0270', title: "T4's egress test: only the source and the target are reachable, and a packet counter proves nothing else was tried", model: 'sonnet', effort: 'high', reviewers: 1, stage: 'foundations', paths: ['tools/egress/', 'Makefile', '.github/workflows/ci.yml', 'THREAT_MODEL.md', 'CONTRIBUTING.md'], checks: 'check',
    brief: `Read tracker/tasks/T-0270-*.md, THREAT_MODEL.md's T4 section (its last control bullet and its 'Blocks v1' line) and ARCHITECTURE.md section 14. Build make egress and a blocking CI job named egress in .github/workflows/ci.yml (ubuntu, on pull_request and on push to main, like the integration job). The test is a script under tools/egress/ (POSIX sh or bash; no new Go module): it cross-builds lazyslice for linux on the host architecture (CGO_ENABLED=0), creates a Docker network, starts a source and a target postgres:16 on it, loads a small schema with invented personal data (a customers table with email, full_name and phone, and an orders child; nothing real), and runs the binary inside a third container that holds NET_ADMIN and has iptables (build a three-line image from alpine with apk add --no-cache iptables, at test time, before the rules go in). Inside that container, before lazyslice runs: OUTPUT accepts loopback, ESTABLISHED/RELATED and the two database IP addresses on 5432, and a final rule counts and REJECTs everything else; the DSNs use IP addresses so no DNS lookup is legitimate. Assert: lazyslice exits 0 with --yes --no-config --root customers and LAZYSLICE_SECRET set; the target holds the rows and the email column holds no source value; the final rule's packet counter (iptables -L OUTPUT -v -n -x) reads 0. Negative control in the same script, after the real run: one deliberate connection attempt to a third address from the same container makes the counter non-zero, and the script fails if it stays 0, so a rule set that counts nothing cannot pass. Clean up containers, network and image on every exit path (trap), name everything with a unique suffix, never touch a container the script did not create, and print what failed. Run it yourself on this machine (Docker Desktop on macOS supports NET_ADMIN inside a container) and paste the output; if it cannot run here, say exactly why and prove the script in pieces. Then move THREAT_MODEL.md T4 from the future tense to naming make egress and the CI job, and change 'The network-namespace test is phase 5.' to say it shipped and where; say in one sentence what the test does not prove (a Docker socket connection is a unix socket and is not counted; a subprocess is covered by the allowlist tests in internal/repo and internal/discover). CONTRIBUTING.md gets the one line that names the target. Run make check and make egress and paste both.` },
  { id: 'T-0271', title: "Q2: the root-table question is asked at a terminal when nothing names the root", model: 'sonnet', effort: 'high', reviewers: 1, stage: 'core', paths: ['internal/core/', 'internal/discover/', 'internal/plan/', 'internal/pipeline/', 'internal/event/catalogue.yml', 'internal/render/', 'cmd/lazyslice/', 'internal/tui/CLAUDE.md', 'ARCHITECTURE.md', 'docs/QUICKSTART_TRANSCRIPT.md'], integration: './internal/core/... ./cmd/lazyslice/...',
    brief: `Read tracker/tasks/T-0271-*.md, then docs/adr/008-first-run.md in full (the one-question rule, the question table's Q2 row, section 7 on the controlling terminal, and its test list), ARCHITECTURE.md sections 3.1 and 9, internal/discover/ask.go (the Prompter seam and openPrompter), internal/core/run.go where discover.Options.Prompter is set, and internal/plan/root.go (rootScore and defaultRoot). ADR-008 is accepted and frozen: build what it says, do not edit it. Q2 is asked by internal/core after introspect and before plan, only when all of these hold: no --root flag and no root in a committed lazyslice.yml; the run is not headless by discover's own definition (--yes, or no controlling terminal); discovery did not already ask Q1 or Q1' in this run (discover must report that it asked, on its result, as an identifier-free boolean); and the mode is one that goes on to plan. The prompt is ADR-008's: 'root table? [<top-scoring table>]' on stderr, read from the controlling terminal, never from stdin. Enter takes the default; a table name (schema-qualified or bare when unambiguous) takes that table, and a name that matches no table re-asks once with the reason and then takes no more than ADR-008 allows (decide from the ADR; if it is silent, re-ask until a valid answer or EOF, and EOF takes the default); '?' prints the ranked top five with their score components through the line printer and re-asks. The ranking comes from internal/plan's own scoring, exported through one function so the question and chooseRoot cannot disagree; the planner still validates the answer exactly as it validates --root. Whatever happens, the chosen root is printed as a decision with --root beside it, as today. Extend the Prompter interface with the one method this needs rather than adding a second terminal path, keep core's test-only prompter seam working, and write tests for: the default on Enter, a named table, '?', an unknown name, no terminal (takes the default and asks nothing: ADR-008's TestNoControllingTerminalBehavesAsYes), --yes, --root given, a yml root, and Q1 already asked. Any new event code goes through internal/event/catalogue.yml and make docs. internal/tui/CLAUDE.md's stale sentence that 'the question ladder has no prompt implementation in the tree yet' is corrected: say what '?' does at Q2 and that --tui remains the only way into the two screens, because both need a plan and Q2 is asked before one exists; report that tension with ADR-002's 'or by pressing ? at a prompt' in concerns for the orchestrator rather than resolving it. README.md's quickstart passes --root, so it stays true; add one sentence under it saying what a run without --root asks. Run make check and the named integration packages and paste the output.` },
]
if (step === 'gate') {
  phase('Gate')
  const results = []
  for (const t of GATE.slice(from)) {
    const r = await workflow({ scriptPath: IMPL }, { ...t, model: t.model || 'sonnet', effort: t.effort || 'medium' })
    results.push(r)
    if (!r || r.status !== 'merged') { log(`Stopped at ${t.id}`); return { results, stopped_at: t.id } }
  }
  return { results }
}

if (step === 'redfix') {
  phase('Red team fixes')
  const results = []
  for (const t of REDFIX.slice(from)) {
    const r = await workflow({ scriptPath: IMPL }, { ...t, model: t.model || 'sonnet', effort: t.effort || (t.model === 'opus' ? 'high' : 'medium') })
    results.push(r)
    if (!r || r.status !== 'merged') { log(`Stopped at ${t.id}`); return { results, stopped_at: t.id } }
  }
  const round = args.round || 3
  const replayFile = args.replay || 'round2-still-leaking.json'
  const only = round >= 4 ? [0, 1, 2] : undefined // a later replay skips the 2026-09-09 probes, which held in rounds 1 to 3
  const variants = args.variants !== false // a pure replay (variants: false) confirms fixes without hunting new shapes
  const third = (await attack(round, replayFile, only, variants)).filter(Boolean).flatMap(r => r.attempts)
  const open = third.filter(x => x.leaked)
  const undocumented = open.filter(x => !x.documented_residual)
  log(`Red team round ${round} (replay of ${replayFile}): ${third.length} attempts, ${open.length} still leaking, ${undocumented.length} of them not named in THREAT_MODEL.md`)
  return { results, round, attempts: third, still_leaking: open, undocumented }
}

const first = (await attack(1)).filter(Boolean).flatMap(r => r.attempts)
const leaks = first.filter(x => x.leaked)
log(`Red team round 1: ${first.length} attempts, ${leaks.length} leaked`)
let fix = null, second = []
if (leaks.length) {
  fix = await workflow({ scriptPath: IMPL }, { id: 'T-REDFIX', title: 'Red team fixes', model: 'opus', effort: 'high', stage: 'hardening', paths: ['internal/', 'cmd/', 'THREAT_MODEL.md', 'testdata/regressions/', 'docs/ERRORS.md', 'docs/FLAGS.md'], integration: true,
    brief: `The red team made lazyslice leak or misbehave in these ways:\n${JSON.stringify(leaks, null, 1)}\nFor each: add a regression test under testdata/regressions/ or the relevant package that reproduces it, then fix it with targeted edits, then update THREAT_MODEL.md with the new threat and control. Never fix by weakening a test.` })
  second = (await attack(2)).filter(Boolean).flatMap(r => r.attempts).filter(x => x.leaked)
  log(`Red team round 2: ${second.length} still leaking`)
}
return { first_round: first, leaks, fix, still_leaking: second }
