export const meta = {
  name: 'lazyslice-hardening',
  description: 'Phase 5: torture schemas, failure UX, performance, then a three-attacker red team with one fix round and re-attack',
  phases: [
    { title: 'Features', detail: 'section 14 phase-5 items: TUI screens, provisioning and rung 4, polymorphic inference, CI matrix and supply chain' },
    { title: 'Backlog', detail: 'review follow-ups carried into phase 5, in dependency order' },
    { title: 'Harden', detail: 'torture, failure UX, performance, each through implement.js in sequence' },
    { title: 'Red team', detail: 'three attackers try to make the tool leak; fix; re-attack' },
  ],
}
const REPO = '/Users/gareth/personal_repos/lazyslice'
const IMPL = `${REPO}/.claude/workflows/implement.js`
// args: { step: 'features' | 'backlog' | 'harden' | 'redteam', from?: index }  one step per usage window; from skips merged tasks in features or backlog
const step = (args && args.step) || 'features'

const FEATURES = [
  { id: 'T-TUI', title: 'Bubble Tea reasons and plan screens', stage: 'tui', paths: ['internal/tui/', 'cmd/lazyslice/'], integration: false,
    brief: `Implement internal/tui per docs/adr/002-tui.md and ARCHITECTURE.md §7 and §9: the reasons screen (classifier decisions with their reason strings, per-column opt-out that builds the same --unmask REASON flag) and the plan screen (tables, estimates, caps hit), both building a core.Request. The line printer stays the default; the TUI runs only on a TTY when the flag or the question ladder invokes it. Every action shows its keybinding; add the ADR-002 test that fails any keybinding lacking a CLI flag. Model tests with the framework's test utilities.` },
  { id: 'T-PROVISION', title: 'Provisioning --create-target and rung 4', stage: 'discover', paths: ['internal/discover/', 'cmd/lazyslice/'], integration: true,
    brief: `Implement discover/provision per ARCHITECTURE.md §9 "Provisioning": --create-target creates and starts a Postgres container matching the source major, and rung 4 offers stopped containers. The T2 gate runs on the provisioned target exactly as on any other. Tracker T-0063 records the seam T-DISCOVER left: widen pipeline.Provisioner to carry the generated POSTGRES_PASSWORD, restore the prompter and controlling-terminal read that were removed as unreachable, and wire --create-target and the one blocking question Q1 per ADR-008 section 6. Integration test against Docker; skip cleanly when Docker is absent.` },
  { id: 'T-POLY', title: 'Polymorphic association inference', stage: 'plan', paths: ['internal/plan/', 'internal/introspect/'], integration: false,
    brief: `Implement ARCHITECTURE.md §3.2 polymorphic inference: detect _type/_id and content_type_id/object_id pairs, add parent-direction virtual edges, report them in the plan, and keep the caps bounding them. Until now the plan printed "polymorphic pair detected, not followed: no constraint"; keep that message for pairs that inference cannot resolve. Tests on nasty.sql's polymorphic pair.` },
  { id: 'T-CI5', title: 'Five-major CI matrix, SBOM, govulncheck, docgen and docs drift', stage: 'foundations', paths: ['.github/', 'Makefile', '.goreleaser.yaml', 'tools/docgen/', 'docs/FLAGS.md', 'docs/KEYBINDINGS.md', 'docs/ERRORS.md', 'internal/tui/'], integration: false,
    brief: `Per ADR-003 and THREAT_MODEL T10: the integration job runs against Postgres 14, 15, 16, 17, and 18 via testcontainers; add govulncheck to CI; add SBOM generation and checksum signing to the goreleaser release if not already present. Write tools/docgen, a small Go program that generates docs/FLAGS.md from the registered cobra flag set of cmd/lazyslice (name, type, default, help, grouped as --help groups them), docs/KEYBINDINGS.md from internal/tui's exported Bindings() table (key, action, the flag it is), and docs/ERRORS.md from internal/event's Catalogue() (code, stage, exit code, message template); add a make docs target that regenerates them and a CI job that fails when the committed files differ from regenerated output (ADR-002's enforcement mechanism). Add the unsafe-flag grep job from CONCEPT.md's enforcement list (fail on --no-mask, --disable-mask, --skip-mask, or any flag whose name contains unmask other than the per-column --unmask TABLE.COL=REASON). Check the workflow files parse and run the docs and grep jobs locally.` },
]

const from = (args && args.from) || 0
if (step === 'features') {
  phase('Features')
  const results = []
  for (const t of FEATURES.slice(from)) {
    const r = await workflow({ scriptPath: IMPL }, { ...t, model: t.id === 'T-CI5' ? 'sonnet' : 'opus', effort: 'high' })
    results.push(r)
    if (!r || r.status !== 'merged') { log(`Stopped at ${t.id}`); return { results, stopped_at: t.id } }
  }
  return { results }
}

const TASKS = [
  { id: 'T-TORTURE', title: 'Schema torture suite', stage: 'hardening', paths: ['testdata/torture/', 'internal/', 'Makefile', 'docs/TORTURE.md'], integration: true,
    brief: `Collect ten real open-source PostgreSQL schemas of different shapes: Discourse, GitLab (a trimmed subset is acceptable, say why), Mastodon, Odoo (subset), Metabase, Supabase auth schema, Cal.com, Plausible, a Django default project with auth and admin, and a Rails default with ActiveStorage. Put each under testdata/torture/<name>/ with its source URL and commit pinned in a README. Add a make torture target that loads each into a container with a small amount of generated data (a generator script per schema, a few hundred rows in the most-connected tables) and runs a snapshot from its most-connected table into a second container, then the invariant checks. For every failure, write a minimal reproduction into testdata/regressions/ before fixing it in internal/. Write docs/TORTURE.md with a table: schema, tables, run time, failures found and fixed, and for three schemas a hand-labelled PII truth set with precision and recall. Do not stop until at least nine of ten snapshot cleanly and the tenth fails with a message that names the exact cause.` },
  { id: 'T-FAILUX', title: 'Failure UX and error catalogue', stage: 'hardening', paths: ['internal/', 'cmd/', 'docs/ERRORS.md'], integration: true,
    brief: `Audit every error path. Each user-facing error must say what went wrong, which table or column, and the exact flag or action that fixes it. No stack trace reaches the user without --debug. Partial failures must leave the target either empty or complete; verify the drop-on-failure path with a test that kills the load mid-way. Define an error type per failure class in one package and write docs/ERRORS.md as the catalogue; add a test that every error type in the code appears in the catalogue and vice versa. Every fix is a targeted edit; do not restructure packages.` },
  { id: 'T-PERF', title: 'Performance baseline', stage: 'hardening', paths: ['internal/extract/', 'internal/load/', 'internal/transform/', 'docs/PERF.md', 'Makefile', '.github/'], integration: true,
    brief: `Profile a snapshot of 5,000 root rows from a source whose child table has 20,000,000 rows (extend the nasty.sql generator with a size parameter). Report where time goes per stage with pprof. Target: under 3 minutes on this machine against local containers. Optimise only the top two hotspots. Write the before and after numbers, the commands, and the flame summary into docs/PERF.md. Add a make bench target and a CI job that fails if extract throughput drops more than 20% from the recorded baseline stored in testdata/bench/baseline.json.` },
]

const BACKLOG = [
  { id: 'T-0075', title: 'CI red from provisioning: Windows file mode, container readiness deadline on runners', model: 'opus', reviewers: 1, stage: 'discover', paths: ['internal/discover/', 'internal/testutil/', '.github/workflows/ci.yml'], integration: './internal/discover/...',
    brief: `Read tracker/tasks/T-0075-*.md. Two CI defects from the provisioning work, both reproduced in GitHub run 34207236918. (1) Windows: TestProvisionCreatesTheContainerSection9Describes asserts the generated password file is 0o600 and Windows reports -rw-rw-rw- because os.Chmod does not carry POSIX modes there. Keep the 0600 guarantee on unix, and on windows skip the mode assertion with a comment naming the limitation (an ACL-based restriction is a later task; note it in internal/discover/provision/CLAUDE.md). (2) Linux runners: every provisioning integration test fails with 'did not accept a connection within 1m0s' while passing locally. The runners have no cached postgres image, so the pull almost certainly runs inside the readiness deadline; verify by removing the image locally (docker rmi postgres:18) and running TestProvisionCreatesAndReusesARealContainer, which should reproduce. Fix: pull or confirm the image before the readiness clock starts (log the pull as its own progress line), start the deadline from container start, wait on the container's 'database system is ready to accept connections' second occurrence before dialling, and make the deadline configurable with a sane default (90 s) that CI can raise through an environment variable read by the provisioner. Also check that the provisioner dials the published host port on the loopback address the daemon actually bound (IPv4 0.0.0.0 publishes are not reachable on ::1 on some hosts) and prefer 127.0.0.1 over localhost. Run make lint && make test && go test -tags integration -count=1 ./internal/discover/... locally with the image removed first, and paste the output including the pull line.` },
  { id: 'T-0052', title: 'testutil retries the mapped port instead of failing on the first miss', model: 'sonnet', reviewers: 1, stage: 'foundations', paths: ['internal/testutil/'], integration: './internal/testutil/... ./internal/load/...',
    brief: `Read tracker/tasks/T-0052-*.md including its Log. internal/testutil.Postgres turns a transient PortEndpoint failure (mapped port 5432/tcp not found, seen in TestKillNineLeavesEveryTableEmptyOrComplete and TestI6RootHoldsTakeRows) into an immediate t.Fatalf. Retry PortEndpoint with a bounded backoff (about ten attempts over five seconds), then fail with a message that names the race. Also handle a stale testcontainers reaper: if container creation fails with a ryuk No such container error, retry once. Add a unit test with a fake that fails the first two calls.` },
  { id: 'T-0073', title: 'Fixture email values out of the masker output space', model: 'sonnet', reviewers: 1, stage: 'foundations', paths: ['testdata/', 'internal/classify/', 'internal/testutil/', 'internal/verify/', 'internal/invariants/CLAUDE.md'], integration: './internal/invariants/...',
    brief: `ARCHITECTURE.md section 5 records that the email masker emits addresses under example.com, example.net and example.org, so a source value in those domains can equal a masked value and I2's assertMaskedValuesAreNew fails intermittently (seen on public.people.alt_emails against uploaded_by, owned_by, ref, and tenant_users.email). Change every source email address in testdata/ (nasty.sql and any generated data) to a domain the masker never emits, such as fixture.test or corp.invalid, keeping row counts and NULL patterns and keeping the values valid for net/mail.ParseAddress. Update testdata/README.md, and any classify, verify, or testutil test that asserts the literal old addresses. Add one sentence to internal/invariants/CLAUDE.md pointing at the section 5 note. Run the invariants package three times (go test -tags integration -count=3 ./internal/invariants/...) and paste the result.` },
  { id: 'T-0046', title: 'Fixture: deferrable unique on a partitioned root, leaf-local key, edge referencing the leaf', model: 'sonnet', reviewers: 1, stage: 'foundations', paths: ['testdata/', 'internal/testutil/', 'internal/introspect/', 'internal/plan/'], integration: './internal/introspect/... ./internal/plan/...',
    brief: `Read tracker/tasks/T-0046-*.md. Add to testdata/nasty.sql a partitioned root carrying a DEFERRABLE unique constraint, a leaf partition carrying its own non-deferrable unique key the root cannot hold, and a child table whose foreign key references the leaf's key. Document the trap in testdata/README.md. Add integration assertions: introspect leaves that edge un-re-pointed with ForeignKey.NotRecreatable set, and the planner refuses at plan time with exit 13 and target.schema.not_recreatable naming the edge, before anything in a target is touched. Update any fixture count assertion.` },
  { id: 'T-0049', title: 'Mask module low findings and a registry test for rules.yml masker ids', model: 'sonnet', reviewers: 1, stage: 'mask', paths: ['mask/', 'internal/classify/', 'internal/transform/'], integration: false,
    brief: `Read tracker/tasks/T-0049-*.md and the Log section of tracker/tasks/T-0040-*.md. Fix each recorded low finding in mask/ with a targeted edit and a test: the unique branch must refuse when no generator fits regardless of an unknown row count; freeTextExact clamps to MaxLen; satAdd saturates; checkValues treats NOT IN and NOT (= ANY) as forbidden sets, not allowed sets; the network_id range test generates honest inputs including documentation-range values and counts distinct outputs. Move internal/transform/writeback_test.go's two RFC 5737 probe values to RFC 1918. Add a test in internal/classify that every masker id named in rules.yml resolves in the mask registry. Do not change generator behaviour beyond what a finding names.` },
  { id: 'T-0053', title: 'pg gate follow-ups: transaction pin, rollback discipline, schema-only introspection', model: 'opus', reviewers: 3, stage: 'pg', paths: ['internal/pg/', 'internal/introspect/', 'internal/pipeline/', 'internal/load/'], integration: './internal/pg/... ./internal/load/... ./internal/introspect/...',
    brief: `Read tracker/tasks/T-0053-*.md. (1) In internal/pg's own integration suite add a case whose injected fingerprinter issues SAVEPOINT through the reader it is handed and fails on 25P01, so the BEGIN around the fingerprinter is pinned where it lives. (2) Route a failed ROLLBACK in catalogFingerprint through the same discipline as source.go's endTx (close the connection) and correct the doc comment that claims the gate has rules left to run. (3) Add a schema-only introspection path (an option on the Introspector or a second method, whichever ARCHITECTURE.md section 2 tolerates with the smallest change; report the deviation) so the gate's fingerprint over the target does not sample rows or hold a REPEATABLE READ transaction longer than the catalog read; use it from load.GateFingerprint. Fix the stale comments T-FPR's reviewer listed.` },
  { id: 'T-0050', title: 'Extract and transform hand-offs: shape-template escaping, KeySet chunk iterator, pooler test, text-keyed big fixture', model: 'opus', reviewers: 3, stage: 'extract', paths: ['internal/extract/', 'internal/pg/', 'internal/pipeline/', 'internal/plan/', 'internal/verify/', 'internal/testutil/', 'testdata/'], integration: './internal/extract/... ./internal/plan/... ./internal/verify/... ./internal/pg/...',
    brief: `Read tracker/tasks/T-0050-*.md including its Log. (1) lookupShapeFor interpolates a quoted table name into a shape template, so a table named with a {token} widens or breaks the allowlist; give the tracer a way to register a shape with a pre-quoted literal segment, or escape placeholder-shaped text in identifiers, with a test using a table named with braces. (2) Add FirstChunk(n int) Chunk to pipeline.KeySet and both internal/plan implementations, and a chunk-at-a-time iterator so extract's peak memory is one chunk, not a full copy of the key set; make internal/verify/sample.go use FirstChunk and drop its fallback; record the section 2 change in the package CLAUDE.md files. (3) Add a pgbouncer testcontainer helper to internal/testutil and one integration test proving the pooler-safe startup parameter list and the pooled single-connection fallback. (4) Add a text-keyed or uuid-keyed large table to the nasty generator and a memory-bound extract test over it.` },
  { id: 'T-PIN', title: 'The run that writes the target is pinned to the snapshot and endpoints the operator reviewed', model: 'opus', reviewers: 3, stage: 'core', paths: ['internal/core/', 'internal/pipeline/', 'internal/event/catalogue.yml', 'cmd/lazyslice/', 'internal/tui/'], integration: true,
    brief: `From T-TUI's review. With --tui, cmd/lazyslice runs a preview core.Run (plan only) to fill the reasons and plan screens, then a second core.Run with the built request; nothing ties the two together, so the operator's review is of a different snapshot and a different discovery walk than the run that writes the target. Add to core.Request an optional Reviewed struct carrying the preview's pipeline.Schema.Fingerprint (ADR-009 definition) and the chosen source and target endpoints; when set, core compares after introspection and discovery and refuses with a new event code (core.refused.reviewed_changed, exit 12, naming what changed) before any write. cmd/lazyslice fills it from the preview; the plan lines printed by the preview are then not reprinted by the run. Tests in internal/core: identical snapshot passes; a schema change between passes refuses; a different resolved target refuses. Update the runTUI doc comment that records the limit. Also apply the lows recorded in the Log of tracker/tasks/T-0071-*.md (options-literal test asserts values, openTarget empty-target test, ArgReason redaction test against a PgError with Detail, the three dangling comment back-references).` },
  { id: 'T-0076', title: 'Source read-only setting scoped per transaction; no session GUC leaks through a transaction-pooling PgBouncer', model: 'opus', reviewers: 3, stage: 'pg', paths: ['internal/pg/', 'internal/testutil/', 'THREAT_MODEL.md'], integration: './internal/pg/...',
    brief: `Read tracker/tasks/T-0076-*.md and internal/pg/CLAUDE.md's paragraph on the measured leak. internal/pg's AfterConnect runs SET default_transaction_read_only = on on every source connection; through a transaction-pooling PgBouncer that session GUC stays on the shared server connection after lazyslice exits, so other applications on the pooler become read-only for up to server_lifetime. Every source transaction is already BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY, so the session default is defence in depth that harms neighbours. Drop the AfterConnect exec and the source.read_only statement shape; wrap the one statement issued outside a transaction (Source.SystemID) in a read-only transaction; keep the tracer allowlist as the enforcement. Add an integration test using the pgbouncer testcontainer from T-0050 proving that after a lazyslice source session ends, a second client on the same pooler can CREATE TABLE. THREAT_MODEL.md is in your paths for exactly one edit: reword T9's read-only bullet (added 2026-09-06) to say the setting is per transaction, never a session default, and why. Record the decision in internal/pg/CLAUDE.md.` },
  { id: 'T-0077', title: 'stream_docs lifted above the nasty.sql big gate; introspect table list updated', model: 'sonnet', reviewers: 1, stage: 'foundations', paths: ['testdata/', 'internal/introspect/', 'internal/testutil/', 'internal/extract/'], integration: './internal/introspect/... ./internal/extract/...',
    brief: `Read tracker/tasks/T-0077-*.md. testdata/nasty.sql defines public.stream_docs and public.fill_stream_docs inside the \\if :{?big} gate, so the fixture's schema differs by load flag (25 tables by default, 26 with big). Move the CREATE TABLE and CREATE FUNCTION above the gate so the schema is constant and only the fill stays gated; add public.stream_docs to the table list internal/introspect/introspect_integration_test.go asserts; remove the nastyTables hole and the assertNastyGateOff special case in internal/extract that worked around it; update testdata/README.md. Run the named integration packages with and without the big flag.` },
  { id: 'T-0055', title: 'Shared validators package with the name dictionary; person_name and free_text in the second net', model: 'opus', reviewers: 3, stage: 'verify', paths: ['internal/classify/', 'internal/verify/', 'internal/pipeline/', 'internal/textsig/'], integration: './internal/classify/... ./internal/verify/...',
    brief: `Read tracker/tasks/T-0055-*.md. Create a leaf package internal/textsig holding the value-only halves of the classifier's validators and the embedded name dictionary, imported by both internal/classify and internal/verify (check internal/CLAUDE.md's import-graph rule: a leaf under internal/ that imports only ref and pipeline is allowed; say so in its CLAUDE.md). Register person_name and free_text in verify's second net. Decide the verify-side false-positive threshold: a single dictionary word (black, brown, hill, green, wood) in a column must not fail a target; require the classifier's own multi-token name shape or a dictionary hit rate over the strong threshold across at least minValues distinct values, and name the rule in internal/verify/CLAUDE.md. Update THREAT_MODEL.md T1's gap list only by reporting it; the orchestrator edits that file.` },
]

if (step === 'backlog') {
  phase('Backlog')
  const results = []
  for (const t of BACKLOG.slice(from)) {
    const r = await workflow({ scriptPath: IMPL }, { ...t, effort: t.model === 'opus' ? 'high' : 'medium' })
    results.push(r)
    if (!r || r.status !== 'merged') { log(`Stopped at ${t.id}`); return { results, stopped_at: t.id } }
  }
  return { results }
}

if (step === 'harden') {
  phase('Harden')
  const results = []
  for (const t of TASKS) {
    const r = await workflow({ scriptPath: IMPL }, { ...t, model: 'opus', effort: 'high' })
    results.push(r)
    if (!r || r.status !== 'merged') { log(`Stopped at ${t.id}`); return { results, stopped_at: t.id } }
  }
  return { results }
}

phase('Red team')
const ATTACK = { type: 'object', required: ['attempts'], properties: { attempts: { type: 'array', items: { type: 'object', required: ['attack', 'reproduction', 'leaked', 'fix'], properties: { attack: { type: 'string' }, reproduction: { type: 'string' }, leaked: { type: 'boolean' }, fix: { type: 'string' } } } } } }
const attackers = [
  'PII that dodges the classifier: column names in other languages or abbreviations, values that miss every regex (obfuscated emails, phone numbers with spaces and words, names in a column called label), personal data inside arrays and JSON three levels deep, and inside a column the classifier marked as safe. Build a schema for each, run the tool, and check the target.',
  'Wrong target: make the tool write to production by aliasing the host, using a different port on the same database, a read replica, a connection string with the same database name on a different host, or a target URL taken from a compose file that points at prod. Also try to get it to hold write privileges on the source.',
  'Secrets and residue: get a password, secret, or unmasked row into lazyslice.yml, logs at any verbosity, the emitted error messages, a crash dump, a temp file, or a snapshot written into a git-tracked or cloud-synced folder. Also try a custom masker that throws halfway and one that returns its input.',
]
const attack = (round) => parallel(attackers.map((a, i) => () => agent(`You are a red-team engineer trying to make lazyslice leak production data. Repo: ${REPO}. Read THREAT_MODEL.md, ARCHITECTURE.md, and the code. Build the binary. Use the testutil containers. Your attack surface: ${a} For each attempt give the exact reproduction commands, whether anything leaked or the tool misbehaved, and the fix. Do not change any repo file; put scratch schemas under /private/tmp/claude-501/lazyslice-scratch/redteam-${i}/. Report every attempt, including the ones that failed to leak.`,
  { label: `attack:${i + 1}:r${round}`, phase: 'Red team', model: 'opus', schema: ATTACK })))

const first = (await attack(1)).filter(Boolean).flatMap(r => r.attempts)
const leaks = first.filter(x => x.leaked)
log(`Red team round 1: ${first.length} attempts, ${leaks.length} leaked`)
let fix = null, second = []
if (leaks.length) {
  fix = await workflow({ scriptPath: IMPL }, { id: 'T-REDFIX', title: 'Red team fixes', model: 'opus', effort: 'high', stage: 'hardening', paths: ['internal/', 'cmd/', 'THREAT_MODEL.md', 'testdata/regressions/'], integration: true,
    brief: `The red team made lazyslice leak or misbehave in these ways:\n${JSON.stringify(leaks, null, 1)}\nFor each: add a regression test under testdata/regressions/ or the relevant package that reproduces it, then fix it with targeted edits, then update THREAT_MODEL.md with the new threat and control. Never fix by weakening a test.` })
  second = (await attack(2)).filter(Boolean).flatMap(r => r.attempts).filter(x => x.leaked)
  log(`Red team round 2: ${second.length} still leaking`)
}
return { first_round: first, leaks, fix, still_leaking: second }
