export const meta = {
  name: 'lazyslice-implement',
  description: 'One task: developer implements, three reviewers, up to two fix rounds, independent verify, commit',
  phases: [
    { title: 'Build', detail: 'developer implements the brief and runs the checks' },
    { title: 'Review', detail: 'correctness, safety, scope reviewers in parallel' },
    { title: 'Fix', detail: 'developer addresses findings, reviewer re-verifies' },
    { title: 'Verify', detail: 'independent check run and commit' },
  ],
}
// args: { id, title, brief, model, effort, paths, stage }
//   id     tracker task id (for the commit message)
//   title  short title
//   brief  the full task text (from docs/BUILD_PLAN.md or written by the orchestrator)
//   model  developer model: 'opus' | 'sonnet' ('opus' is Opus 5.5 by its full id, OPUS below; the bare alias resolved to Opus 5 in Claude Code 2.1.275 and Opus 5.5 needs 2.1.280 or newer, so a run must start from a session on that version)
//   paths  directories or files the developer may write, as an array of repo-relative paths
//   stage  pipeline stage name or 'peripheral'
//   reviewers  1 (default; one Opus reviewer with a merged correctness-and-safety lens) or 3 (the three lenses, only when the task says so)
//   effort  developer effort; default medium for both (Opus 5.5 at medium matches Opus 5 at high on coding and review in fewer tokens, docs/prompting/opus-5-5.md; the maintainer, 2026-09-22).  reviewEffort  reviewer and re-verifier effort, default medium
//   integration  true: run make integration in verify (only once the pipeline can pass I1-I6); a package pattern string like './internal/pg/...': run that package's integration-tagged tests instead
//   checks  'full' (default) or 'none' for documentation-only tasks; parallel code tasks are verified by the orchestrator after the batch

const REPO = '/Users/gareth/personal_repos/lazyslice'
const a = args || {}
if (!a.brief || !a.id) throw new Error('implement.js needs args {id, title, brief, model, paths}')
// Opus is named by its full id, not the alias: the alias followed whatever the running Claude Code mapped it to (Opus 5 on 2.1.275 after Opus 5.5 was out),
// and the prompting guide says to set the model and its effort explicitly rather than inherit (docs/prompting/opus-5-5.md). Opus 5 stays the fallback by hand.
const OPUS = 'claude-opus-5-5'
const model = a.model === 'opus' ? OPUS : (a.model || 'sonnet') // default Sonnet; a task opts in to Opus only for masking, verify, or source-safety logic (the maintainer, 2026-09-09)
const effort = a.effort || 'medium' // Opus 5.5's own default; it was high for Opus 5 (the maintainer, 2026-09-14) and medium on 5.5 is the same quality in fewer tokens (2026-09-22)
const paths = (a.paths || []).join(', ')
const nReviewers = a.reviewers === 3 ? 3 : 1 // default one reviewer; three only when the task says so

const PRE = `You are a developer on lazyslice. Repo: ${REPO}. Read ${REPO}/CLAUDE.md, ${REPO}/ARCHITECTURE.md, and the CLAUDE.md in every directory you touch, before writing code.
Rules: a test fixture never imitates a real provider's secret format (no ghp_/sk_live_/xoxb-/AKIA/SG./Discord-token shapes, even invented): GitHub's push protection refuses the whole push (T-0315, 2026-09-24); use a synthetic high-entropy string of the same length instead. You may write only under these paths: ${paths}. You may not add a module to go.mod; if you need a dependency that is missing, stop and report it in your return value. You may run go mod tidy when it only moves an already-present module between direct and indirect, and CI requires go.mod to be tidy, so run go mod tidy -diff before returning. Do not fix nearby code, do not extend behaviour the task did not mention, do not add tests beyond the task. If you must deviate from ARCHITECTURE.md (a module path, a signature, a default), say so in concerns; never silently. Work that someone must do outside your paths is filed by you with python3 tools/tracker.py new --epic E9 --title ... --goal ... (the one permitted write outside your paths; never edit tracker files by hand), and the task id goes in the CLAUDE.md note that records the debt. Your changelog bullets become the commit body and, later, the release notes between two versions: write each as what a user of the tool now sees or no longer suffers (a flag, an exit code, a kind of column, a message), not what the code does. README.md and SECURITY.md are what a stranger reads first: when your change adds or changes a flag, an exit code or a first-run behaviour either of them describes, or makes a sentence in them untrue, correct that sentence in the same task (both files are inside your paths for exactly that reason, like the generated docs) and say so in your changelog; do not otherwise rewrite them. Prefer targeted edits over rewriting files. Run gofmt on files you touch. docs/ERRORS.md, docs/FLAGS.md and docs/KEYBINDINGS.md are generated by make docs from internal/event/catalogue.yml and the command tree; whenever you change either, run make docs and treat the regenerated files as yours (they are inside your paths for exactly that reason; a stale one fails make check and CI). Before returning, run: make check (and make integration if your task says so), and paste the last 20 lines of output into your return value. "Should work" is not a status. Do not commit. Nobody is watching and nobody can answer questions: finish the whole task. A previous attempt at this task may have been interrupted: if files under your paths already exist, read them and continue from that state rather than starting over. Return your report as one StructuredOutput call whose object has every field as a top-level key (files, summary, changelog, checks_output, checks_passed, concerns, postmortem); never write one field inside another field's text: T-0325's developer put the changelog inside summary, failed the schema five times and took the batch down (2026-09-24). Keep every scratch file, log and temporary schema under /private/tmp/claude-501/-Users-gareth-personal-repos-lazyslice/ (the session scratchpad) or the repo's own ignored paths, never under /tmp or your home directory, and never call a directory-access or permission-request tool: nobody is watching to approve it, and T-0398's first developer stalled for two hours on one (2026-09-25).`
// Opus 5.5 may end an unattended turn with a text report while work is still owed (docs/prompting/opus-5-5.md, "Unattended agentic runs"). The guide's own
// paragraph, verbatim and last, names the stops it should not make; it is scoped to Opus 5.5 because that is the model it was written and measured for.
const EARLY_STOP = `A standing instruction from the user, the person you are working for. It is about how your turns end. A message with no tool call in it ends your turn, and the work stops there until you are asked to continue. The user has seen you end turns in four ways while work they asked for was still owed, and does not want any of them. One: a long summary of what was done that closes by announcing the next step and has no tool call, so the next thing never starts. Two: an offer to carry on with something unless the user would prefer otherwise, which stops to wait for an answer the user was not going to give. Three: a list of decisions for the user when, by your own account, none of them blocks the rest of the work. Four: deciding that this is a good place to report, because the turn has been long or a milestone is done. Status notes are welcome, and so are your recommendations on open decisions, but put them in the same message as your next tool call and carry on with whatever does not depend on the user's answer. If you notice yourself inviting the user to redirect you or offering to wait, delete it and do the next thing. The stops the user does want are the ones where nothing can move without them, or where the thing blocking you is deliberately protected from you. This does not override the need for confirmation on risky or destructive actions.`
const DEV_PROMPT = model === OPUS ? `${PRE}\n\n${EARLY_STOP}` : PRE

const DEV = { type: 'object', required: ['files', 'summary', 'changelog', 'checks_output', 'checks_passed', 'concerns', 'postmortem'], properties: {
  files: { type: 'array', items: { type: 'string' } }, summary: { type: 'string', description: 'at most 150 words' },
  changelog: { type: 'array', minItems: 1, items: { type: 'string', minLength: 40 }, description: 'three to eight bullets for the commit body and the release notes: each one user-visible change or fix in plain words, naming the flag, exit code, column kind or behaviour, never a file or function name or a tracker id; a doc-only change gets one bullet' },
  checks_output: { type: 'string', description: 'last 20 lines of make check' }, checks_passed: { type: 'boolean' },
  concerns: { type: 'array', items: { type: 'string' }, description: 'things noticed outside scope, missing deps, doubts' },
  postmortem: { type: 'string', minLength: 80, description: 'went well | went badly | change next time; T-0213 returned ok and a one-letter changelog, so both fields now have a floor' } } }

// The fix round returns the developer's shape, but its changelog is optional and is appended to the original bullets: a fix that changes nothing a user sees adds no bullet. A required changelog here failed T-0188's landing five times (2026-09-15) when the fixer's return was rejected for the missing field.
const FIX = { ...DEV, required: DEV.required.filter(k => k !== 'changelog') }
const FINDINGS = { type: 'object', required: ['findings'], properties: { findings: { type: 'array', items: { type: 'object',
  required: ['severity', 'file', 'line', 'issue', 'fix'], properties: { severity: { type: 'string', enum: ['high', 'medium', 'low'] },
  file: { type: 'string' }, line: { type: 'integer' }, issue: { type: 'string' }, fix: { type: 'string' } } } } } }

const LENSES = [
  { key: 'correctness', text: 'Correctness. Read the diff (git diff) and the files listed. Find bugs: wrong logic, unhandled errors, off-by-one, races, resource leaks, Postgres edge cases (nulls, composite keys, quoted identifiers, schemas other than public, partitions). Does every test actually assert the behaviour the brief asks for, or could a stub pass it?' },
  { key: 'safety', text: 'Data safety and invariants. Could this change let unmasked personal data reach the target, write to the source, log a secret, or leave a half-loaded target? Does it weaken any invariant I1-I6 in ARCHITECTURE.md or a control in THREAT_MODEL.md? Is any flag added that reduces masking?' },
  { key: 'scope', text: 'Scope and simplicity. Did the developer do only what the brief asked? Flag unrequested changes, extra files, speculative abstractions, dependencies added, and anything that belongs to a later phase per ROADMAP.md. Flag code that two other developers would each have to understand to work on the next stage.' },
]

// One reviewer reads through a merged correctness-and-safety lens; three reviewers split the lenses (the maintainer, 2026-09-14: conservative on model and effort, not on what the reviewer looks for).
const SOLO = { key: 'correctness+safety', text: LENSES[0].text + ' Then, ' + LENSES[1].text }
const lenses = nReviewers === 3 ? LENSES : [SOLO]
const reviewEffort = a.reviewEffort || 'medium'

log(`Task ${a.id}: ${a.title} (developer: ${model}, effort ${effort}, reviewers ${nReviewers})`)
let dev = await agent(`${DEV_PROMPT}\n\n<task id="${a.id}">\n${a.brief}\n</task>`, { label: `build:${a.id}`, phase: 'Build', model, effort, schema: DEV })
if (!dev) return { id: a.id, status: 'blocked', reason: 'developer agent died', findings: [] }

const review = async (round) => {
  const rs = await parallel(lenses.map(l => () => agent(`You are a reviewer on lazyslice. Repo: ${REPO}. Read ${REPO}/CLAUDE.md and ${REPO}/ARCHITECTURE.md. The task under review is:\n<task id="${a.id}">\n${a.brief}\n</task>\nThe developer reports: ${dev.summary}. Files: ${dev.files.join(', ')}. Checks passed: ${dev.checks_passed}.\nYour lens: ${l.text}\nRun the checks yourself (make check) and do not trust the developer's report. Do not fix anything. Return findings with file and line; severity high means it must not merge.`,
    { label: `review:${l.key}:r${round}`, phase: 'Review', model: OPUS, effort: reviewEffort, schema: FINDINGS })))
  return rs.filter(Boolean).flatMap(r => r.findings)
}

let findings = await review(1)
let blocking = findings.filter(f => f.severity !== 'low')
let round = 0
while (blocking.length && round < 2) {
  round++
  log(`Round ${round}: ${blocking.length} findings to fix`)
  const fixed = await agent(`${PRE}\n\nYou implemented task ${a.id}: ${a.title}. Reviewers found:\n${JSON.stringify(blocking, null, 1)}\nAddress every high and medium finding with targeted edits. If you believe a finding is wrong, say so in concerns with your reasoning rather than silently ignoring it. Re-run the checks. Keep summary to a few sentences. Your changelog lists only user-visible changes this fix adds, if any; the original bullets are kept.`,
    { label: `fix:${a.id}:r${round}`, phase: 'Fix', model, effort, schema: FIX })
  if (!fixed) break
  dev = { ...fixed, changelog: [...(dev.changelog || []), ...(fixed.changelog || [])], postmortem: fixed.postmortem || dev.postmortem }
  const re = await agent(`You are the re-verifier on lazyslice. Repo: ${REPO}. These findings were reported on task ${a.id} and the developer says they are fixed:\n${JSON.stringify(blocking, null, 1)}\nDeveloper's concerns: ${JSON.stringify(dev.concerns)}. Check each finding against the current code (git diff, read the files). Run make check. Return only findings that are still open, keeping their severity, plus any new high-severity problem the fix introduced.`,
    { label: `reverify:${a.id}:r${round}`, phase: 'Fix', model: OPUS, effort: reviewEffort, schema: FINDINGS })
  blocking = re ? re.findings.filter(f => f.severity !== 'low') : []
}

if (blocking.length) {
  log(`Task ${a.id} blocked after ${round} fix rounds`)
  return { id: a.id, status: 'blocked', findings: blocking, dev, postmortem: dev.postmortem }
}

const integ = a.integration === true ? ' && make integration' : (typeof a.integration === 'string' ? ` && go test -tags integration -count=1 ${a.integration}` : '')
// A task that touches the regression corpus is verified under make torture as well: T-0137 returned without running it and a red regression sat on main across four landings (T-0172, 2026-09-15).
// The corpus gate is decided by the working tree, not the path list: a task allowed to touch testdata/ that did not is not held for a run that can take an hour (T-0319's verify agent was cut off mid-torture on a tree with no corpus change, 2026-09-24).
const torture = (a.paths || []).some(p => p.startsWith('testdata/regressions') || p === 'testdata/') ? ' && (if git status --porcelain -- testdata/ | grep -q .; then make torture; else echo "torture skipped: nothing under testdata/ changed"; fi)' : ''
const verify = a.checks === 'none' ? { passed: true, output: 'checks skipped: documentation task' } : await agent(`Repo: ${REPO}. Run, in the foreground and waiting for it to finish (never as a background task: a result reported before the command has exited counts as not run), exactly: cd ${REPO} && docker info --format '{{.ServerVersion}}' | grep -q . && make check${integ}${torture}. The docker check comes first because every integration test skips silently when Docker is down and a skipped suite reports ok; if docker info prints nothing, wait 30 seconds and run docker info once more (Docker Desktop answers late under load; T-0190's landing was reported as Docker down while it was up); only if it prints nothing twice report passed=false with the reason 'Docker is not running' and do not run the rest. If an integration package fails only because a container's mapped port was not found after the startup wait (the message names 'port not mapped' or T-0052, Docker's known port-table race on this machine), run that one package again once and use the second result; say that you did. The torture step, when the command has one, runs only if something under testdata/ is modified in the working tree; if it prints 'torture skipped', that step counts as passed and you say so. Report whether every command exited 0 and paste the last 30 lines of output. Do not change any file.`,
  { label: `verify:${a.id}`, phase: 'Verify', model: 'sonnet', effort: 'medium', schema: { type: 'object', required: ['passed', 'output'], properties: { passed: { type: 'boolean' }, output: { type: 'string', minLength: 300, description: 'the last 30 lines the command actually printed, pasted verbatim; never a summary or a placeholder (T-0255 was blocked by a verify step that returned the word placeholder)' } } } })

if (!verify || !verify.passed) {
  return { id: a.id, status: 'blocked', findings: [{ severity: 'high', file: 'Makefile', line: 0, issue: 'independent check run failed', fix: (verify && verify.output) || 'no output' }], dev, postmortem: dev.postmortem }
}

// Commit message: headline with the stage and tracker id, then the developer's changelog bullets as the body (the maintainer, 2026-09-15: release notes are generated from these bodies by tools/relnotes.py, so the bullets describe behaviour, not code), then trailers.
const bullets = (dev.changelog && dev.changelog.length ? dev.changelog : [dev.summary]).map(b => '- ' + String(b).replace(/\s+/g, ' ').trim()).join('\n')
const trailers = `Task: ${a.id}\nReview: ${nReviewers} reviewer${nReviewers === 1 ? '' : 's'}, ${round} fix round${round === 1 ? '' : 's'}`
const message = `${(a.stage || 'peripheral')}: ${a.title} (${a.id})\n\n${bullets}\n\n${trailers}\n`
// The message file lives outside the repository and staging is scoped to the task's paths plus tracker/: writing under .git/ and git add -A tripped a safety classifier twice (T-0178, T-0221, 2026-09-16) and a blocked commit then bled into the next task's commit. A commit that did not happen blocks the task instead of reporting merged with no hash.
const MSG = `/private/tmp/claude-501/lazyslice-scratch/COMMIT_MSG_${a.id}`
const stagePaths = [...(a.paths || []), 'tracker/', 'docs/ERRORS.md', 'docs/FLAGS.md', 'docs/KEYBINDINGS.md', 'README.md', 'SECURITY.md'].map(p => `'${p}'`).join(' ')
const commit = await agent(`Repo: ${REPO}. Create the directory /private/tmp/claude-501/lazyslice-scratch if it is missing and write the following commit message, exactly and completely, to the file ${MSG} (create it; do not edit it):\n<<<\n${message}>>>\nThen run: cd ${REPO} && git add -A -- ${stagePaths} && git commit -F ${MSG} && rm -f ${MSG}, and report the short hash. If git rejects a pathspec because a path does not exist, drop that path from the list and run the same command again. Do not use git add -A without the path list, and do not change any other file. If there is nothing to commit, report hash as the empty string and say why.`,
  { label: `commit:${a.id}`, phase: 'Verify', model: 'haiku', effort: 'low', schema: { type: 'object', required: ['hash'], properties: { hash: { type: 'string' } } } })
if (!commit || !commit.hash) {
  log(`Task ${a.id}: verified but not committed`)
  return { id: a.id, status: 'blocked', findings: [{ severity: 'high', file: 'tracker/', line: 0, issue: 'the commit step did not commit; the tree holds the verified work', fix: 'commit by hand with the lazyslice-commit skill, then resume from the next task' }], dev, postmortem: dev.postmortem }
}

return { id: a.id, status: 'merged', hash: commit ? commit.hash : '', files: dev.files, summary: dev.summary, concerns: dev.concerns, findings_low: findings.filter(f => f.severity === 'low'), rounds: round, postmortem: dev.postmortem }
