export const meta = {
  name: 'lazyslice-implement',
  description: 'One task: developer implements, three reviewers, up to two fix rounds, independent verify, commit',
  phases: [
    { title: 'Build', detail: 'developer implements the brief and runs the checks' },
    { title: 'Review', detail: 'correctness, safety, scope reviewers in parallel' },
    { title: 'Fix', detail: 'developer addresses findings, reviewer re-verifies' },
    { title: 'Verify', detail: 'independent check run and commit' },
  ],
}
// args: { id, title, brief, model, effort, paths, stage }
//   id     tracker task id (for the commit message)
//   title  short title
//   brief  the full task text (from docs/BUILD_PLAN.md or written by the orchestrator)
//   model  developer model: 'opus' | 'sonnet'
//   paths  directories or files the developer may write, as an array of repo-relative paths
//   stage  pipeline stage name or 'peripheral'
//   reviewers  1 (default; one Opus reviewer with a merged correctness-and-safety lens) or 3 (the three lenses, only when the task says so)
//   effort  developer effort; default high for opus, medium for sonnet.  reviewEffort  reviewer and re-verifier effort, default medium
//   integration  true: run make integration in verify (only once the pipeline can pass I1-I6); a package pattern string like './internal/pg/...': run that package's integration-tagged tests instead
//   checks  'full' (default) or 'none' for documentation-only tasks; parallel code tasks are verified by the orchestrator after the batch

const REPO = '/Users/gareth/personal_repos/lazyslice'
const a = args || {}
if (!a.brief || !a.id) throw new Error('implement.js needs args {id, title, brief, model, paths}')
const model = a.model || 'sonnet' // default Sonnet; a task opts in to Opus only for masking, verify, or source-safety logic (Gareth, 2026-09-09)
const effort = a.effort || (model === 'opus' ? 'high' : 'medium') // Opus tasks are the safety ones and keep high; Sonnet runs at medium (Gareth, 2026-09-14)
const paths = (a.paths || []).join(', ')
const nReviewers = a.reviewers === 3 ? 3 : 1 // default one reviewer; three only when the task says so

const PRE = `You are a developer on lazyslice. Repo: ${REPO}. Read ${REPO}/CLAUDE.md, ${REPO}/ARCHITECTURE.md, and the CLAUDE.md in every directory you touch, before writing code.
Rules: you may write only under these paths: ${paths}. You may not add a module to go.mod; if you need a dependency that is missing, stop and report it in your return value. You may run go mod tidy when it only moves an already-present module between direct and indirect, and CI requires go.mod to be tidy, so run go mod tidy -diff before returning. Do not fix nearby code, do not extend behaviour the task did not mention, do not add tests beyond the task. If you must deviate from ARCHITECTURE.md (a module path, a signature, a default), say so in concerns; never silently. Work that someone must do outside your paths is filed by you with python3 tools/tracker.py new --epic E9 --title ... --goal ... (the one permitted write outside your paths; never edit tracker files by hand), and the task id goes in the CLAUDE.md note that records the debt. Your changelog bullets become the commit body and, later, the release notes between two versions: write each as what a user of the tool now sees or no longer suffers (a flag, an exit code, a kind of column, a message), not what the code does. Prefer targeted edits over rewriting files. Run gofmt on files you touch. docs/ERRORS.md, docs/FLAGS.md and docs/KEYBINDINGS.md are generated by make docs from internal/event/catalogue.yml and the command tree; whenever you change either, run make docs and treat the regenerated files as yours (they are inside your paths for exactly that reason; a stale one fails make check and CI). Before returning, run: make check (and make integration if your task says so), and paste the last 20 lines of output into your return value. "Should work" is not a status. Do not commit. Nobody is watching and nobody can answer questions: finish the whole task. A previous attempt at this task may have been interrupted: if files under your paths already exist, read them and continue from that state rather than starting over.`

const DEV = { type: 'object', required: ['files', 'summary', 'changelog', 'checks_output', 'checks_passed', 'concerns', 'postmortem'], properties: {
  files: { type: 'array', items: { type: 'string' } }, summary: { type: 'string', description: 'at most 150 words' },
  changelog: { type: 'array', items: { type: 'string' }, description: 'three to eight bullets for the commit body and the release notes: each one user-visible change or fix in plain words, naming the flag, exit code, column kind or behaviour, never a file or function name or a tracker id; a doc-only change gets one bullet' },
  checks_output: { type: 'string', description: 'last 20 lines of make check' }, checks_passed: { type: 'boolean' },
  concerns: { type: 'array', items: { type: 'string' }, description: 'things noticed outside scope, missing deps, doubts' },
  postmortem: { type: 'string', description: 'went well | went badly | change next time' } } }

const FINDINGS = { type: 'object', required: ['findings'], properties: { findings: { type: 'array', items: { type: 'object',
  required: ['severity', 'file', 'line', 'issue', 'fix'], properties: { severity: { type: 'string', enum: ['high', 'medium', 'low'] },
  file: { type: 'string' }, line: { type: 'integer' }, issue: { type: 'string' }, fix: { type: 'string' } } } } } }

const LENSES = [
  { key: 'correctness', text: 'Correctness. Read the diff (git diff) and the files listed. Find bugs: wrong logic, unhandled errors, off-by-one, races, resource leaks, Postgres edge cases (nulls, composite keys, quoted identifiers, schemas other than public, partitions). Does every test actually assert the behaviour the brief asks for, or could a stub pass it?' },
  { key: 'safety', text: 'Data safety and invariants. Could this change let unmasked personal data reach the target, write to the source, log a secret, or leave a half-loaded target? Does it weaken any invariant I1-I6 in ARCHITECTURE.md or a control in THREAT_MODEL.md? Is any flag added that reduces masking?' },
  { key: 'scope', text: 'Scope and simplicity. Did the developer do only what the brief asked? Flag unrequested changes, extra files, speculative abstractions, dependencies added, and anything that belongs to a later phase per ROADMAP.md. Flag code that two other developers would each have to understand to work on the next stage.' },
]

// One reviewer reads through a merged correctness-and-safety lens; three reviewers split the lenses (Gareth, 2026-09-14: conservative on model and effort, not on what the reviewer looks for).
const SOLO = { key: 'correctness+safety', text: LENSES[0].text + ' Then, ' + LENSES[1].text }
const lenses = nReviewers === 3 ? LENSES : [SOLO]
const reviewEffort = a.reviewEffort || 'medium'

log(`Task ${a.id}: ${a.title} (developer: ${model}, effort ${effort}, reviewers ${nReviewers})`)
let dev = await agent(`${PRE}\n\n<task id="${a.id}">\n${a.brief}\n</task>`, { label: `build:${a.id}`, phase: 'Build', model, effort, schema: DEV })
if (!dev) return { id: a.id, status: 'blocked', reason: 'developer agent died', findings: [] }

const review = async (round) => {
  const rs = await parallel(lenses.map(l => () => agent(`You are a reviewer on lazyslice. Repo: ${REPO}. Read ${REPO}/CLAUDE.md and ${REPO}/ARCHITECTURE.md. The task under review is:\n<task id="${a.id}">\n${a.brief}\n</task>\nThe developer reports: ${dev.summary}. Files: ${dev.files.join(', ')}. Checks passed: ${dev.checks_passed}.\nYour lens: ${l.text}\nRun the checks yourself (make check) and do not trust the developer's report. Do not fix anything. Return findings with file and line; severity high means it must not merge.`,
    { label: `review:${l.key}:r${round}`, phase: 'Review', model: 'opus', effort: reviewEffort, schema: FINDINGS })))
  return rs.filter(Boolean).flatMap(r => r.findings)
}

let findings = await review(1)
let blocking = findings.filter(f => f.severity !== 'low')
let round = 0
while (blocking.length && round < 2) {
  round++
  log(`Round ${round}: ${blocking.length} findings to fix`)
  const fixed = await agent(`${PRE}\n\nYou implemented task ${a.id}: ${a.title}. Reviewers found:\n${JSON.stringify(blocking, null, 1)}\nAddress every high and medium finding with targeted edits. If you believe a finding is wrong, say so in concerns with your reasoning rather than silently ignoring it. Re-run the checks.`,
    { label: `fix:${a.id}:r${round}`, phase: 'Fix', model, effort, schema: DEV })
  if (!fixed) break
  dev = fixed
  const re = await agent(`You are the re-verifier on lazyslice. Repo: ${REPO}. These findings were reported on task ${a.id} and the developer says they are fixed:\n${JSON.stringify(blocking, null, 1)}\nDeveloper's concerns: ${JSON.stringify(dev.concerns)}. Check each finding against the current code (git diff, read the files). Run make check. Return only findings that are still open, keeping their severity, plus any new high-severity problem the fix introduced.`,
    { label: `reverify:${a.id}:r${round}`, phase: 'Fix', model: 'opus', effort: reviewEffort, schema: FINDINGS })
  blocking = re ? re.findings.filter(f => f.severity !== 'low') : []
}

if (blocking.length) {
  log(`Task ${a.id} blocked after ${round} fix rounds`)
  return { id: a.id, status: 'blocked', findings: blocking, dev, postmortem: dev.postmortem }
}

const integ = a.integration === true ? ' && make integration' : (typeof a.integration === 'string' ? ` && go test -tags integration -count=1 ${a.integration}` : '')
// A task that touches the regression corpus is verified under make torture as well: T-0137 returned without running it and a red regression sat on main across four landings (T-0172, 2026-09-15).
const torture = (a.paths || []).some(p => p.startsWith('testdata/regressions') || p === 'testdata/') ? ' && make torture' : ''
const verify = a.checks === 'none' ? { passed: true, output: 'checks skipped: documentation task' } : await agent(`Repo: ${REPO}. Run exactly: cd ${REPO} && docker info --format '{{.ServerVersion}}' | grep -q . && make check${integ}${torture}. The docker check comes first because every integration test skips silently when Docker is down and a skipped suite reports ok; if docker info prints nothing, report passed=false with the reason 'Docker is not running' and do not run the rest. Report whether every command exited 0 and paste the last 30 lines of output. Do not change any file.`,
  { label: `verify:${a.id}`, phase: 'Verify', model: 'sonnet', effort: 'low', schema: { type: 'object', required: ['passed', 'output'], properties: { passed: { type: 'boolean' }, output: { type: 'string' } } } })

if (!verify || !verify.passed) {
  return { id: a.id, status: 'blocked', findings: [{ severity: 'high', file: 'Makefile', line: 0, issue: 'independent check run failed', fix: (verify && verify.output) || 'no output' }], dev, postmortem: dev.postmortem }
}

// Commit message: headline with the stage and tracker id, then the developer's changelog bullets as the body (Gareth, 2026-09-16: release notes are generated from these bodies by tools/relnotes.py, so the bullets describe behaviour, not code), then trailers.
const bullets = (dev.changelog && dev.changelog.length ? dev.changelog : [dev.summary]).map(b => '- ' + String(b).replace(/\s+/g, ' ').trim()).join('\n')
const trailers = `Task: ${a.id}\nReview: ${nReviewers} reviewer${nReviewers === 1 ? '' : 's'}, ${round} fix round${round === 1 ? '' : 's'}`
const message = `${(a.stage || 'peripheral')}: ${a.title} (${a.id})\n\n${bullets}\n\n${trailers}\n`
const commit = await agent(`Repo: ${REPO}. Write the following commit message, exactly and completely, to the file ${REPO}/.git/COMMIT_MSG_${a.id} (create it; do not edit it):\n<<<\n${message}>>>\nThen run: cd ${REPO} && git add -A && git commit -F .git/COMMIT_MSG_${a.id} && rm -f .git/COMMIT_MSG_${a.id}, and report the short hash. If there is nothing to commit, say so. Do not change any other file.`,
  { label: `commit:${a.id}`, phase: 'Verify', model: 'haiku', effort: 'low', schema: { type: 'object', required: ['hash'], properties: { hash: { type: 'string' } } } })

return { id: a.id, status: 'merged', hash: commit ? commit.hash : '', files: dev.files, summary: dev.summary, concerns: dev.concerns, findings_low: findings.filter(f => f.severity === 'low'), rounds: round, postmortem: dev.postmortem }
