export const meta = {
  name: 'lazyslice-launch',
  description: 'Phase 6: the GIF, the README as landing page, the launch-post drafts and the issue templates, each through implement.js; the posting itself is the maintainer\'s',
  phases: [
    { title: 'Material', detail: 'docs/BUILD_PLAN.md prompts 6.1 to 6.4 as tasks the orchestrator can run: GIF, README, posts, templates. The docs-site decision (T-0283) and the maintainer\'s paragraph (T-0282) are outside this script.' },
    { title: 'v0.2.0', detail: 'what a stranger hits in the first ten minutes: go install, and a first-name column masked with a full name. The orchestrator cuts mask/v0.1.0 with make tag before this step runs.' },
  ],
}
const REPO = '/Users/gareth/personal_repos/lazyslice'
const IMPL = `${REPO}/.claude/workflows/implement.js`
// args: { step: 'material' | 'v020' | 'polish', from?: index }  from skips merged tasks; a task's brief starts with `python3 tools/tracker.py show T-NNNN` (T-0196: open tasks are GitHub issues, not files)
const step = (args && args.step) || 'material'
const from = (args && args.from) || 0

const MATERIAL = [
  { id: 'T-0065', title: '20-second VHS GIF of the first run on Pagila', model: 'sonnet', effort: 'medium', reviewers: 1, stage: 'peripheral', paths: ['docs/media/', 'Makefile', 'docs/CLAUDE.md', 'CONTRIBUTING.md', '.gitattributes'], checks: 'check',
    brief: `Read the task with python3 tools/tracker.py show T-0065 (its last log entry holds the decisions), CONCEPT.md "What a delighted first run looks like", README.md's quickstart, testdata/README.md's Pagila section and internal/testutil/fixtures.go (how the fixture is loaded). Write docs/media/first-run.tape for charmbracelet/vhs (installed: vhs 0.11.0) that records the real binary (make build first; the tape runs bin/lazyslice) against the Pagila fixture at 1200x700, in under 25 seconds of playback: two disposable postgres:16 containers on unusual host ports named with a suffix nobody else uses, testdata/pagila/pagila-schema.sql and pagila-data.sql loaded into the source with psql, LAZYSLICE_SECRET set from openssl rand in a Set line that is hidden, then one run with --root public.customer -n 200 --no-config and both DSNs given as flags (sslmode=disable), a Sleep on the per-column reasons long enough to read three of them, the plan and the load, then a psql select of three masked customer rows against the target. Nothing typed is a real value or a password other than the throwaway container password. A Makefile target gif builds the binary, starts the containers, runs vhs, removes the containers on every exit path (trap) and refuses if docs/media/first-run.gif is over 4 MB; the GIF is committed once and .gitattributes marks *.gif binary. Run make gif here, paste its output and the GIF's size, and look at the GIF (Read the file) to confirm the reasons frame is readable; docs/CLAUDE.md gains one line for docs/media/. Do not touch README.md: T-0279 places the GIF.` },
  { id: 'T-0279', title: 'README as the landing page', model: 'sonnet', effort: 'high', reviewers: 1, stage: 'peripheral', paths: ['README.md', 'docs/', 'tools/docgen/'], checks: 'check',
    brief: `Read the task with python3 tools/tracker.py show T-0279 (its log corrects one cross-reference), then README.md as it stands, CONCEPT.md, ROADMAP.md's phase 6 and "Versioning and releases", docs/RUNBOOK.md "Cutting a release", and the first screen of the sqlit, lazygit and Bruno READMEs on GitHub (fetch them; say in concerns what each does in its first screen and what you took). Restructure README.md in the order the task's goal gives, keeping every sentence that is true and already there (the quickstart transcript verbatim, the six-sentence safety model, "What a snapshot will not hide", the exit codes, the generated flag table between its markers). The GIF is docs/media/first-run.gif (T-0065 landed it; if it is missing, reference the path and say so in concerns rather than inventing a frame). The install section: brew first, then go install github.com/Liarea/lazyslice/cmd/lazyslice@v0.1.0 (run it with GOMODCACHE and GOPATH pointed at a scratch directory to prove it resolves and the binary prints its version; paste that), then the release archives with the cosign verification pointer. The comparison table: Greenmask, PostgreSQL Anonymizer (pg_anonymizer) and Tonic on time to first snapshot, config required before the first run, databases, masking determinism (same input, same output across runs) and licence; every cell about another tool cites that tool's own documentation as fetched today with the URL in a footnote, a cell you cannot verify says "not stated" rather than a guess, and lazyslice's own cells are true of v0.1.0 as installed from the tap (Postgres only; one command, no config; deterministic under a local key; Apache-2.0). "Why" is three short paragraphs, one per principle in CONCEPT.md's order, each ending with the one thing the tool refuses to do for that principle. "How it decides what is personal data" explains the name rules, the value validators and the corroboration idea in plain words with the reasons output as the evidence, and "how to override it" shows --unmask TABLE.COL=REASON and the lazyslice.yml the run emits. Leave no slot for "why I built this" (T-0282, the maintainer's); end with the ROADMAP link and the licence. make docs-check must pass; a change to which flags the first-run table shows is made in tools/docgen/readme.go, never by hand. Run make check and paste the output.` },
  { id: 'T-0280', title: 'Launch-post drafts and the listings', model: 'sonnet', effort: 'high', reviewers: 1, stage: 'peripheral', paths: ['docs/launch/', 'docs/CLAUDE.md'], checks: 'none',
    brief: `Read the task with python3 tools/tracker.py show T-0280, research/POSTMORTEMS.md, README.md (the landing page T-0279 just landed), CONCEPT.md, ROADMAP.md "Versioning and releases" and the residual list in README "What a snapshot will not hide". Write, under docs/launch/: SHOW_HN.md (a title under 80 characters and a first comment under 200 words that leads with the problem and the Snaplet and Neosync shutdowns, each shutdown linked to a source fetched today and dated), R_POSTGRESQL.md, R_DEVOPS.md, R_WEBDEV.md (each a post for that audience, honest that v0.1.0 is Postgres only and pseudonymises, ending with one specific question to readers), BLOG_POSTMORTEMS.md ("What I learned reading Snaplet's and Neosync's issue trackers": under 900 words, every factual claim linked to research/POSTMORTEMS.md's sources or a page fetched today), and LISTINGS.md (ten awesome-lists or comparison pages where a PR adding lazyslice would be welcome: for each, the URL fetched today, the section, and the exact line the PR would add). Write "the maintainer" wherever a name would go; never the maintainer's name. Post nothing and open nothing anywhere: these are drafts the maintainer edits and posts. docs/CLAUDE.md says docs/launch/ has no assigned purpose: replace that sentence with what it now holds. In your return value's checks_output write "documentation task: no make check" and set checks_passed true.` },
  { id: 'T-0281', title: 'Issue templates that keep personal data out of reports; CHANGELOG.md', model: 'sonnet', effort: 'medium', reviewers: 1, stage: 'peripheral', paths: ['.github/ISSUE_TEMPLATE/', 'CHANGELOG.md', 'CONTRIBUTING.md', 'SECURITY.md'], checks: 'none',
    brief: `Read the task with python3 tools/tracker.py show T-0281, SECURITY.md in full, CONCEPT.md's principles, CONTRIBUTING.md and ROADMAP.md "Versioning and releases". Write GitHub issue forms (YAML, .github/ISSUE_TEMPLATE/): bug_report.yml whose first visible text says never to paste a row, a dump or a screenshot of one and asks for the shape (table and column names and types, the reasons lines, the exit code and its message, the lazyslice version and Postgres major), pii_miss.yml whose body is one paragraph pointing at SECURITY.md's private route and a single checkbox confirming the report contains no real value, feature_request.yml that requires the requester to name which of the three principles the feature serves and what it must refuse to do, and config.yml with blank_issues_enabled false and a contact link to the security advisory page. Templates apply type:bug or type:feature (labels that exist). CHANGELOG.md: five lines saying release notes live on the GitHub releases page, are generated from commit bodies by make relnotes, and that this file is a pointer until v1.0.0 (ROADMAP.md). CONTRIBUTING.md gets one line naming the templates. Prove each YAML parses (python3 -c with a yaml library if present, else ruby -ryaml) and that every label named exists (gh label list); open no issue and change no label. In your return value's checks_output write "documentation task: yaml parsed, labels checked" and set checks_passed true.` },
]

const V020 = [
  { id: 'T-0285', title: 'go install works: go.mod requires the mask module by version; go.work for local development', model: 'sonnet', effort: 'high', reviewers: 1, stage: 'foundations', paths: ['go.mod', 'go.sum', 'go.work', 'go.work.sum', 'mask/go.mod', 'mask/go.sum', 'Makefile', '.github/workflows/ci.yml', 'README.md', 'CONTRIBUTING.md', 'docs/RUNBOOK.md', 'internal/CLAUDE.md', 'mask/CLAUDE.md'], checks: 'check',
    brief: `Read the task with python3 tools/tracker.py show T-0285 (its log says the tag part is already done: mask/v0.1.0 exists on origin, cut by the orchestrator, so the module proxy can serve github.com/Liarea/lazyslice/mask v0.1.0), README.md's Install section (the paragraph that says go install does not work yet), ADR-006 (why mask is its own module), and the Makefile's check target. Do it in this order and prove each step. (1) go.mod: drop the replace directive and require github.com/Liarea/lazyslice/mask v0.1.0; go mod tidy; go.sum gains the module's entries. (2) go.work at the repo root with use ./ and ./mask (commit go.work and go.work.sum), so a change under mask/ is seen by the root module during development without a replace; say in mask/CLAUDE.md and internal/CLAUDE.md how a change to mask/ now reaches the binary (edit, test in the workspace, tag mask/vX.Y.Z with make tag, bump the require) and that go mod tidy runs outside the workspace. (3) Makefile: a target install-proof that builds the root module the way go install does, with GOWORK=off and GOFLAGS=-mod=mod in a temporary GOMODCACHE, so the replace can never come back unnoticed; wire it into make check only if it stays under ten seconds warm, otherwise into a CI job named install-proof on ubuntu that runs go install github.com/Liarea/lazyslice/cmd/lazyslice@$GITHUB_SHA-style (use the checked-out tree: GOWORK=off go build ./cmd/lazyslice from a fresh module cache) and then runs the binary with --version. (4) Prove go install of the tagged v0.1.0 still fails (the tag predates this change; that is expected and the README must say the fix is in the next tag) and that HEAD's tree builds with GOWORK=off from an empty GOMODCACHE and GOPATH in a scratch directory; paste both. (5) README.md: replace the paragraph that says go install does not work with the go install line for the next tag (v0.2.0) and one sentence that v0.1.0's tag predates the fix; CONTRIBUTING.md gets the workspace rule in one line. make check passes; docs/RUNBOOK.md's release section gains two lines: a change under mask/ needs a mask/vX.Y.Z tag and a require bump before the tool's tag, and make tag TAG=mask/vX.Y.Z cuts it. Run make check and paste the output.` },
  { id: 'T-0287', title: 'The person_name masker respects the column role: given name, surname, or full name', model: 'sonnet', effort: 'high', reviewers: 1, stage: 'mask', paths: ['mask/', 'internal/classify/', 'internal/pipeline/', 'internal/transform/', 'internal/emit/', 'internal/verify/', 'testdata/regressions/', 'docs/media/', 'ARCHITECTURE.md', 'THREAT_MODEL.md'], integration: './internal/classify/... ./internal/transform/... ./internal/verify/...',
    brief: `Read the task with python3 tools/tracker.py show T-0287, ADR-006, ARCHITECTURE.md section 5 (the masker contract and the category maskers), mask/CLAUDE.md, the person_name masker in mask/, internal/classify's name rules for person_name (rules.yml and where the Decision is built), and how the phone region reaches the masker (Decision field, transform, emit, verify) since this follows the same route. Work in the go.work workspace T-0285 landed: a change under mask/ is visible to the root module during development, and the orchestrator tags mask/v0.2.0 and bumps the require when this merges, so do not edit go.mod's require. The mask/ change must be additive: the orchestrator lands mask/ as its own commit first (CI builds that commit with GOWORK=off against the published mask v0.1.0 and with the workspace against the new mask/, and both must pass with the root module's code unchanged), tags mask/v0.2.0 on it, then lands the rest with the require bump; so keep every exported mask identifier the root uses today with its current signature and meaning, add the role as a new identifier (for example a new option or constructor), and list in your summary the mask exports you added and confirm none changed. The change: a person_name column carries a role, given, family or full, decided at classify time from the column's name (first, given, forename, fname -> given; last, family, surname, lname -> family; anything else, including name and full_name -> full), carried on the Decision beside the category, written to lazyslice.yml and read back from it, and honoured by the masker: given emits a given name only, family a surname only, full the existing "Given Family". Determinism is unchanged: the same input under the same key and the same role masks the same way, and a role change is a category change for verify's purposes (the residual scan still compares canonical equality; the second net's name validator still scores a single given name or a single surname as a name, check it does). Prove it with mask/'s tests, a classify test for each role, a regression under testdata/regressions/ with first_name, last_name and full_name columns whose expected target rows show one word, one word and two words, and make torture (the regression corpus changed). Re-record the GIF with make gif afterwards and read its last frame back: public.customer.first_name shows one given name. Run make check, the named integration packages and make torture; paste the output.` },
]

if (step === 'v020') {
  phase('v0.2.0')
  const results = []
  for (const t of V020.slice(from)) {
    const r = await workflow({ scriptPath: IMPL }, { ...t, model: t.model || 'sonnet', effort: t.effort || 'medium' })
    results.push(r)
    if (!r || r.status !== 'merged') { log(`Stopped at ${t.id}`); return { results, stopped_at: t.id } }
  }
  return { results }
}

// Launch polish (2026-09-22): four Later tasks re-homed to E6 because a stranger meets each before or at the v0.2.0 tag. T-0288 runs first because its plan line may change what the GIF shows; T-0289 re-records the GIF last.
const POLISH = [
  { id: 'T-0288', title: 'A root table can hold more rows than --take names: find out why, then say so or stop it', model: 'sonnet', effort: 'high', reviewers: 1, stage: 'plan', paths: ['cmd/lazyslice/', 'internal/plan/', 'internal/core/', 'internal/render/', 'internal/event/', 'ARCHITECTURE.md', 'README.md', 'docs/', 'testdata/regressions/'], integration: './internal/plan/... ./internal/core/...',
    brief: `Read the task with python3 tools/tracker.py show T-0288, ARCHITECTURE.md section 3 (the planner and the closure), internal/plan's root selection and closure, the --take flag's help in cmd/lazyslice, and the README's quickstart transcript. Diagnose first, with evidence: load Pagila (internal/testutil's fixture, or make gif's container recipe) and count the payments whose customer_id differs from their rental's customer_id among the 200 lowest-id customers' rentals, and show that the extra roots are exactly those customers; paste the query and its answer. If that is the cause, the behaviour is correct (referential completeness wins over the row count, THREAT_MODEL and ARCHITECTURE both require it): change --take's help to say the root holds at least N rows plus any the closure requires, the root's plan line to say 'N chosen, M pulled in by references' when M > 0 (through internal/event's catalogue if that line is an event: make docs regenerates docs/FLAGS.md, docs/ERRORS.md and README's flag table), ARCHITECTURE.md section 3 to match, and a test that pins the wording on a two-table fixture where a child points back at an unchosen root. If it is not the cause, it is a planner defect: stop, write the diagnosis in your summary and concerns, and add a failing regression under testdata/regressions/ only; do not fix the planner in this task. Run make check and the named integration packages; paste the output.` },
  { id: 'T-0289', title: 'make gif records with a read-only role, probes readiness from the host, and pace.awk fails when it paused nothing', model: 'sonnet', effort: 'medium', reviewers: 1, stage: 'peripheral', paths: ['Makefile', 'docs/media/', 'docs/CLAUDE.md', 'README.md'], checks: 'check',
    brief: `Read the task with python3 tools/tracker.py show T-0289, the gif target in the Makefile, docs/media/first-run.tape, docs/media/pace.awk, and the warning text lazyslice prints for a source role that can write (grep internal/ for 'can write to'). Do the three items it names: (1) make gif creates, in the source container after Pagila loads, the read-only role the warning recommends (LOGIN, no superuser, SELECT on the schema's tables and USAGE on the schema, and whatever else the run needs to read the catalog; find out by running it) and the tape connects as that role, so the recording has no write warning; (2) readiness is probed from the host over the published port (psql or pg_isready with -h 127.0.0.1 -p the host port), not inside the container; (3) pace.awk anchors on the column names it pauses on, not on a two-space marker, and exits non-zero when fewer than three lines matched, and make gif fails when it does. Start the recipe with set -e and set -o pipefail explicitly: this machine's GNU Make 3.81 ignores .SHELLFLAGS (T-0291). Re-record with make gif and read the first and last frames back (ffmpeg or vhs's own screenshot) and paste what they say; the README's embedded frame must still match its transcript. Run make check; paste the output. Do not commit.` },
  { id: 'T-0277', title: 'The cask quarantine hook without the postflight Homebrew deprecates', model: 'sonnet', effort: 'medium', reviewers: 1, stage: 'release', paths: ['.goreleaser.yaml', '.github/workflows/ci.yml', '.github/workflows/release.yml', 'docs/RUNBOOK.md'], checks: 'check',
    brief: `Read the task with python3 tools/tracker.py show T-0277, .goreleaser.yaml's homebrew_casks block, ci.yml's release-config job (it asserts the cask's hook), and docs/RUNBOOK.md's release section. Find out from goreleaser's current documentation and changelog (fetch them; cite the page and the version in your summary, as of today) whether goreleaser can emit a cask hook that is not the deprecated postflight block, and from Homebrew's Cask Cookbook what postflight_steps or its replacement looks like. If goreleaser supports it, change the block and the release-config assertion together; if it does not, say so with the source, and keep the hook but make the release-config assertion and RUNBOOK name the deprecation and the day it bites (every fresh install on macOS stops at Gatekeeper). Either way, prove it with make snapshot and paste dist/homebrew/Casks/lazyslice.rb, and run brew style on that file if brew is present. The installed binary must still lose its quarantine attribute; that is the hook's whole job. Run make check; paste the output. Do not commit.` },
  { id: 'T-0286', title: 'research/POSTMORTEMS.md says what the blog draft now says', model: 'sonnet', effort: 'low', reviewers: 1, stage: 'peripheral', paths: ['research/POSTMORTEMS.md'], checks: 'none',
    brief: `Read the task with python3 tools/tracker.py show T-0286, research/POSTMORTEMS.md lines 90 to 115, and the corresponding sentences in docs/launch/BLOG_POSTMORTEMS.md. Make the two facts in the research document match the blog draft with the same sources: the Hacker News comment is seven weeks after the shutdown (give both dates), and the npm figure is the ratio with the npm downloads API endpoints as sources. Fetch each source today and confirm it says what the sentence claims; if one does not, say so and write what it does say. Change nothing else in the file. Do not commit.` },
]

if (step === 'polish') {
  phase('Polish')
  const results = []
  for (const t of POLISH.slice(from)) {
    const r = await workflow({ scriptPath: IMPL }, { ...t, model: t.model || 'sonnet', effort: t.effort || 'medium' })
    results.push(r)
    if (!r || r.status !== 'merged') { log(`Stopped at ${t.id}`); return { results, stopped_at: t.id } }
  }
  return { results }
}

if (step === 'material') {
  phase('Material')
  const results = []
  for (const t of MATERIAL.slice(from)) {
    const r = await workflow({ scriptPath: IMPL }, { ...t, model: t.model || 'sonnet', effort: t.effort || 'medium' })
    results.push(r)
    if (!r || r.status !== 'merged') { log(`Stopped at ${t.id}`); return { results, stopped_at: t.id } }
  }
  return { results }
}

log(`unknown step '${step}'; this script has three: material, v020, polish`)
return { results: [], stopped_at: null }
