export const meta = {
  name: 'lazyslice-slice',
  description: 'Phase 4: the gate-4 packages from ARCHITECTURE.md section 14, in dependency order, each through implement.js with reviews; stops at the first blocked task',
  phases: [{ title: 'Slice', detail: 'pg, introspect, classify, plan, mask, extract+transform, load, verify, core+emit+render, discover' }],
}
const REPO = '/Users/gareth/personal_repos/lazyslice'
const IMPL = `${REPO}/.claude/workflows/implement.js`
// args: { from: index } to start at a later stage; resume by run id replays finished stages from cache
const start = (args && args.from) || 0

const ARCH = `Implement exactly what ${REPO}/ARCHITECTURE.md specifies for this package; its section numbers are cited below and are the specification. THREAT_MODEL.md names the controls. Where ARCHITECTURE.md is silent, choose the simplest correct behaviour and record the choice in the package's CLAUDE.md under "Decisions made during implementation". Tests use internal/testutil and the fixtures in testdata/.`

const STAGES = [
  { id: 'T-PG', title: 'Source and target connections, target gate, shape allowlist', stage: 'pg', paths: ['internal/pg/', 'internal/dsn/'], integration: true,
    brief: `${ARCH} Package internal/pg per §2 (Source, Target, Reader, Writer) and §11 (marker table, target eligibility gate as specified, including the migration-bookkeeping exemption and the same-cluster rule), plus internal/dsn per §12 (parsing, redacting Ref, loopback and cluster normalisation). Implement the pgx QueryTracer statement-shape allowlist on the source so any non-read statement fails closed (THREAT_MODEL T4 or wherever it is specified). Integration tests: the gate accepts an empty database, accepts a database carrying our marker, refuses a database with rows in a non-exempt table, refuses the source itself, and refuses a target on the same cluster only in the cases §11 says; the tracer rejects a write on the source.` },
  { id: 'T-INTROSPECT', title: 'Introspect stage', stage: 'introspect', paths: ['internal/introspect/'], integration: true,
    brief: `${ARCH} Package internal/introspect per §2 (Schema, Table, Column and the Introspector interface) and the sampling rules (TABLESAMPLE, leaf-partition sampling). Cover every schema, composite and self-referencing FKs, unique constraints, identity and sequence defaults, partitions, enums, arrays, generated columns, quoted mixed-case identifiers, and approximate row counts. Tests on both fixtures assert every introspection trap listed in testdata/README.md.` },
  { id: 'T-CLASSIFY', title: 'Classify stage with rule pack', stage: 'classify', paths: ['internal/classify/'], integration: false,
    brief: `${ARCH} Package internal/classify per §4: embedded YAML rule pack, validators named in §4, English name dictionary, scoring, confidence levels, and reasons.go templates producing the human-readable reason. Pure package, no database access. Tests: on nasty.sql's introspected schema (use a recorded Schema fixture if introspect is not yet wired into the test), email_verified is not flagged, ref is flagged, JSONB, notes, and text[] are flagged; precision and recall on Pagila against a hand-labelled truth table in the test; a 50-name fixture from Discourse, GitLab, and Mastodon schemas with a printed confusion matrix.` },
  { id: 'T-PLAN', title: 'Subset planner', stage: 'plan', paths: ['internal/plan/'], integration: false,
    brief: `${ARCH} Package internal/plan per §3: deterministic FIFO worklist with CHILD_OK/PARENT_ONLY provenance, per-parent-key-per-edge child cap and depth defaults as §3 states, row and memory budgets with the Σ Bytes() estimate, identity fallback chain and ctid refusal (exit 12 path), root default, lookup-table whole copies gated as §3 says, unreadable tables, SCC and topological order, estimates printed in the plan. Pure package. Tests: three-table cycle terminates, self-reference, composite FK, polymorphic pair reported as not followed with the column names, Pagila from customer with take 50 gives the expected table set, and two runs produce byte-identical plans.` },
  { id: 'T-MASK', title: 'Mask module', stage: 'mask', paths: ['mask/'], integration: false,
    brief: `${ARCH} The nested module github.com/Liarea/lazyslice/mask per §5 and ADR-006: key handling, HKDF per category, length-prefixed HMAC-SHA256 canonicalisation, every category generator listed in §5 with Domain() and small-domain reporting, format preservation rules, null and empty handling, and the unique-index collision rule. This module has its own go.mod; you may create or edit mask/go.mod and mask/go.sum only. No dependency on the parent module. Resolve the scaffold review note on mask.Canonical: either return the type tag or document that Constraints.TypeTag supplies it (see tracker/tasks/T-0020*.md Log). Tests: same key same input same output across processes, different key different output, Domain() sizes, format preservation per category, and a collision test under uniqueness pressure.` },
  { id: 'T-EXTRACT', title: 'Extract and transform stages', stage: 'extract', paths: ['internal/extract/', 'internal/transform/'], integration: true,
    brief: `${ARCH} Packages internal/extract (§2 and the chunked typed unnest joins over the run snapshot into chan RowBatch, one table at a time, RowBatch.Last, pooler fallback as specified) and internal/transform (mask per Decision, JSON leaf walking with per-leaf residual digests, canonicalisation, FK propagation, the residual filter). Memory stays bounded: prove it with a test on the 2,000,000-row nasty table under a runtime.MemStats ceiling. Events carry no row values (§7). Tests: determinism across two runs, difference across keys, uniqueness preserved, and every JSON leaf masked.` },
  { id: 'T-LOAD', title: 'Load stage', stage: 'load', paths: ['internal/load/'], integration: true,
    brief: `${ARCH} Package internal/load per §11: ddl/ generating exactly the §11.1 object classes in dependency order and exit 13 otherwise, CopyFrom in plan order, indexes and FKs NOT VALID then validated, setval after commit, ANALYZE, the marker table, and the empty-or-complete property on failure (per-table transactions and the drop path). Integration tests: load a planned Pagila slice into an empty target and into a marked target; kill the load mid-way and assert the target is empty or complete.` },
  { id: 'T-VERIFY', title: 'Verify stage', stage: 'verify', paths: ['internal/verify/'], integration: true,
    brief: `${ARCH} Package internal/verify per §6: FK validation, the residual scan with its capped, split, fail-closed confirmation in a short second transaction, the second net over the whole target, sequence and identity checks, row counts against the plan, and the sample compare. Each check fails with the table and column named and the exit code from §8's table. Integration tests: a correct target passes every check; a target seeded with one unmasked email fails the residual scan and names the column; a target with a broken FK fails FK validation. This includes tracker T-0035, the negative control: plant a known source email literal into a target column the run recorded as masked, run lazyslice verify, and assert exit 9 naming table and column (§6 items 1 to 3).` },
  { id: 'T-CORE', title: 'Core run, emit, render, repo, CLI end to end', stage: 'core', paths: ['internal/core/', 'internal/emit/', 'internal/render/', 'internal/repo/', 'internal/config/', 'cmd/lazyslice/', '.github/workflows/ci.yml'], integration: true,
    brief: `${ARCH} Package internal/core (Run, Request, Report; the only place stages are wired, §1), internal/emit (the §10 lazyslice.yml writer and reader with the tighten-only merge and literal withholding), internal/render (Lines default and NDJSON sinks, §7), internal/repo (.gitignore writes and tracked-file check, §9), internal/config (state dir), and cmd/lazyslice wiring the full §8 flag surface (add a Mode enum to core.Request so introspect, classify, plan, verify, and doctor are distinguishable; fix the --cap and --unmask parser gaps and extend the flag-surface test to assert defaults and types, per tracker/tasks/T-0020*.md Log) so that lazyslice --source URL --target URL --root T --take N runs end to end and emits lazyslice.yml, and a second run from that yml reproduces the target. Then run make integration: all six invariants in internal/invariants must pass on both fixtures. Remove the continue-on-error line from the integration job in .github/workflows/ci.yml so the suite blocks merges from now on. Do not stop until they do or you have a specific blocker named in your return.` },
  { id: 'T-DISCOVER', title: 'Discovery rungs 0 to 3 and the first-run ladder', stage: 'discover', paths: ['internal/discover/', 'cmd/lazyslice/'], integration: true,
    brief: `${ARCH} Package internal/discover per §9 and docs/adr/008-first-run.md: rungs 0 to 3 of the ladder, candidate verification and de-duplication, dockerctx/ resolving the Docker endpoint in the order ADR-008 states (DOCKER_HOST, current context in ~/.docker/config.json and its meta, default socket paths), compose and .env as naming sources only, and the single blocking question with its default. Provisioning (--create-target) and rung 4 are phase 5; leave a clear not-implemented path. Wire lazyslice with no arguments in cmd/lazyslice. Tests: discovery against a real container from testutil; against a temp dir with .env and compose files; the question ladder in headless mode asks nothing and exits with the §8 code.` },
]

const out = []
for (let i = start; i < STAGES.length; i++) {
  const s = STAGES[i]
  log(`Stage ${i + 1}/${STAGES.length}: ${s.title}`)
  const r = await workflow({ scriptPath: IMPL }, { ...s, model: 'opus', effort: 'high' })
  out.push(r)
  if (!r || r.status !== 'merged') { log(`Stopped at ${s.id}: ${r ? r.status : 'no result'}`); return { results: out, stopped_at: i } }
}
return { results: out, stopped_at: null }
