export const meta = {
  name: 'lazysnap-slice',
  description: 'Phase 4: the six pipeline stages in order, then first-run and TUI, each through implement.js with reviews; stops at the first blocked task',
  phases: [{ title: 'Slice', detail: 'introspect, classify, plan, extract+transform, load+safety, first-run+TUI' }],
}
const REPO = '/Users/gareth/personal_repos/lazysnap'
const IMPL = `${REPO}/.claude/workflows/implement.js`
// args: { from: 0-5 } to resume from a stage index
const start = (args && args.from) || 0

const STAGES = [
  { id: 'T-INTROSPECT', title: 'Introspect stage for Postgres', stage: 'introspect', paths: ['internal/introspect/', 'cmd/lazysnap/'], integration: false,
    brief: `Implement internal/introspect for PostgreSQL per ARCHITECTURE.md: tables across all schemas (not only public), columns with types, primary keys, foreign keys including composite and self-referencing, unique constraints, sequences and identity columns, partitions, enums, approximate row counts from pg_class, and a 200-row sample per table via TABLESAMPLE where available with a fallback for small tables. Output the Schema type from ARCHITECTURE.md. Wire the introspect subcommand with --json. Tests use internal/testutil and both fixtures and assert every trap in testdata/README.md that concerns introspection is represented (self-reference, cycle, composite keys, partitions, enum, array, generated column, identity starts, non-public schema, quoted identifier).` },
  { id: 'T-CLASSIFY', title: 'Classify stage', stage: 'classify', paths: ['internal/classify/', 'cmd/lazysnap/'], integration: false,
    brief: `Implement internal/classify per ARCHITECTURE.md and docs/adr/006-extension-model.md: column-name heuristics with weights, value sampling with validators (RFC 5322 email, E.164 phone, Luhn, IPv4/6, ISO dates for DOB), and a free-text and JSON catch-all. Output per column: category, confidence, and a human-readable reason like "column name contains email; 97% of samples matched". Rule: anything at or above the "possible" confidence is masked unless the user opts out per column. Wire the classify subcommand printing a table sorted by confidence and --json. Tests: on nasty.sql, email_verified must not be flagged, ref must be flagged, the JSONB, notes, and text[] columns must be flagged; report precision and recall on Pagila against a hand-labelled truth table you write in the test; add a fixture of 50 real column names from open-source schemas (Discourse, GitLab, Mastodon) with expected categories and print the confusion matrix in test output.` },
  { id: 'T-PLAN', title: 'Subset planner', stage: 'plan', paths: ['internal/plan/', 'cmd/lazysnap/'], integration: false,
    brief: `Implement internal/plan per the planner algorithm in ARCHITECTURE.md. Given Schema, a root table, and N, produce an ordered Plan of (table, predicate) steps: parents to completeness, then children with a per-table cap defaulting to 10x N, cycles handled by marking constraints for deferral, small lookup tables (under 1000 rows, no outgoing FKs) copied whole, unreachable tables excluded and listed. Every step carries an estimated row count. Wire the plan subcommand printing the plan. Tests on nasty.sql must show the three-table cycle handled without infinite loop, the self-reference handled, composite FKs followed, and the polymorphic association reported as "not followed: no constraint" with a hint naming the columns. Test on Pagila from customer with N=50.` },
  { id: 'T-EXTRACT', title: 'Extract and transform stages', stage: 'extract', paths: ['internal/extract/', 'internal/transform/', 'cmd/lazysnap/'], integration: false,
    brief: `Implement internal/extract and internal/transform per ARCHITECTURE.md. Extract streams each plan step with COPY TO (pgx CopyTo) or a server-side cursor, never holding a full table in memory; prove it with a test on the 2,000,000 row nasty table under a memory ceiling measured with runtime.MemStats. Transform applies maskers per the deterministic HMAC scheme row by row, preserves format (email domain shape, phone country code), handles nulls and empties, guarantees unique constraints on masked columns survive, and emits progress events on the event channel defined in ARCHITECTURE.md. Implement every v1 masker category listed in ARCHITECTURE.md. Tests: determinism across two runs with the same secret, difference with a different secret, uniqueness under collision pressure, and format preservation per category.` },
  { id: 'T-LOAD', title: 'Load stage, safety rails, end to end', stage: 'load', paths: ['internal/load/', 'internal/run/', 'internal/config/', 'cmd/lazysnap/'], integration: true,
    brief: `Implement internal/load for PostgreSQL: create schema objects in the target if missing (types, tables, constraints, in dependency order), load with COPY FROM in plan order with constraints deferred, reset sequences and identities to max+1, verify FK integrity at the end, and on any failure leave the target either empty or complete (drop what was created). Then implement every control marked v1-blocking in THREAT_MODEL.md, at minimum: refuse a target whose host and database match the source or whose name matches a production pattern unless --i-know-this-is-not-prod; refuse a target with existing data unless --replace; never log or emit secrets; add snapshots/ to .gitignore on first run. Implement internal/run wiring the six stages into one run and internal/config emitting lazysnap.yml (the exact shape in ARCHITECTURE.md) at the end of every run and accepting it as input. Wire the top-level command: lazysnap --from URL --to URL --root T --take N must run end to end. Run make integration: all six invariants must now pass on both fixtures. Do not stop until they do or you have a specific blocker to report.` },
  { id: 'T-FIRSTRUN', title: 'Zero-config first run and thin TUI', stage: 'tui', paths: ['internal/discover/', 'internal/tui/', 'cmd/lazysnap/'], integration: true,
    brief: `Implement the first-run experience from research/SQLIT_STUDY.md and docs/adr/004-config-model.md. internal/discover: detect PostgreSQL containers via the Docker socket, read DATABASE_URL from .env and docker-compose.yml, and rank candidates as source and target. With no arguments: if exactly one plausible source and one plausible target exist, ask the single question (root table, default: the table with the most incoming foreign keys) and run. internal/tui with the framework in docs/adr/002-tui.md as a thin layer: a table picker showing the classifier's reasons, a plan preview, and a live progress view fed by the event channel; every action shows its keybinding; no feature may exist in the TUI that is not reachable by a flag. Tests: discover against a real container from testutil and against a temp dir with .env and compose files; TUI model tests with the framework's test utilities. make integration must still pass.` },
]

const out = []
for (let i = start; i < STAGES.length; i++) {
  const s = STAGES[i]
  log(`Stage ${i + 1}/${STAGES.length}: ${s.title}`)
  const r = await workflow({ scriptPath: IMPL }, { ...s, model: 'opus', effort: 'high' })
  out.push(r)
  if (!r || r.status !== 'merged') { log(`Stopped at ${s.id}: ${r ? r.status : 'no result'}`); return { results: out, stopped_at: i } }
}
return { results: out, stopped_at: null }
