// SPDX-License-Identifier: Apache-2.0

//go:build integration && torture

package invariants

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/jackc/pgx/v5"
)

// The ten schemas of testdata/torture/, and the runs `make torture` makes
// against them.
//
// They are here rather than in a package of their own because everything the
// suite needs is here: the binary under test is built once (harness_test.go),
// the two containers are started the same way, and the assertions are the same
// helpers I1, I2, I4 and I6 use against pagila and nasty. A torture suite that
// re-implemented "every foreign key in the target resolves" would be asserting
// something subtly different from the invariant of the same name, which is the
// one thing it must not do.
//
// The build tag is `integration && torture`, so `make integration` does not run
// them: ten real schemas on two containers each is a different unit of work from
// the six invariants, and docs/TORTURE.md records the times. `make torture` is
// the target.

// tortureSchema is one schema under testdata/torture/ and the run made against
// it.
type tortureSchema struct {
	// dir is the directory under testdata/torture/.
	dir string

	// image, when set, is the container image both databases run. Only
	// discourse sets it: its schema needs pgvector.
	image string

	// root is the table the snapshot slices from, and it is not a free choice.
	// The rule, applied to every schema and checked at run time by
	// assertRootIsMostConnected, is: the table with the most foreign-key edges
	// incident to it, counting each declared constraint once, in either
	// direction; ties broken by incoming edges, then by row count, then by name.
	//
	// Discourse is the schema that needs all four terms. `public.users`,
	// `public.uploads` and `public.ad_plugin_house_ads` each have exactly four
	// incoming edges and no outgoing ones, and the fixture's row counts
	// (300/150/20) are what separate them.
	root string
	take int

	// flags are what a first run refused and told the operator to pass, in the
	// order the refusals arrived. Every one of them is in docs/TORTURE.md with
	// the reason it is there.
	flags []string

	// wantExit is the exit code the run must produce, and wantCode the event
	// code that must be in the message. Nine of the ten are 0; mastodon is the
	// tenth, and what it must fail with is as much a part of the suite as the
	// nine successes are.
	wantExit int
	wantCode string

	// mustHoldRows names tables the slice has to reach, each holding at least
	// one row in the target; mustBeSubset the ones it must hold fewer rows of
	// than the source. Same meaning, and same reason for the split, as the two
	// fields of fixture (harness_test.go).
	mustHoldRows []string
	mustBeSubset []string

	// countedRoot and countedTake are I6's slice: a root no selected row can
	// reach as a parent, so that "the root holds exactly --take rows" is true.
	// Empty means the schema contributes no I6 case, which is the honest answer
	// for a schema whose most-connected table is reachable from its own
	// children.
	countedRoot string
	countedTake int
}

// tortureSchemas is the catalogue. Order is the order docs/TORTURE.md lists
// them: smallest schema first, because that is the order a person debugging a
// change wants them to fail in.
var tortureSchemas = []tortureSchema{
	{
		dir:  "rails-activestorage",
		root: "public.active_storage_blobs",
		take: 100,
		flags: []string{
			// An ActiveStorage key is the opaque path a blob is stored under,
			// generated by Rails and meaningless outside the store. It is under
			// a unique index and classifies as credential, so `credential_unique`
			// would mask it now; the flag stays because its reason is the other
			// kind, a claim that the column is not personal data, which no
			// masker changes.
			"--unmask", "public.active_storage_blobs.key=an opaque ActiveStorage storage key, not personal data",
		},
		mustHoldRows: []string{"public.active_storage_attachments", "public.active_storage_variant_records"},
		mustBeSubset: []string{"public.active_storage_attachments", "public.active_storage_variant_records"},
		countedRoot:  "public.active_storage_blobs",
		countedTake:  100,
	},
	{
		dir:  "django",
		root: "public.auth_user",
		take: 100,
		flags: []string{
			// `varchar(150) UNIQUE`, decided person_name, and a group's name is
			// not a person's. It is the one flag this schema needs.
			"--unmask", "public.auth_group.name=a permission group's name, not a person's",
		},
		mustHoldRows: []string{"public.auth_user_groups", "public.django_admin_log", "public.auth_group"},
		// Only django_admin_log. auth_user_groups is a join table and every one
		// of its rows is reached: --take 100 of 300 users pulls 100 users, their
		// group memberships, the groups those name as parents — and then every
		// *other* membership of those groups, because auth_user_groups is a
		// child of auth_group too. That is what §3 says to do, at every value of
		// --take, so requiring a proper subset of it would fail a correct run.
		mustBeSubset: []string{"public.django_admin_log"},
		countedRoot:  "public.auth_user",
		countedTake:  100,
	},
	{
		dir:  "supabase-auth",
		root: "auth.users",
		take: 100,
		// This schema carried six more flags until T-0112: `refresh_tokens.token`
		// and five of `users`'s token columns, every one of them under a unique
		// index and classified credential, none of which could be masked at all
		// while `CatCredential`'s only generator was the fixed literal (T-0098).
		// `credential_unique` (mask/gen_credential.go) escalates them now, so the
		// six are gone and the six columns are masked rather than copied. An
		// authentication schema is nothing but unique credentials, which is why
		// this schema was the clearest evidence for that defect and is now the
		// clearest evidence for its fix.
		//
		// The one that remains is a different finding and its reason says so. `mfa_factors`
		// carries `CREATE UNIQUE INDEX mfa_factors_user_friendly_name_unique ...
		// (friendly_name, user_id) WHERE (TRIM(BOTH FROM friendly_name) <> '')`,
		// which `raiseCompositeUnique` now judges — a masked column and a `user_id`
		// that repeats is exactly the shape that dies in the loader. Here it cannot:
		// `friendly_name` is nullable, the generator does not fill nullable columns,
		// so every row is NULL, `trim(NULL) <> ''` is NULL and the partial index
		// admits no row at all. `d_required` is computed over the whole table's
		// planned row count regardless, which is the over-estimate
		// internal/classify/classify.go argues for and ADR-011 clause (b) states
		// as the rule (ARCHITECTURE.md §5); the flag copies a column of NULLs.
		flags: []string{
			"--unmask", "auth.mfa_factors.friendly_name=NULL in every row here, so the partial unique index over it admits none; d_required is still computed over the whole table (ADR-011 clause (b))",
		},
		mustHoldRows: []string{"auth.identities", "auth.sessions", "auth.mfa_factors"},
		mustBeSubset: []string{"auth.identities", "auth.sessions", "auth.mfa_factors"},
		countedRoot:  "auth.users",
		countedTake:  100,
	},
	{
		dir:  "plausible",
		root: "public.sites",
		take: 100,
		flags: []string{
			// Empty in the fixture and keyless upstream: no primary key, no
			// unique index over NOT NULL columns.
			"--skip-table", "public.email_verification_codes",
			// A site's domain is the site's, not a person's, and it is the
			// natural key the whole schema hangs off.
			"--unmask", "public.sites.domain=the site's own hostname, the schema's natural key",
		},
		mustHoldRows: []string{"public.site_memberships", "public.users", "public.goals", "public.funnels"},
		mustBeSubset: []string{"public.site_memberships", "public.goals", "public.funnels"},
		countedRoot:  "public.sites",
		countedTake:  100,
	},
	{
		dir:  "metabase",
		root: "public.core_user",
		take: 100,
		flags: []string{
			"--skip-table", "public.model_index_value",
			"--skip-table", "public.table_privileges",
			"--unmask", "public.core_session.id=an opaque session id, regenerated on every login",
			"--unmask", "public.permissions_group.name=a permissions group's name, not a person's",
		},
		mustHoldRows: []string{"public.login_history", "public.report_card", "public.metabase_database", "public.core_session"},
		mustBeSubset: []string{"public.login_history", "public.report_card"},
		countedRoot:  "public.core_user",
		countedTake:  100,
	},
	{
		dir:  "calcom",
		root: "public.users",
		take: 100,
		flags: []string{
			// A booking's `uid` is the opaque reference in its public URL —
			// Cal.com generates it, and it is what an attendee pastes to
			// reschedule. Under a unique index and classified credential, so
			// `credential_unique` would mask it now; this flag stays because its
			// reason is the other kind, a claim that the column is not personal
			// data, and that claim is unaffected by which masker exists.
			//
			// `public."Booking".oneTimePassword` was the second flag until T-0112:
			// NULL in every row of the fixture and refused anyway, because §5's
			// rule is about the column's unique index and its row count and knows
			// nothing about how many of those rows are NULL. `credential_unique`
			// escalates it, so the refusal is gone with the flag (T-0098).
			"--unmask", `public."Booking".uid=the booking's public URL reference, generated by Cal.com`,
		},
		mustHoldRows: []string{`public.Booking`, `public.Attendee`, `public.EventType`, `public.Membership`},
		mustBeSubset: []string{`public.Booking`, `public.Attendee`, `public.EventType`},
		countedRoot:  "public.users",
		countedTake:  100,
	},
	{
		dir:  "mastodon",
		root: "public.accounts",
		take: 100,
		flags: []string{
			"--unmask", "public.accounts.uri=the account's federation URI, the public address the account is known by",
			"--unmask", "public.session_activations.session_id=an opaque session id",
			"--unmask", "public.statuses.uri=the status's federation URI",
			// `public.users.confirmation_token` and `public.users.reset_password_token`
			// were the fourth and fifth flags until T-0112: unique credential
			// columns no masker could fill (T-0098). `credential_unique` fills
			// them now.
			//
			// The three that remain were T-0100, not T-0098: all three are
			// values `textsig.LooksSecret` read as credentials, which under a
			// unique index meant the fixed literal and a refusal. **T-0100 is
			// fixed** (T-HARD-B): a URL is no longer a secret to that validator
			// and `internal/classify` asks `textsig.ValidURL` ahead of it, so
			// the two federation URIs are `online_id` — a category whose
			// generator has a domain a unique column can use — and only
			// `session_id` is still read as a credential. Whether either URI
			// flag is still *needed* is not something this run can say: mastodon
			// refuses at exit 13 before the plan, so no masker is ever chosen
			// here (the same reason T-0112 could remove the other two without
			// measuring anything). They stay, and the count stays honest,
			// until the exit-13 refusal is something a run can get past.
		},
		// The tenth. ARCHITECTURE.md §11.1 does not recreate functions, and
		// Mastodon's primary keys default to `timestamp_id('accounts')`, which
		// the application installs from lib/mastodon/snowflake.rb. There is
		// deliberately no flag that drops the default and carries on, so this
		// run cannot succeed and is not expected to: what is asserted is that it
		// fails at exit 13 under its own code, naming the table, the column and
		// the function. Before T-TORTURE it exited 1 as run.refused.internal
		// with "run with --debug"
		// (testdata/regressions/002-function-default-refusal-uncoded.sql).
		wantExit: 13,
		wantCode: "target.schema.not_recreatable.function",
	},
	{
		dir:  "gitlab",
		root: "public.namespaces",
		take: 100,
		// Eleven flags until T-0112, of which eight were one defect: the invite,
		// runner, reset-password, confirmation, unlock and static-object token
		// columns are all unique credentials, and `CatCredential`'s only
		// generator was the fixed literal (T-0098). `credential_unique` masks
		// them now and the eight flags are gone. GitLab was the schema the
		// headline sentence quoted — "a stranger types eleven `--unmask` flags
		// before it runs" — and it is three.
		flags: []string{
			"--unmask", "public.namespaces.name=a namespace's name is its path, the schema's natural key",
			"--unmask", "public.organizations.path=an organisation's URL path, not personal data",
			"--unmask", "public.projects.name=a project's name, not a person's",
		},
		mustHoldRows: []string{"public.projects", "public.members", "public.users", "public.issues"},
		mustBeSubset: []string{"public.issues"},
	},
	{
		dir:  "odoo",
		root: "public.res_users",
		take: 100,
		flags: []string{
			// A country's international dialling code is an integer, and
			// `phone` cannot be written into one: E.164 does not fit.
			"--unmask", "public.res_country.phone_code=a country's international dialling code, not a phone number",
			"--unmask", "public.res_company.name=the operator's own company name, not a person's",
			"--unmask", "public.res_currency.name=a currency code, not a person's name",
		},
		mustHoldRows: []string{"public.res_partner", "public.res_users_log", "public.mail_message"},
		mustBeSubset: []string{"public.res_users_log"},
	},
	{
		dir:   "discourse",
		image: "pgvector/pgvector:pg16",
		root:  "public.users",
		take:  100,
		flags: []string{
			// public.poll_votes has no primary key and no unique index over
			// NOT NULL columns, so §3.4's ladder runs out. It is the one table
			// in the set that --key rescues rather than --skip-table: it is the
			// only edge in Discourse that carries a person two tables deep, and
			// skipping it would leave the slice with nothing to reach.
			"--key", "public.poll_votes=poll_id,poll_option_id,user_id",
			"--unmask", "public.user_chat_channel_memberships.mobile_notification_level=a notification level, not a phone number",
			"--skip-table", "public.inferred_concept_posts",
			"--skip-table", "public.inferred_concept_topics",
			"--skip-table", "public.post_replies",
			"--skip-table", "public.topic_views",
			"--unmask", "public.ad_plugin_house_ads.name=a house ad's name, not a person's",
			"--unmask", "public.poll_options.digest=a content digest of the option's HTML",
			// `public.user_security_keys.credential_id` was the ninth flag until
			// T-0112: a unique credential column no masker could fill (T-0098).
			// `credential_unique` fills it now.
		},
		mustHoldRows: []string{"public.poll_votes", "public.user_security_keys", "public.reviewable_notes", "public.ad_plugin_impressions"},
		// reviewable_notes is not in mustBeSubset: it is a child of both
		// public.users and public.reviewables, and the reviewables a selected
		// person created pull back every note on them, whoever wrote it.
		mustBeSubset: []string{"public.poll_votes", "public.user_security_keys"},
		countedRoot:  "public.users",
		countedTake:  100,
	},
}

// tortureRoot is the absolute path of testdata/torture.
func tortureRoot() (string, error) {
	root, err := repoRoot()
	if err != nil {
		return "", err
	}
	return filepath.Join(root, "testdata", "torture"), nil
}

// loadTorture is the fixture loader for one schema: the upstream schema, the
// shared generator, the schema's own generator, and the cleanup that takes the
// generator back out again. Four files, in that order, and testdata/torture's
// README.md is the contract.
func (s tortureSchema) load(ctx context.Context, connURL string) error {
	dir, err := tortureRoot()
	if err != nil {
		return err
	}
	for _, path := range []string{
		filepath.Join(dir, s.dir, "schema.sql"),
		filepath.Join(dir, "_common", "fill.sql"),
		filepath.Join(dir, s.dir, "generate.sql"),
		filepath.Join(dir, "_common", "cleanup.sql"),
	} {
		if err := runScript(ctx, connURL, path); err != nil {
			return err
		}
	}
	return nil
}

// runScript sends one .sql file to the database as a single simple query.
//
// It is not psql and it does not need to be: nothing under testdata/torture/ has
// a `COPY ... FROM stdin` block or a backslash command — the schemas are
// pg_dump's `--schema-only` output with its two `\restrict` lines removed, and
// the generators are ordinary statements — so the server's own statement
// splitting is the whole of what is required. testdata/torture/README.md carries
// that as a rule, and a file that broke it would fail here with the server's own
// syntax error and the file's name.
//
// pgx sends a query with no arguments through the simple protocol, which is what
// makes a multi-statement script work at all.
func runScript(ctx context.Context, connURL, path string) error {
	text, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("torture: reading %s: %w", filepath.Base(path), err)
	}
	if strings.TrimSpace(string(text)) == "" {
		return nil
	}
	conn, err := pgx.Connect(ctx, connURL)
	if err != nil {
		return fmt.Errorf("torture: connecting to load %s: %w", filepath.Base(path), err)
	}
	defer func() { _ = conn.Close(context.WithoutCancel(ctx)) }()

	if _, err := conn.Exec(ctx, string(text)); err != nil {
		return fmt.Errorf("torture: %s: %w", filepath.Base(path), err)
	}
	return nil
}
