-- root:   public.reg6_owner
-- take:   20
-- expect: ok
-- found:  metabase
-- why:    setval named the source's sequence for an identity column the target renames
--
-- Metabase renamed `group_table_access_policy` to `sandboxes` and, as Postgres
-- does, left the sequence behind under its old name: the catalog still says
--
--     group_table_access_policy_id_seq  OWNED BY (deptype 'i')  sandboxes
--
-- ARCHITECTURE.md §11.1 recreates an identity column as
-- `GENERATED ... AS IDENTITY`, and the sequence that comes with it is the
-- server's to name — so the target's is `sandboxes_id_seq`. `ddl.sequences`
-- knows this and skips an identity column's sequence when it emits `CREATE
-- SEQUENCE`. `ddl.Setvals` did not: it walked the same `Table.Sequences` and
-- wrote the source's name into the literal, so the last statement of the load
-- was
--
--     SELECT pg_catalog.setval('"public"."group_table_access_policy_id_seq"', ...)
--
-- against a target that has no such relation:
--
--     lazyslice: relation "public.group_table_access_policy_id_seq"
--       does not exist (SQLSTATE 42P01)
--
-- — after every table had been copied, which is exactly the shape THREAT_MODEL.md
-- T8 and the strict-NULL setval form exist to avoid.
--
-- The fix is to ask the target for the name instead of asserting the source's:
-- for an identity column the literal becomes
-- `pg_get_serial_sequence('public.reg6_thing', 'id')`, which resolves to
-- whatever the target's own `GENERATED AS IDENTITY` created. A non-identity
-- sequence keeps the source's name, because that is the name `CREATE SEQUENCE`
-- gave it in the target two steps earlier.
--
-- The fixture reproduces the rename by doing what Metabase did: create the
-- table under one name, rename it, and leave the identity sequence's name alone.
-- `reg6_plain` is the non-identity half — a `serial` whose sequence is created
-- by name — so the fix cannot be "stop resetting sequences".

CREATE TABLE public.reg6_owner (
    id    integer PRIMARY KEY,
    email text NOT NULL
);

CREATE TABLE public.reg6_old_name (
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id integer NOT NULL REFERENCES public.reg6_owner (id),
    label    text NOT NULL
);

-- The rename. The identity sequence keeps the old name, as Postgres leaves it.
ALTER TABLE public.reg6_old_name RENAME TO reg6_thing;

CREATE TABLE public.reg6_plain (
    id       serial PRIMARY KEY,
    owner_id integer NOT NULL REFERENCES public.reg6_owner (id),
    note     text NOT NULL
);

INSERT INTO public.reg6_owner (id, email)
SELECT i, 'owner' || i || '@regression.test' FROM generate_series(1, 60) AS g(i);

INSERT INTO public.reg6_thing (owner_id, label)
SELECT i, 'thing ' || i FROM generate_series(1, 60) AS g(i);

INSERT INTO public.reg6_plain (owner_id, note)
SELECT i, 'note ' || i FROM generate_series(1, 60) AS g(i);
