// SPDX-License-Identifier: Apache-2.0

// Code generated by tools/names; DO NOT EDIT.

// censusGivenWords and censusSurnameWords are the U.S. Census Bureau's 2020
// Census top-1000 given names and surnames (tools/names/README.md,
// THIRD_PARTY_NOTICES.md), lowercased: 958 given names -- the union of the
// top-ranked male and top-ranked female first names, deduped -- and 1000
// surnames. Regenerate with `make names` (go run ./tools/names); never edit by
// hand.
//
// Nothing in mask reads either constant yet: this task (T-0303) only fetches,
// extracts and generates the corpus, and mask/CLAUDE.md says why no masker is
// wired to it. T-0304 does that, after T-0302 lands.
package mask

const (
	censusGivenWords = `aaliyah aaron abby abel abigail abraham adam addison adrian adriana adrienne aidan aiden aimee
alan alana albert alberto alec alejandra alejandro alex alexa alexander alexandra alexandria
alexis alfonso alfred alfredo ali alice alicia alisha alison allan allen allison alma alvin
alyssa amanda amber amelia amy ana andre andrea andres andrew andy angel angela angelica
angelina angelo angie anita ann anna anne annette annie anthony antonio april aria ariana
arianna ariel arlene armando arnold arthur arturo asher ashley ashton aubrey audrey aurora
austin autumn ava avery ayden bailey barbara barry beatrice beatriz becky belinda bella ben
benjamin bernard bertha beth bethany betty beverly bianca bill billie billy blake blanca bob
bobbie bobby bonnie brad braden bradley brady brandi brandon brandy braxton brayden breanna
brenda brendan brent brett brian briana brianna bridget brittany brittney brody brooke brooklyn
bruce bryan bryce bryson byron caden caitlin caleb calvin camden cameron camila camille candace
candice carl carla carlos carly carmen carol carole carolina caroline carolyn carrie carson
carter casey cassandra cassidy catherine cathy cecilia celeste celia cesar chad chance charlene
charles charlie charlotte chase chelsea cheryl cheyenne chloe chris christian christina
christine christopher christy cindy claire clara clarence claudia clayton clifford clinton clyde
cody colby cole colin colleen collin colton conner connie connor constance cooper cora corey
cory courtney craig cristian cristina crystal curtis cynthia daisy dakota dale dallas dalton
damian damien damon dan dana daniel daniela danielle danny darlene darrell darren darryl daryl
dave david dawn dean deanna debbie deborah debra delores denise dennis derek derrick desiree
destiny devin devon diana diane dianne diego dillon dolores dominic dominick dominique don
donald donna donovan dora doris dorothy doug douglas drew duane dustin dwayne dwight dylan earl
easton eddie edgar edith edna eduardo edward edwin eileen elaine eleanor elena eli elias elijah
elisa elise elizabeth ella ellen ellie elliot elliott elsa emerson emilio emily emma emmanuel
enrique eric erica erick erik erika erin ernest ernesto esmeralda esther ethan eugene eva evan
evelyn everett ezra faith fatima felicia felipe felix fernando florence floyd frances francis
francisco frank franklin fred frederick gabriel gabriela gabriella gabrielle gage gail garrett
gary gavin gayle gene genesis genevieve geoffrey george georgia gerald geraldine gerardo gianna
gilbert gina giovanni gladys glen glenda glenn gloria gordon grace gracie graham grant grayson
greg gregory guadalupe guillermo gustavo guy gwendolyn hailey haley hannah harley harold harper
harrison harry harvey hayden hazel heather hector heidi helen henry herbert hilda holly hope
howard hudson hugo hunter ian irene iris irma isaac isabel isabella isabelle isaiah ismael
israel ivan ivy jace jack jackie jackson jacob jacqueline jacquelyn jada jade jaden jaime jake
james jamie jan jane janelle janet janice jared jasmine jason javier jaxon jaxson jay jayden
jean jeanette jeanne jeff jeffery jeffrey jenna jennifer jenny jeremiah jeremy jerome jerry
jesse jessica jessie jesus jill jillian jim jimmie jimmy jo joan joann joanna joanne jocelyn
jodi jody joe joel joey johanna john johnathan johnnie johnny jon jonah jonathan jonathon jordan
jorge jose joseph josephine josh joshua josiah josue joy joyce juan juana juanita judith judy
julia julian juliana julie julio june justin kaden kai kaitlin kaitlyn kaleb kara karen kari
karina karl karla kate katelyn katherine kathleen kathryn kathy katie katrina kay kayden kayla
kaylee keith kelli kelly kelsey kelvin ken kendall kendra kennedy kenneth kenny kent kerry kevin
kim kimberly kirk kirsten krista kristen kristi kristin kristina kristine kristopher kristy
krystal kurt kyle kylie lana lance landon larry laura lauren laurie lawrence layla leah lee lena
leo leon leonard leonardo leroy leslie lester leticia levi lewis liam liliana lillian lilly lily
lincoln linda lindsay lindsey lisa lloyd logan lois lonnie lorena lorenzo loretta lori lorraine
louis louise lucas lucia lucille lucy luis luke luz lydia lynda lynn lynne mackenzie madeline
madelyn madison maggie makayla mallory manuel marc marcia marco marcos marcus margaret margarita
maria mariah marian mariana marianne maribel marie marilyn marina mario marion marisa marisol
marissa marjorie mark marlene marsha marshall marta martha martin marvin mary maryann mason
mateo mathew matt matthew maureen maurice max maxwell maya mayra mckenzie megan meghan melanie
melinda melissa melody melvin mercedes meredith mia micah michael micheal michele michelle
miguel mikayla mike mildred miles milton miranda miriam misty mitchell mohamed mohammad mohammed
molly monica monique morgan mya nadia nancy naomi natalia natalie natasha nathan nathaniel neil
nelson nevaeh nicholas nichole nick nicolas nicole nina noah noel nolan nora norma norman olga
oliver olivia omar orlando oscar owen pablo paige pamela parker patricia patrick patsy paul
paula pauline payton pedro peggy penelope penny perry peter peyton philip phillip phyllis
preston priscilla quinn rachael rachel rafael ralph ramon ramona randall randy raquel raul ray
raymond reagan rebecca rebekah reese regina reginald rene renee rhonda ricardo richard rick
ricky riley rita robert roberta roberto robin robyn rodney rodolfo rodrigo rogelio roger roland
roman ron ronald ronnie rosa rose rosemarie rosemary ross roxanne roy ruben ruby russell ruth
ryan ryder rylee sabrina sadie sally salvador sam samantha samuel sandra sandy santiago sara
sarah saul savannah sawyer scarlett scott sean sebastian sergio seth shane shannon sharon shaun
shawn sheila shelby shelley shelly sheri sherri sherry sheryl shirley sidney sierra silvia simon
skylar skyler sofia son sonia sonya sophia sophie spencer stacey stacy stanley stella stephanie
stephen steve steven stuart sue summer susan suzanne sydney sylvia tabitha tamara tammy tanner
tanya tara taylor ted teresa terrance terrence terri terry thelma theodore theresa thomas
tiffany tim timothy tina todd tom tomas tommy toni tony tonya tracey tracy travis trent trenton
trevor trinity tristan troy ty tyler tyrone valentina valeria valerie vanessa vera vernon
veronica vicki vickie vicky victor victoria vincent violet virginia vivian wade walter wanda
warren wayne wendy wesley weston whitney will william willie wilma wyatt xavier yesenia yolanda
yvette yvonne zach zachary zane zoe zoey`

	censusSurnameWords = `abbott acevedo acosta adams adkins aguilar aguirre ahmed alexander alfaro ali allen allison
alvarado alvarez amaya andersen anderson andrade andrews anthony arellano arias armstrong arnold
arroyo ashley atkins atkinson austin avalos avery avila ayala ayers bailey baker baldwin ball
ballard banks barajas barber barker barnes barnett barr barrera barrett barron barry bartlett
barton bass bates bauer bautista baxter bean beard beasley beck becker bell beltran bender
benitez benjamin bennett benson bentley benton berg berger bernal bernard berry best bishop
black blackburn blackwell blair blake blanchard blanco blankenship blevins bond bonilla booker
boone booth bowen bowers bowman boyd boyer boyle bradford bradley bradshaw brady brandt bravo
brennan brewer bridges briggs brock brooks brown browning bruce bryan bryant buchanan buck
buckley bui bullock burch burgess burke burnett burns burton bush butler byrd cabrera cain
calderon caldwell calhoun callahan camacho cameron campbell campos cannon cano cantu cardenas
cardona carey carlson carpenter carr carrillo carroll carson carter case casey castaneda
castillo castro cervantes chambers chan chandler chang chapman charles chase chavez chen cheng
cho choi christensen christian chung cisneros clark clarke clay clayton clements cline cobb
cochran coffey cohen cole coleman collier collins colon combs compton conley conner conrad
contreras conway cook cooper copeland cordova corona correa cortes cortez costa cox craig crane
crawford crosby cross cruz cuevas cummings cunningham curry curtis dalton dang daniel daniels
davenport david davidson davila davis dawson day dean decker dejesus delacruz delarosa deleon
delgado dennis diaz dickerson dillon dixon do dodson doe dominguez donaldson donovan dorsey
dougherty douglas doyle drake duarte dudley duffy duncan dunlap dunn duran durham dyer eaton
edwards elliott ellis ellison english enriquez erickson escobar esparza espinosa espinoza
esquivel estes estrada evans everett farley farmer farrell faulkner felix ferguson fernandez
fields figueroa finley fischer fisher fitzgerald fitzpatrick fleming fletcher flores flowers
floyd flynn foley ford foster fowler fox francis franco frank franklin frazier frederick freeman
french friedman frost fry frye fuentes fuller gaines galindo gallagher gallegos galvan garcia
gardner garner garrett garrison garza gates gentry george gibbs gibson gilbert giles gill
gillespie gilmore glass glenn glover golden gomez gonzales gonzalez good goodman goodwin gordon
gould graham grant graves gray green greene greer gregory griffin griffith grimes gross guerra
guerrero guevara gutierrez guzman hahn hale haley hall hamilton hammond hampton han hancock
hanna hansen hanson hardin harding hardy harmon harper harrell harrington harris harrison hart
hartman harvey hawkins hayden hayes haynes heath hebert henderson hendricks henry hensley henson
herman hernandez herrera herring hess hickman hicks higgins hill hines ho hoang hobbs hodge
hodges hoffman hogan holland holloway holmes holt hood hoover hopkins horn horne horton house
houston howard howe howell huang hubbard huber hudson huerta huff huffman hughes hull humphrey
hunt hunter hurley hurst hutchinson huynh ibarra ingram jackson jacobs jacobson james jaramillo
jefferson jenkins jennings jensen jimenez john johns johnson johnston jones jordan joseph juarez
kane kang kaur keith keller kelley kelly kemp kennedy kent kerr khan kim king kirby kirk klein
kline knapp knight knox koch kramer krueger kumar lam lamb lambert landry lane lang lara larsen
larson lawrence lawson le leach leal leblanc lee leon leonard lester levy lewis li lim lin
lindsey little liu livingston lloyd logan long lopez love lowe lowery lozano lu lucas lucero
lugo luna lynch lynn lyons ma macdonald macias mack maddox magana mahoney maldonado malone mann
manning marin marks marquez marsh marshall martin martinez mason massey mata mathews mathis
matthews maxwell may mayer maynard mays mcbride mccall mccarthy mccarty mcclain mcclure
mcconnell mccormick mccoy mccullough mcdaniel mcdonald mcdowell mcfarland mcgee mcguire mcintosh
mcintyre mckay mckee mckenzie mckinney mclaughlin mclean mcmahon mcmillan mcpherson meadows
medina medrano mejia melendez melton mendez mendoza mercado merritt meyer meyers meza michael
middleton miles miller mills miranda mitchell mohamed molina monroe montes montgomery montoya
moody moon moore mora morales moran moreno morgan morris morrison morrow morse morton moses
mosley moss moyer mueller mullen mullins munoz murillo murphy murray myers nash nava navarro
neal nelson newman newton ngo nguyen nichols nicholson nielsen nieves nixon noble nolan norman
norris norton nunez obrien ochoa oconnell oconnor odonnell oliver olsen olson oneal oneill
orozco orr ortega ortiz osborne owen owens pace pacheco padilla page palacios palmer park parker
parks parra parrish parsons patel patrick patterson patton paul payne pearson peck pena
pennington peralta perez perkins perry person peters petersen peterson pham phan phelps phillips
pierce pierre pineda pittman pitts ponce poole pope porter portillo potter potts powell powers
pratt preston price prince pruitt pugh quinn quinones quintana quintero ramirez ramos ramsey
randall randolph rangel rasmussen ray raymond reed reese reeves reid reilly reyes reynolds
rhodes rice rich richard richards richardson richmond riley rios rivas rivera rivers roach
robbins roberson roberts robertson robinson robles rocha rodgers rodriguez rogers rojas roman
romero rosales rosario rosas rose ross roth rowe roy rubio ruiz rush russell russo ryan salas
salazar salgado salinas sampson sanchez sanders sandoval sanford santana santiago santos
saunders savage sawyer schaefer schmidt schmitt schneider schroeder schultz schwartz scott
sellers serrano sexton shaffer shah shannon sharma sharp shaw shelton shepard shepherd sheppard
sherman shields short sierra silva simmons simon simpson sims singh singleton skinner sloan
small smith snow snyder solis solomon sosa soto sparks spears spence spencer stafford stanley
stanton stark steele stein stephens stephenson stevens stevenson stewart stokes stone stout
strickland strong stuart suarez sullivan summers sun sutton swanson sweeney tan tang tanner
tapia tate taylor terry thomas thompson thornton todd torres townsend tran trejo trevino
trujillo truong tucker turner tyler underwood valdez valencia valentine valenzuela vance vang
vargas vasquez vaughan vaughn vazquez vega velasquez velazquez velez ventura villa villalobos
villanueva villarreal villegas vincent vo vu wade wagner walker wall wallace walls walsh walter
walters walton wang ward ware warner warren washington waters watkins watson watts weaver webb
weber webster weeks weiss welch wells west wheeler whitaker white whitehead wiggins wilcox wiley
wilkerson wilkins wilkinson williams williamson willis wilson winters wise wolf wolfe wong wood
woodard woods woodward wright wu wyatt xiong xu yang yates yoder york young yu zamora zavala
zhang zhao zheng zhou zhu zimmerman zuniga`
)
